Repository nv-morpheus/Morpheus, pull requests merged in 2022-05, with the labels that each got.

#58 Fix type-o in log parsing example & small formatting fix
  examples/log_parsing/README.md
  examples/log_parsing/preprocessing.py
  examples/log_parsing/run.py
Labels: non-breaking, improvement, 5 - Ready to Merge

#74 Fix typos in README.md & Change GitLab-style reference in CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: non-breaking, doc

#61 Fix the nlp_si_detection example
  examples/nlp_si_detection/README.md
Labels: bug, non-breaking, 3 - Ready for Review

#66 Clear log handlers after each test
  tests/conftest.py
Labels: non-breaking, improvement, 5 - Ready to Merge

#79 Revert "Install new apt key"
  docker/Dockerfile
Labels: enhancement, non-breaking, improvement, 3 - Ready for Review

#82 Rename mlflow conda env file
  models/mlflow/README.md
  models/mlflow/docker/Dockerfile
  models/mlflow/docker/conda/mlflow-env.yml
Labels: non-breaking, improvement, 5 - Ready to Merge

#91 Updates to README.md for clarity
  README.md
Labels: non-breaking, doc, 3 - Ready for Review

#90 Update hammah-inference.py
  models/validation-inference-scripts/hammah-models/hammah-inference.py
Labels: bug, non-breaking, 3 - Ready for Review, 4 - Needs Reviewer

#97 Apply enterprise sphinx html theme to docs
  docs/source/_static/main_nv_logo_square.png
  docs/source/_static/omni-style.css
  docs/source/conf.py
Labels: non-breaking, doc, 3 - Ready for Review

#100 Add pybind11/cython stubs to Morpheus package
  .gitignore
  CMakeLists.txt
  morpheus/_lib/CMakeLists.txt
  morpheus/_lib/src/python_modules/stages.cpp
  morpheus/cmake/utils/python_module_tools.cmake
  morpheus/py.typed
  setup.py
Labels: non-breaking, feature request, 5 - Ready to Merge

#81 Update morpheus dev container to support flag for building with debug python build + source files.
  CONTRIBUTING.md
  ci/conda/recipes/python-dbg/build.sh
  ci/conda/recipes/python-dbg/conda_build_config.yaml
  ci/conda/recipes/python-dbg/meta.yaml
  ci/conda/recipes/python_dbg_install.sh
  ci/conda/recipes/run_conda_build.sh
  docker/Dockerfile
Labels: enhancement, non-breaking, feature request, 5 - Ready to Merge

#106 Update morpheus_quickstart_guide.md
  docs/source/morpheus_quickstart_guide.md
Labels: non-breaking, doc, 3 - Ready for Review

#109 Add pybind11-stubgen to conda environment yaml.
  docker/conda/environments/cuda11.4_dev.yml
Labels: bug, non-breaking, 5 - Ready to Merge

#80 Jenkins integration
  ci/Jenkinsfile
  ci/conda/recipes/cudf/meta.yaml
  ci/conda/recipes/morpheus/morpheus_build.sh
  ci/conda/recipes/run_conda_build.sh
  ci/scripts/common.sh
  ci/scripts/jenkins/build.sh
  ci/scripts/jenkins/checks.sh
  ci/scripts/jenkins/common.sh
  ci/scripts/jenkins/docs.sh
  ci/scripts/jenkins/test.sh
  docker/conda/environments/cuda11.4_ci.yml
  docker/conda/environments/requirements.txt
Labels: non-breaking, improvement, 5 - Ready to Merge

#118 Updating CODEOWNERS for New Organization
  .github/CODEOWNERS
Labels: non-breaking, feature request

#96 Updates to developer_guide for clarity.
  docs/source/developer_guide/architecture.md
  docs/source/developer_guide/guides/1_simple_python_stage.md
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/developer_guide/guides/3_simple_cpp_stage.md
  docs/source/developer_guide/guides/4_source_cpp_stage.md
Labels: non-breaking, doc, 3 - Ready for Review

#62 Ensure default path values in morpheus.cli are no longer relative
  .gitattributes
  CMakeLists.txt
  MANIFEST.in
  docs/source/basics/examples.rst
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/morpheus_quickstart_guide.md
  examples/abp_nvsmi_detection/README.md
  examples/abp_pcap_detection/README.md
  examples/abp_pcap_detection/abp_pcap_preprocessing.py
  examples/gnn_fraud_detection_pipeline/README.md
  examples/gnn_fraud_detection_pipeline/run.py
  examples/log_parsing/messages.py
  examples/log_parsing/preprocessing.py
  examples/log_parsing/run.py
  examples/nlp_si_detection/README.md
  morpheus/__init__.py
  morpheus/cli.py
  morpheus/cmake/utils/python_module_tools.cmake
  morpheus/data/abp_pcap_dump.jsonlines
  morpheus/data/bert-base-cased-hash.txt
  morpheus/data/bert-base-uncased-hash.txt
  morpheus/data/columns_ae.txt
  morpheus/data/columns_fil.txt
  morpheus/data/email.jsonlines
  morpheus/data/labels_ae.txt
  morpheus/data/labels_nlp.txt
  morpheus/data/labels_phishing.txt
  morpheus/data/nvsmi.jsonlines
  morpheus/data/pcap_dump.jsonlines
  morpheus/data/sid_training_data_truth.csv
  setup.py
  tests/test_cli.py
  tests/utils.py
Labels: bug, non-breaking, 4 - Waiting on Reviewer

#116 Add script to capture triton config
  scripts/get-triton-config.sh
Labels: enhancement, non-breaking, improvement, 5 - Ready to Merge

#131 Set Python3_FIND_STRATEGY=Location
  morpheus/CMakeLists.txt
Labels: non-breaking, feature request, 5 - Ready to Merge

#129 Migrate Neo's tensor code directly into Morpheus
  CMakeLists.txt
  morpheus/_lib/CMakeLists.txt
  morpheus/_lib/cmake/libraries/cuda_utils.cmake
  morpheus/_lib/cmake/libraries/morpheus.cmake
  morpheus/_lib/include/morpheus/messages/memory/inference_memory.hpp
  morpheus/_lib/include/morpheus/messages/memory/inference_memory_fil.hpp
  morpheus/_lib/include/morpheus/messages/memory/inference_memory_nlp.hpp
  morpheus/_lib/include/morpheus/messages/memory/response_memory.hpp
  morpheus/_lib/include/morpheus/messages/memory/response_memory_probs.hpp
  morpheus/_lib/include/morpheus/messages/multi.hpp
  morpheus/_lib/include/morpheus/messages/multi_inference.hpp
  morpheus/_lib/include/morpheus/messages/multi_inference_fil.hpp
  morpheus/_lib/include/morpheus/messages/multi_inference_nlp.hpp
  morpheus/_lib/include/morpheus/messages/multi_response.hpp
  morpheus/_lib/include/morpheus/messages/multi_response_probs.hpp
  morpheus/_lib/include/morpheus/objects/dev_mem_info.hpp
  morpheus/_lib/include/morpheus/objects/rmm_tensor.hpp
  morpheus/_lib/include/morpheus/objects/table_info.hpp
  morpheus/_lib/include/morpheus/objects/tensor.hpp
  morpheus/_lib/include/morpheus/objects/tensor_object.hpp
  morpheus/_lib/include/morpheus/objects/wrapped_tensor.hpp
  morpheus/_lib/include/morpheus/utilities/cupy_util.hpp
  morpheus/_lib/include/morpheus/utilities/matx_util.hpp
  morpheus/_lib/include/morpheus/utilities/tensor_util.hpp
  morpheus/_lib/include/morpheus/utilities/type_util.hpp
  morpheus/_lib/include/morpheus/utilities/type_util_detail.hpp
  morpheus/_lib/src/messages/memory/inference_memory_fil.cpp
  morpheus/_lib/src/messages/memory/inference_memory_nlp.cpp
  morpheus/_lib/src/messages/memory/response_memory.cpp
  morpheus/_lib/src/messages/memory/response_memory_probs.cpp
  morpheus/_lib/src/messages/multi.cpp
  morpheus/_lib/src/messages/multi_inference.cpp
  morpheus/_lib/src/messages/multi_inference_fil.cpp
  morpheus/_lib/src/messages/multi_inference_nlp.cpp
  morpheus/_lib/src/messages/multi_response.cpp
  morpheus/_lib/src/messages/multi_response_probs.cpp
  morpheus/_lib/src/objects/neo_wrapped_tensor.cpp
  morpheus/_lib/src/objects/rmm_tensor.cpp
  morpheus/_lib/src/objects/table_info.cpp
  morpheus/_lib/src/objects/tensor.cpp
  morpheus/_lib/src/objects/tensor_object.cpp
  morpheus/_lib/src/objects/wrapped_tensor.cpp
  morpheus/_lib/src/python_modules/common.cpp
  morpheus/_lib/src/stages/add_classification.cpp
  morpheus/_lib/src/stages/add_scores.cpp
  morpheus/_lib/src/stages/filter_detection.cpp
  morpheus/_lib/src/stages/preprocess_fil.cpp
  morpheus/_lib/src/stages/preprocess_nlp.cpp
  morpheus/_lib/src/stages/triton_inference.cpp
  morpheus/_lib/src/utilities/cupy_util.cpp
  morpheus/_lib/src/utilities/matx_util.cu
  morpheus/_lib/src/utilities/tensor_util.cpp
  morpheus/_lib/src/utilities/type_util.cu
  morpheus/_lib/src/utilities/type_util_detail.cpp
  morpheus/_lib/tests/CMakeLists.txt
  morpheus/_lib/tests/test_cuda.cu
  morpheus/_lib/tests/test_main.cpp
  morpheus/_lib/tests/test_morpheus.hpp
  morpheus/_lib/tests/test_tensor.cpp
  morpheus/_lib/tests/test_type_util_detail.cpp
Labels: non-breaking, feature request, 5 - Ready to Merge
