Repository nv-morpheus/Morpheus, pull requests merged in 2022-09, with the labels that each got.

#308 kafka integration tests
  ci/scripts/jenkins/test.sh
  morpheus/_lib/include/morpheus/stages/kafka_source.hpp
  morpheus/_lib/src/io/serializers.cpp
  morpheus/_lib/src/python_modules/stages.cpp
  morpheus/_lib/src/stages/kafka_source.cpp
  morpheus/cli.py
  morpheus/stages/inference/triton_inference_stage.py
  morpheus/stages/input/kafka_source_stage.py
  morpheus/stages/output/write_to_kafka_stage.py
  morpheus/utils/compare_df.py
  pyproject.toml
  tests/conftest.py
  tests/test_abp_kafka.py
  tests/test_hammah_kafka.py
  tests/test_kafka_source_stage_pipe.py
  tests/test_phishing_kafka.py
  tests/test_sid_kafka.py
  tests/test_write_to_kafka_stage_pipe.py
  tests/utils.py
Labels: breaking, improvement, 3 - Ready for Review

#332 Fixing compilation with SRF 22.08a
  CMakeLists.txt
  CONTRIBUTING.md
  README.md
  ci/Jenkinsfile
  ci/conda/recipes/morpheus/conda_build_config.yaml
  ci/conda/recipes/morpheus/meta.yaml
  ci/scripts/jenkins/checks.sh
  cmake/dependencies.cmake
  cmake/import-rapids-cmake.cmake
  docker/Dockerfile
  docker/build_container.sh
  docker/conda/environments/cuda11.5_dev.yml
  docs/source/index.rst
  docs/source/morpheus_quickstart_guide.md
  morpheus/_lib/cmake/libraries/cudf_helpers.cmake
  morpheus/_lib/include/morpheus/objects/tensor_object.hpp
  morpheus/_lib/src/objects/tensor_object.cpp
Labels: bug, non-breaking

#336 Branch 22.09 merge 22.08
  CHANGELOG.md
  CMakeLists.txt
  CONTRIBUTING.md
  README.md
  ci/Jenkinsfile
  ci/conda/recipes/morpheus/conda_build_config.yaml
  ci/conda/recipes/morpheus/meta.yaml
  ci/scripts/common.sh
  ci/scripts/jenkins/checks.sh
  cmake/dependencies.cmake
  cmake/import-rapids-cmake.cmake
  docker/Dockerfile
  docker/build_container.sh
  docker/conda/environments/cuda11.5_ci.yml
  docker/conda/environments/cuda11.5_dev.yml
  docs/source/index.rst
  docs/source/morpheus_quickstart_guide.md
  morpheus/_lib/cmake/libraries/cudf_helpers.cmake
  morpheus/_lib/include/morpheus/objects/tensor_object.hpp
  morpheus/_lib/src/objects/tensor_object.cpp
Labels: bug, non-breaking

#304 Initial example readme
  examples/README.md
Labels: non-breaking, doc, 4 - Waiting on Author

#353 Update Dockerfile
  docker/Dockerfile
Labels: dependencies, non-breaking, improvement, 3 - Ready for Review

#315 Digital Fingerprinting 2.0 Pipelines
  docker/conda/environments/requirements.txt
  docs/source/morpheus_quickstart_guide.md
  examples/digital_fingerprinting/README.md
  examples/digital_fingerprinting/run_cloudtrail_dfp.py
  models/.gitattributes
  models/README.md
  models/datasets/training-data/azure/AZUREAD-DIAG-2022-05-09T21.08.53Z.json
  models/datasets/training-data/dfp-cloudtrail-role-g-training-data.csv
  models/datasets/training-data/dfp-cloudtrail-user123-training-data.csv
  models/datasets/validation-data/dfp-cloudtrail-role-g-validation-data-input.csv
  models/datasets/validation-data/dfp-cloudtrail-role-g-validation-data-output.csv
  models/datasets/validation-data/dfp-cloudtrail-user123-validation-data-input.csv
  models/datasets/validation-data/dfp-cloudtrail-user123-validation-data-output.csv
  models/dfp-models/hammah-role-g-20211017-dill.pkl
  models/dfp-models/hammah-user123-20211017-dill.pkl
  models/training-tuning-scripts/dfp-models/hammah-20211017-script.py
  models/training-tuning-scripts/dfp-models/hammah-20211017.ipynb
  models/validation-inference-scripts/dfp-models/.gitkeep
  models/validation-inference-scripts/dfp-models/hammah-inference.py
  models/validation-inference-scripts/dfp-models/requirements.txt
  morpheus.code-workspace
  morpheus/cli/commands.py
  morpheus/cli/register_stage.py
  morpheus/cli/stage_registry.py
  morpheus/cli/utils.py
  morpheus/config.py
  morpheus/data/columns_ae_azure.txt
  morpheus/data/columns_ae_cloudtrail.txt
  morpheus/data/columns_ae_duo.txt
  morpheus/messages/multi_ae_message.py
  morpheus/messages/multi_inference_ae_message.py
  morpheus/messages/multi_response_message.py
  morpheus/stages/inference/auto_encoder_inference_stage.py
  morpheus/stages/input/autoencoder_source_stage.py
  morpheus/stages/input/azure_source_stage.py
  morpheus/stages/input/cloud_trail_source_stage.py
  morpheus/stages/input/duo_source_stage.py
  morpheus/stages/preprocess/preprocess_ae_stage.py
  morpheus/stages/preprocess/train_ae_stage.py
  scripts/validation/hammah/val-hammah.sh
  scripts/validation/kafka_testing.md
  scripts/validation/val-run-pipeline.sh
  setup.py
  tests/benchmarks/e2e_test_configs.json
  tests/benchmarks/test_bench_e2e_pipelines.py
  tests/test_cli.py
  tests/test_dfp.py
  tests/test_dfp_kafka.py
  tests/tests_data/dfp_roleg_anomaly_score.csv
  tests/tests_data/dfp_roleg_exp_results.csv
  tests/tests_data/dfp_roleg_tensor.csv
  tests/tests_data/dfp_user123_anomaly_score.csv
  tests/tests_data/dfp_user123_exp_results.csv
  tests/tests_data/dfp_user123_tensor.csv
  tests/tests_data/hammah_roleg_anomaly_score.csv
  tests/tests_data/hammah_user123_anomaly_score.csv
Labels: enhancement, non-breaking, feature request

#360 Removing `grpcio-channelz`
  ci/conda/recipes/morpheus/meta.yaml
  docker/conda/environments/cuda11.5_dev.yml
  docker/conda/environments/requirements.txt
  setup.py
Labels: bug, non-breaking

#333 Fix broken developer guide code examples
  CMakeLists.txt
  ci/scripts/jenkins/build.sh
  docs/source/developer_guide/guides/1_simple_python_stage.md
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/developer_guide/guides/3_simple_cpp_stage.md
  docs/source/developer_guide/guides/4_source_cpp_stage.md
  examples/CMakeLists.txt
  examples/developer_guide/1_simple_python_stage/pass_thru.py
  examples/developer_guide/1_simple_python_stage/run.py
  examples/developer_guide/2_1_real_world_phishing/recipient_features_stage.py
  examples/developer_guide/2_1_real_world_phishing/run.py
  examples/developer_guide/2_2_rabbitmq/README.md
  examples/developer_guide/2_2_rabbitmq/__init__.py
  examples/developer_guide/2_2_rabbitmq/rabbitmq_source_stage.py
  examples/developer_guide/2_2_rabbitmq/read_simple.py
  examples/developer_guide/2_2_rabbitmq/requirements.txt
  examples/developer_guide/2_2_rabbitmq/write_simple.py
  examples/developer_guide/2_2_rabbitmq/write_to_rabbitmq_stage.py
  examples/developer_guide/3_simple_cpp_stage/CMakeLists.txt
  examples/developer_guide/3_simple_cpp_stage/_lib/__init__.py
  examples/developer_guide/3_simple_cpp_stage/_lib/pass_thru.cpp
  examples/developer_guide/3_simple_cpp_stage/_lib/pass_thru.hpp
  examples/developer_guide/3_simple_cpp_stage/pass_thru.py
  examples/developer_guide/3_simple_cpp_stage/run.py
  examples/developer_guide/4_rabbitmq_cpp_stage/CMakeLists.txt
  examples/developer_guide/4_rabbitmq_cpp_stage/README.md
  examples/developer_guide/4_rabbitmq_cpp_stage/__init__.py
  examples/developer_guide/4_rabbitmq_cpp_stage/_lib/__init__.py
  examples/developer_guide/4_rabbitmq_cpp_stage/_lib/rabbitmq_source.cpp
  examples/developer_guide/4_rabbitmq_cpp_stage/_lib/rabbitmq_source.hpp
  examples/developer_guide/4_rabbitmq_cpp_stage/cmake/Configure_SimpleAmqpClient.cmake
  examples/developer_guide/4_rabbitmq_cpp_stage/cmake/Configure_rabbitmq.cmake
  examples/developer_guide/4_rabbitmq_cpp_stage/cmake/dependencies.cmake
  examples/developer_guide/4_rabbitmq_cpp_stage/rabbitmq_source_stage.py
  examples/developer_guide/4_rabbitmq_cpp_stage/read_simple.py
  examples/developer_guide/4_rabbitmq_cpp_stage/requirements.txt
  examples/developer_guide/4_rabbitmq_cpp_stage/write_simple.py
  examples/developer_guide/4_rabbitmq_cpp_stage/write_to_rabbitmq_stage.py
  morpheus/pipeline/stream_wrapper.py
Labels: non-breaking, doc, 3 - Ready for Review

#359 Demo notebook for DFP feature selection with toy dataset
  models/.gitattributes
  models/datasets/training-data/azure/READ.ME
  models/datasets/training-data/azure/azure-ad-logs-sample-training-data.json
  models/training-tuning-scripts/dfp-models/dfp-feature-selection-demo.ipynb
  models/training-tuning-scripts/dfp-models/steps.png
Labels: non-breaking, feature request, 4 - Waiting on Author

#361 Bump Versions 22.09
  README.md
  cmake/dependencies.cmake
  cmake/deps/Configure_srf.cmake
  cmake/import-rapids-cmake.cmake
  docker/conda/environments/cuda11.5_dev.yml
  docs/source/index.rst
  docs/source/morpheus_quickstart_guide.md
Labels: non-breaking, feature request

#366 Adjustments for docker build inclusion of morpheus-visualization
  .gitmodules
  ci/scripts/jenkins/test.sh
  docker/Dockerfile
Labels: bug, breaking, 3 - Ready for Review, Priority 0

#369 Wholesale updates for tritonserver version
  README.md
  docs/source/developer_guide/guides/2_real_world_phishing.md
  examples/abp_nvsmi_detection/README.md
  examples/abp_pcap_detection/README.md
  examples/log_parsing/README.md
  examples/nlp_si_detection/README.md
  examples/ransomware_detection/README.md
  examples/sid_visualization/docker-compose.yml
  models/triton-model-repo/README.md
  scripts/validation/kafka_testing.md
  scripts/validation/val-globals.sh
  scripts/validation/val-utils.sh
  tests/benchmarks/README.md
Labels: non-breaking, doc, 3 - Ready for Review

#367 Mlflow update 2209
  models/mlflow/README.md
  models/mlflow/docker/Dockerfile
  models/mlflow/docker/conda/mlflow-env.yml
Labels: dependencies, non-breaking, improvement, 3 - Ready for Review, Priority 0

#372 Use libcudacxx from NVIDIA repo
  cmake/dependencies.cmake
  cmake/deps/rapids_cpm_package_overrides.json
Labels: dependencies, non-breaking, improvement, 3 - Ready for Review

#371 DFP Updates to enable example workflows
  examples/digital_fingerprinting/fetch_example_data.py
  examples/digital_fingerprinting/starter/README.md
  morpheus/cli/commands.py
  morpheus/stages/input/azure_source_stage.py
  morpheus/stages/input/duo_source_stage.py
  morpheus/stages/preprocess/train_ae_stage.py
Labels: non-breaking, improvement, 3 - Ready for Review, 5 - Ready to Merge

#387 Pin numba version
  docker/conda/environments/cuda11.5_dev.yml
Labels: bug, non-breaking, 5 - Ready to Merge

#386 Training and validation script and notebook fixes.
  models/training-tuning-scripts/abp-models/requirements.txt
  models/training-tuning-scripts/dfp-models/hammah-20211017-script.py
  models/training-tuning-scripts/fraud-detection-models/requirements.txt
  models/training-tuning-scripts/log-parsing-models/requirements.txt
  models/training-tuning-scripts/phishing-models/phish-bert-20211006.ipynb
  models/training-tuning-scripts/phishing-models/requirements.txt
  models/training-tuning-scripts/ransomware-models/requirements.txt
  models/validation-inference-scripts/abp-models/abp-inference.py
  models/validation-inference-scripts/dfp-models/hammah-inference.py
  models/validation-inference-scripts/log-parsing-models/log-parsing-inference.py
  models/validation-inference-scripts/log-parsing-models/requirements.txt
  models/validation-inference-scripts/phishing-models/phish-bert-20220113-inference-script.py
Labels: bug, non-breaking, 5 - Ready to Merge

#383 Add websockets dependency for viz
  docker/conda/environments/requirements.txt
  examples/sid_visualization/README.md
Labels: bug, non-breaking, 3 - Ready for Review

#382 Update Quickstart Guide for 22.09
  docs/source/morpheus_quickstart_guide.md
Labels: non-breaking, doc, 3 - Ready for Review

#370 Starter DFP docstring updates
  morpheus/stages/input/autoencoder_source_stage.py
  morpheus/stages/input/azure_source_stage.py
  morpheus/stages/input/duo_source_stage.py
  morpheus/stages/preprocess/preprocess_ae_stage.py
  morpheus/stages/preprocess/train_ae_stage.py
Labels: non-breaking, doc, 5 - Ready to Merge

#380 Update HAMMAH E2E benchmark test to DFP 2.0
  tests/benchmarks/test_bench_e2e_pipelines.py
Labels: non-breaking, improvement, 5 - Ready to Merge

#368 Misc DFP Documentation & fixes
  docs/source/_static/omni-style.css
  docs/source/developer_guide/guides/5_digital_fingerprinting.md
  docs/source/developer_guide/guides/img/dfp_deployment_configs.png
  docs/source/developer_guide/guides/img/dfp_inference_overview.png
  docs/source/developer_guide/guides/img/dfp_input_config.png
  docs/source/developer_guide/guides/img/dfp_output_config.png
  docs/source/developer_guide/guides/img/dfp_pipeline_structure.png
  docs/source/developer_guide/guides/img/dfp_training_overview.png
  examples/digital_fingerprinting/production/Dockerfile
  examples/digital_fingerprinting/production/README.md
  examples/digital_fingerprinting/production/conda_env.yml
  examples/digital_fingerprinting/production/docker-compose.yml
  examples/digital_fingerprinting/production/mlflow/Dockerfile
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_file_batcher_stage.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_file_to_df.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/multi_file_source.py
  examples/digital_fingerprinting/production/morpheus/dfp/utils/column_info.py
  examples/digital_fingerprinting/production/morpheus/dfp/utils/file_utils.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_inference.ipynb
  examples/digital_fingerprinting/production/morpheus/dfp_azure_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_training.ipynb
  examples/digital_fingerprinting/production/morpheus/dfp_duo_inference.ipynb
  examples/digital_fingerprinting/production/morpheus/dfp_duo_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_duo_training.ipynb
  examples/digital_fingerprinting/production/morpheus/launch.sh
  examples/digital_fingerprinting/starter/README.md
  morpheus/cli/commands.py
  morpheus/cli/utils.py
  morpheus/stages/input/azure_source_stage.py
  morpheus/stages/input/duo_source_stage.py
Labels: non-breaking, doc, 3 - Ready for Review

#378 [REVIEW] updating the filenames in the paths and adding the missing file for abp
  models/datasets/training-data/abp-sample-nvsmi-training-data.json
  models/training-tuning-scripts/abp-models/abp-nvsmi-xgb-20210310.ipynb
  models/training-tuning-scripts/abp-models/abp-nvsmi-xgb-20210310.py
  models/training-tuning-scripts/dfp-models/hammah-20211017.ipynb
Labels: bug, non-breaking, 3 - Ready for Review

#377 Ransomware models need update for Triton 22.08
  examples/ransomware_detection/README.md
  examples/ransomware_detection/models/ransomw-model-long-rf/1/checkpoint.tl
  examples/ransomware_detection/models/ransomw-model-medium-rf/1/checkpoint.tl
  examples/ransomware_detection/models/ransomw-model-short-rf/1/checkpoint.tl
  examples/ransomware_detection/run.py
Labels: bug, non-breaking, 3 - Ready for Review
