Repository nv-morpheus/Morpheus, pull requests merged in 2022-04, with the labels that each got.

#15 fix to_file "overwrite" option for cli
  morpheus/pipeline/output/to_file.py
Labels: bug, non-breaking

#29 Removing `no_args_is_help` from CLI commands
  morpheus/cli.py
Labels: bug, non-breaking

#23 TensorRT installation warning for onnx_to_trt
  docs/source/conf.py
  morpheus/utils/onnx_to_trt.py
Labels: non-breaking, improvement

#28 Log parsing example updates
  examples/log_parsing/README.md
  examples/log_parsing/run.py
Labels: bug, non-breaking

#33 Fix default DOCKER_IMAGE_TAG to match that of build_container_release.sh
  docker/run_container_release.sh
Labels: bug, non-breaking

#27 Update CONTRIBUTING.md & fix file ownership
  CONTRIBUTING.md
  docker/build_conda_packages.sh
  docker/conda/environments/cuda11.4_dev.yml
Labels: non-breaking, doc

#32 [BUG] fix incorrect bert vocab and hash in training-tuning-scripts/log-parsing/resources
  models/training-tuning-scripts/log-parsing-models/resources/bert-base-cased-hash.txt
  models/training-tuning-scripts/log-parsing-models/resources/bert-base-cased-vocab.txt
Labels: bug, non-breaking

#16 Quickstart guide
  docs/source/morpheus_quickstart_guide.md
Labels: non-breaking, doc

#34 Large Reorg of Developer Docs
  README.md
  basic_usage_img/monitor_throughput.png
  docs/source/basic_usage.rst
  docs/source/basics/building_a_pipeline.rst
  docs/source/basics/examples.rst
  docs/source/basics/img/monitor_throughput.png
  docs/source/basics/img/multi_monitor_throughput.png
  docs/source/basics/img/nlp_kitchen_sink.png
  docs/source/basics/img/remove_fields_from_json_objects.png
  docs/source/basics/img/simple_identity.png
  docs/source/basics/overview.rst
  docs/source/conf.py
  docs/source/developer_guide/architecture.md
  docs/source/developer_guide/guides.rst
  docs/source/developer_guide/guides/1_simple_python_stage.md
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/developer_guide/guides/3_simple_cpp_stage.md
  docs/source/developer_guide/guides/4_source_cpp_stage.md
  docs/source/developer_guide/guides/img/sink_deps.png
  docs/source/extra_info/known_issues.md
  docs/source/extra_info/performance.md
  docs/source/extra_info/troubleshooting.md
  docs/source/index.rst
  docs/source/intro.rst
  docs/source/kafka.rst
  docs/source/morpheus_developer_documentation.md
  docs/source/morpheus_quickstart_guide.md
  docs/source/stages.rst
  docs/source/triton.rst
Labels: non-breaking, doc

#36 Fixing pytest in conda build
  ci/conda/recipes/morpheus/meta.yaml
Labels: bug, non-breaking

#38 Quickstart guide changes
  docs/source/morpheus_quickstart_guide.md
Labels: non-breaking, doc

#40 CONTRIBUTING.md typeos
  CONTRIBUTING.md
Labels: non-breaking, doc

#41 Update README.md
  README.md
Labels: non-breaking, doc

#42 Update morpheus_quickstart_guide.md
  docs/source/morpheus_quickstart_guide.md
Labels: non-breaking, doc

#44 Update abp_nvsmi_detection example
  examples/abp_nvsmi_detection/README.md
Labels: non-breaking, doc

#46 Changing runtime-22.04 to 22.04-runtime
  docker/build_container_release.sh
  docker/run_container_release.sh
  docs/source/index.rst
Labels: bug, non-breaking

#50 Adding option to specify a conda channel alias during conda-build
  ci/conda/recipes/run_conda_build.sh
  docker/Dockerfile
Labels: bug, non-breaking

#52 Typo in run_container_release.sh script
  docker/run_container_release.sh
Labels: bug, non-breaking

#56 Update license header for readme
  examples/log_parsing/README.md
Labels: non-breaking, doc

#57 Adding build arg to use conda mirror
  ci/conda/recipes/run_conda_build.sh
  docker/Dockerfile
Labels: bug, non-breaking

#49 Fix typeos in abp_pcap_detection
  examples/abp_pcap_detection/README.md
  examples/abp_pcap_detection/run.py
Labels: bug, non-breaking

#53 Fixes bug in WriteToFileStage when configured with a filename without a path
  morpheus/pipeline/output/to_file.py
  tests/conftest.py
  tests/test_file_in_out_stage_pipe.py
Labels: bug, non-breaking, 3 - Ready for Review

#71 Updated README with documentation links and banner image
  README.md
  img/morpheus-banner.png
Labels: non-breaking, doc, 3 - Ready for Review

#76 Update README.md
  README.md
Labels: non-breaking, doc, 3 - Ready for Review

#72 Install new apt key in docker
  docker/Dockerfile
Labels: bug, non-breaking, 5 - Ready to Merge
