Repository nv-morpheus/Morpheus, pull requests merged in 2022-11, with the labels that each got.

#429 Set channels and versions to ensure we get a good version of tensorflow
  examples/gnn_fraud_detection_pipeline/README.md
  examples/gnn_fraud_detection_pipeline/requirements.yml
Labels: non-breaking, doc, 3 - Ready for Review

#419 MultiInferenceMessage & MultiResponseMessage share a new base class
  morpheus/_lib/cmake/libraries/morpheus.cmake
  morpheus/_lib/include/morpheus/io/deserializers.hpp
  morpheus/_lib/include/morpheus/messages/memory/inference_memory.hpp
  morpheus/_lib/include/morpheus/messages/memory/response_memory_probs.hpp
  morpheus/_lib/include/morpheus/messages/memory/tensor_memory.hpp
  morpheus/_lib/include/morpheus/messages/multi_inference.hpp
  morpheus/_lib/include/morpheus/messages/multi_inference_fil.hpp
  morpheus/_lib/include/morpheus/messages/multi_inference_nlp.hpp
  morpheus/_lib/include/morpheus/messages/multi_response.hpp
  morpheus/_lib/include/morpheus/messages/multi_response_probs.hpp
  morpheus/_lib/include/morpheus/messages/multi_tensor.hpp
  morpheus/_lib/include/morpheus/objects/tensor.hpp
  morpheus/_lib/include/morpheus/stages/file_source.hpp
  morpheus/_lib/src/io/deserializers.cpp
  morpheus/_lib/src/messages/memory/response_memory_probs.cpp
  morpheus/_lib/src/messages/multi_inference.cpp
  morpheus/_lib/src/messages/multi_inference_fil.cpp
  morpheus/_lib/src/messages/multi_inference_nlp.cpp
  morpheus/_lib/src/messages/multi_response.cpp
  morpheus/_lib/src/messages/multi_response_probs.cpp
  morpheus/_lib/src/messages/multi_tensor.cpp
  morpheus/_lib/src/stages/file_source.cpp
  morpheus/_lib/src/stages/kafka_source.cpp
  morpheus/_lib/src/stages/triton_inference.cpp
  morpheus/_lib/tests/CMakeLists.txt
  morpheus/_lib/tests/test_matx_util.cpp
  morpheus/_lib/tests/test_morpheus.cpp
  morpheus/_lib/tests/test_morpheus.hpp
  morpheus/_lib/tests/test_multi_slices.cpp
Labels: non-breaking, improvement, 3 - Ready for Review

#408 Add dockerfile for CI runner
  .github/workflows/ci_pipe.yml
  .github/workflows/pull_request.yml
  ci/runner/Dockerfile
  ci/runner/README.md
  ci/runner/build_and_push.sh
  ci/scripts/github/build.sh
  ci/scripts/github/checks.sh
  ci/scripts/github/common.sh
  ci/scripts/github/docs.sh
  ci/scripts/github/test.sh
  docker/conda/environments/cuda11.5_ci.yml
  docker/conda/environments/cuda11.5_dev.yml
Labels: non-breaking, improvement, 4 - Waiting on Reviewer

#436 Ensure Camouflage is shutdown after every test
  tests/conftest.py
  tests/mock_triton_server/mocks/reset/POST.mock
  tests/mock_triton_server/mocks/v2/models/abp-nvsmi-xgb/infer/POST.mock
  tests/mock_triton_server/mocks/v2/models/phishing-bert-onnx/infer/POST.mock
  tests/mock_triton_server/mocks/v2/models/sid-minibert-onnx-no-trunc/infer/POST.mock
  tests/mock_triton_server/mocks/v2/models/sid-minibert-onnx/infer/POST.mock
Labels: bug, non-breaking

#438 Avoid unnecessary copy in add-scores stage
  morpheus/_lib/src/objects/tensor.cpp
  morpheus/_lib/src/stages/add_classification.cpp
  morpheus/_lib/src/stages/add_scores.cpp
Labels: non-breaking, improvement, 3 - Ready for Review

#418 Add documentation to LinearBoundary stages
  morpheus/pipeline/linear_pipeline.py
  morpheus/stages/boundary/linear_boundary_stage.py
Labels: non-breaking, doc, 3 - Ready for Review

#428 426 bug msg keyerror data
  examples/log_parsing/preprocessing.py
  morpheus/_lib/include/morpheus/stages/preprocess_nlp.hpp
  morpheus/_lib/src/python_modules/stages.cpp
  morpheus/_lib/src/stages/preprocess_nlp.cpp
  morpheus/stages/preprocess/preprocess_nlp_stage.py
  morpheus/utils/logger.py
  tests/conftest.py
  tests/test_sid.py
Labels: bug, non-breaking, 3 - Ready for Review, ! - Hotfix

#450 DFPFileBatcherStage: Sort only by timestamp
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_file_batcher_stage.py
Labels: bug, non-breaking, 3 - Ready for Review

#455 ABP change the arg name in the comment and update req
  models/training-tuning-scripts/abp-models/abp-nvsmi-xgb-20210310.py
  models/training-tuning-scripts/abp-models/requirements.txt
Labels: non-breaking, improvement

#457 Remove warning about tests not having a return value
  tests/test_multi_segment.py
Labels: bug, non-breaking, 3 - Ready for Review

#300 Simplify Python impl for KafkaSourceStage
  docker/conda/environments/cuda11.5_dev.yml
  morpheus/_lib/include/morpheus/stages/kafka_source.hpp
  morpheus/_lib/src/python_modules/stages.cpp
  morpheus/_lib/src/stages/kafka_source.cpp
  morpheus/stages/input/kafka_source_stage.py
  tests/test_abp_kafka.py
  tests/test_cli.py
  tests/test_kafka_source_stage_pipe.py
Labels: non-breaking, improvement, 3 - Ready for Review

#460 Root cause analysis example pipeline
  examples/root_cause_analysis/README.md
  models/.gitattributes
  models/datasets/validation-data/rootcause-validation-data-input.csv
  models/root-cause-models/rootcause-binary-bert-20221118.onnx
  models/triton-model-repo/root-cause-binary-onnx/1/model.onnx
  models/triton-model-repo/root-cause-binary-onnx/config.pbtxt
Labels: non-breaking, feature request, 3 - Ready for Review

#448 Forward Merge `branch-22.09` into `branch-22.09`
  CHANGELOG.md
  examples/log_parsing/preprocessing.py
  models/training-tuning-scripts/abp-models/abp-nvsmi-xgb-20210310.py
  models/validation-inference-scripts/log-parsing-models/log-parsing-inference.py
  morpheus/_lib/include/morpheus/stages/preprocess_nlp.hpp
  morpheus/_lib/src/python_modules/stages.cpp
  morpheus/_lib/src/stages/preprocess_nlp.cpp
  morpheus/stages/preprocess/preprocess_nlp_stage.py
  morpheus/utils/logger.py
  tests/conftest.py
  tests/test_sid.py
Labels: non-breaking, improvement

#468 update for numpy array results on ABP notebook
  models/training-tuning-scripts/abp-models/abp-nvsmi-xgb-20210310.ipynb
Labels: bug, non-breaking, 3 - Ready for Review

#477 Use tritonserver 22.06 for the phishing example
  docs/source/developer_guide/guides/2_real_world_phishing.md
Labels: non-breaking, doc, 3 - Ready for Review

#452 Root cause use case scripts
  models/README.md
  models/model-information.csv
  models/training-tuning-scripts/root-cause-models/binary_sequence_classifier.py
  models/training-tuning-scripts/root-cause-models/dataloader.py
  models/training-tuning-scripts/root-cause-models/dataset.py
  models/training-tuning-scripts/root-cause-models/requirements.txt
  models/training-tuning-scripts/root-cause-models/resources/bert-base-uncased-hash.txt
  models/training-tuning-scripts/root-cause-models/root-cause-bert.ipynb
  models/training-tuning-scripts/root-cause-models/root-cause-bert.py
  models/training-tuning-scripts/root-cause-models/sequence_classifier.py
  models/validation-inference-scripts/root-cause-models/requirements.txt
  models/validation-inference-scripts/root-cause-models/root-cause-inference.py
Labels: non-breaking, feature request, 3 - Ready for Review

#462 Phishing model and data updates
  examples/data/email.jsonlines
  examples/data/email_with_addresses.jsonlines
  models/README.md
  models/datasets/validation-data/phishing-email-validation-data.jsonlines
  models/phishing-models/phishing-bert-20211006.onnx
  models/phishing-models/phishing-bert-20211006.pt
  models/phishing-models/phishing-bert-20221115.onnx
  models/phishing-models/phishing-bert-20221115.pt
  models/training-tuning-scripts/phishing-models/binary_sequence_classifier.py
  models/training-tuning-scripts/phishing-models/phish-bert-20211006-script.py
  models/training-tuning-scripts/phishing-models/phish-bert-20211006.ipynb
  models/training-tuning-scripts/phishing-models/phish-bert-training-script.py
  models/training-tuning-scripts/phishing-models/phish-bert-training.ipynb
  models/training-tuning-scripts/phishing-models/requirements.txt
  models/training-tuning-scripts/phishing-models/sequence_classifier.py
  models/triton-model-repo/phishing-bert-onnx/1/model.onnx
  models/validation-inference-scripts/phishing-models/phish-bert-inference-script.py
  models/validation-inference-scripts/phishing-models/requirements.txt
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.1.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.10.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.11.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.12.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.13.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.14.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.15.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.16.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.17.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.18.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.19.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.2.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.20.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.21.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.22.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.23.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.24.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.25.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.26.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.27.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.28.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.29.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.3.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.30.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.31.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.32.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.33.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.34.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.35.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.4.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.5.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.6.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.7.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.8.body
  tests/mock_triton_server/payloads/phishing/phishing_infer_resp.9.body
  tests/test_phishing.py
  tests/test_phishing_kafka.py
  tests/tests_data/triton_phishing_inf_results.csv
Labels: non-breaking, feature request, 3 - Ready for Review

#470 Root cause analysis datasets
  examples/root_cause_analysis/README.md
  models/datasets/training-data/root-cause-training-data.csv
  models/datasets/training-data/root-cause-unseen-errors.csv
  models/datasets/validation-data/root-cause-validation-data-input.jsonlines
  models/datasets/validation-data/rootcause-validation-data-input.csv
  models/root-cause-models/root-cause-binary-bert-20221118.onnx
  models/triton-model-repo/root-cause-binary-onnx/1/model.onnx
Labels: non-breaking, improvement, 3 - Ready for Review

#474 [DOC] Add datasets readme, change lfs tracking
  models/.gitattributes
  models/datasets/README.md
  models/datasets/training-data/azure/READ.ME
Labels: non-breaking, doc, 3 - Ready for Review

#466 Various Dockerfile-based updates for 22.11
  ci/conda/recipes/morpheus/meta.yaml
  docker/Dockerfile
  docker/conda/environments/cuda11.5_dev.yml
  docker/conda/environments/cuda11.5_runtime.yml
  docker/conda/environments/requirements.txt
  examples/digital_fingerprinting/production/README.md
  examples/digital_fingerprinting/production/mlflow/Dockerfile
  models/mlflow/docker/Dockerfile
  models/mlflow/docker/conda/mlflow-env.yml
Labels: enhancement, dependencies, non-breaking, improvement, 3 - Ready for Review

#478 Improve Morpheus Shutdown Behavior On Exception
  CMakeLists.txt
  ci/scripts/github/build.sh
  morpheus/pipeline/pipeline.py
Labels: bug, non-breaking

#484 Set ver of mlflow client to match that of the server
  examples/digital_fingerprinting/production/conda_env.yml
Labels: bug, non-breaking, 3 - Ready for Review

#439 DFP Visualization Example
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_viz_postproc.py
  examples/digital_fingerprinting/visualization/README.md
  examples/digital_fingerprinting/visualization/dfp_viz_azure_pipeline.py
  examples/digital_fingerprinting/visualization/dfp_viz_duo_pipeline.py
  examples/digital_fingerprinting/visualization/img/screenshot.png
  examples/digital_fingerprinting/visualization/viz
Labels: non-breaking, feature request, 3 - Ready for Review

#458 Documentation Updates
  README.md
  examples/abp_nvsmi_detection/README.md
  examples/digital_fingerprinting/production/README.md
  models/README.md
  models/mlflow/README.md
  morpheus/_lib/CMakeLists.txt
  morpheus/_lib/doxygen/Doxyfile
  morpheus/_lib/doxygen/DoxygenLayout.xml
  morpheus/_lib/doxygen/README.md
  morpheus/_lib/doxygen/header.html
  morpheus/_lib/doxygen/main_page.md
  morpheus/_lib/include/morpheus/io/deserializers.hpp
  morpheus/_lib/include/morpheus/io/serializers.hpp
  morpheus/_lib/include/morpheus/messages/memory/inference_memory.hpp
  morpheus/_lib/include/morpheus/messages/memory/inference_memory_fil.hpp
  morpheus/_lib/include/morpheus/messages/memory/inference_memory_nlp.hpp
  morpheus/_lib/include/morpheus/messages/memory/response_memory.hpp
  morpheus/_lib/include/morpheus/messages/memory/response_memory_probs.hpp
  morpheus/_lib/include/morpheus/messages/memory/tensor_memory.hpp
  morpheus/_lib/include/morpheus/messages/meta.hpp
  morpheus/_lib/include/morpheus/messages/multi.hpp
  morpheus/_lib/include/morpheus/messages/multi_inference.hpp
  morpheus/_lib/include/morpheus/messages/multi_inference_fil.hpp
  morpheus/_lib/include/morpheus/messages/multi_inference_nlp.hpp
  morpheus/_lib/include/morpheus/messages/multi_response.hpp
  morpheus/_lib/include/morpheus/messages/multi_response_probs.hpp
  morpheus/_lib/include/morpheus/messages/multi_tensor.hpp
  morpheus/_lib/include/morpheus/objects/data_table.hpp
  morpheus/_lib/include/morpheus/objects/dev_mem_info.hpp
  morpheus/_lib/include/morpheus/objects/fiber_queue.hpp
  morpheus/_lib/include/morpheus/objects/file_types.hpp
  morpheus/_lib/include/morpheus/objects/python_data_table.hpp
  morpheus/_lib/include/morpheus/objects/rmm_tensor.hpp
  morpheus/_lib/include/morpheus/objects/table_info.hpp
  morpheus/_lib/include/morpheus/objects/tensor.hpp
  morpheus/_lib/include/morpheus/objects/tensor_object.hpp
  morpheus/_lib/include/morpheus/objects/triton_in_out.hpp
  morpheus/_lib/include/morpheus/objects/wrapped_tensor.hpp
  morpheus/_lib/include/morpheus/stages/add_classification.hpp
  morpheus/_lib/include/morpheus/stages/add_scores.hpp
  morpheus/_lib/include/morpheus/stages/deserialize.hpp
  morpheus/_lib/include/morpheus/stages/file_source.hpp
  morpheus/_lib/include/morpheus/stages/filter_detection.hpp
  morpheus/_lib/include/morpheus/stages/kafka_source.hpp
  morpheus/_lib/include/morpheus/stages/preprocess_fil.hpp
  morpheus/_lib/include/morpheus/stages/preprocess_nlp.hpp
  morpheus/_lib/include/morpheus/stages/serialize.hpp
  morpheus/_lib/include/morpheus/stages/triton_inference.hpp
  morpheus/_lib/include/morpheus/stages/write_to_file.hpp
  morpheus/_lib/include/morpheus/utilities/cudf_util.hpp
  morpheus/_lib/include/morpheus/utilities/cupy_util.hpp
  morpheus/_lib/include/morpheus/utilities/matx_util.hpp
  morpheus/_lib/include/morpheus/utilities/stage_util.hpp
  morpheus/_lib/include/morpheus/utilities/string_util.hpp
  morpheus/_lib/include/morpheus/utilities/table_util.hpp
  morpheus/_lib/include/morpheus/utilities/tensor_util.hpp
  morpheus/_lib/include/morpheus/utilities/type_util.hpp
  morpheus/_lib/include/morpheus/utilities/type_util_detail.hpp
  morpheus/_lib/include/nvtext/subword_tokenize.hpp
Labels: non-breaking, doc, 3 - Ready for Review
