Repository nv-morpheus/Morpheus, pull requests merged in 2022-06, with the labels that each got.

#127 Update morpheus_quickstart_guide.md
  docs/source/morpheus_quickstart_guide.md
Labels: non-breaking, doc, 5 - Ready to Merge

#130 Split data dir, moving large files into examples/data
  .gitattributes
  ci/scripts/jenkins/build.sh
  docs/source/basics/examples.rst
  docs/source/developer_guide/guides/1_simple_python_stage.md
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/morpheus_quickstart_guide.md
  examples/abp_nvsmi_detection/README.md
  examples/abp_pcap_detection/README.md
  examples/data/abp_pcap_dump.jsonlines
  examples/data/email.jsonlines
  examples/data/email_with_addresses.jsonlines
  examples/data/nvsmi.jsonlines
  examples/data/pcap_dump.jsonlines
  examples/data/sid_training_data_truth.csv
  examples/data/with_data_len.json
  examples/data/without_data_len.json
  examples/nlp_si_detection/README.md
  morpheus.code-workspace
Labels: enhancement, non-breaking, doc, 4 - Waiting on Author

#145 Fixes Timestamp Nodes When Running with `--debug`
  docs/source/developer_guide/guides/3_simple_cpp_stage.md
  docs/source/developer_guide/guides/4_source_cpp_stage.md
  morpheus/pipeline/multi_message_stage.py
  morpheus/pipeline/stream_wrapper.py
  morpheus/stages/general/buffer_stage.py
  morpheus/stages/general/delay_stage.py
  morpheus/stages/general/monitor_stage.py
  morpheus/stages/general/trigger_stage.py
  morpheus/stages/inference/inference_stage.py
  morpheus/stages/input/appshield_source_stage.py
  morpheus/stages/input/cloud_trail_source_stage.py
  morpheus/stages/input/file_source_stage.py
  morpheus/stages/output/write_to_kafka_stage.py
  morpheus/stages/postprocess/add_classifications_stage.py
  morpheus/stages/postprocess/add_scores_stage.py
  morpheus/stages/postprocess/filter_detections_stage.py
  morpheus/stages/postprocess/generate_viz_frames_stage.py
  morpheus/stages/postprocess/ml_flow_drift_stage.py
  morpheus/stages/postprocess/serialize_stage.py
  morpheus/stages/postprocess/timeseries_stage.py
  morpheus/stages/postprocess/validation_stage.py
  morpheus/stages/preprocess/deserialize_stage.py
  morpheus/stages/preprocess/drop_null_stage.py
  morpheus/stages/preprocess/preprocess_base_stage.py
  morpheus/stages/preprocess/preprocess_fil_stage.py
  morpheus/stages/preprocess/preprocess_nlp_stage.py
  tests/benchmarks/static_message_source.py
  tests/utils.py
Labels: bug, breaking, 3 - Ready for Review

#139 Limit which lfs assets are pulled by default
  .lfsconfig
  CONTRIBUTING.md
  ci/scripts/jenkins/build.sh
  ci/scripts/jenkins/test.sh
  docker/conda/environments/cuda11.4_dev.yml
  models/mlflow/README.md
  scripts/fetch_data.py
  tests/test_hammah.py
Labels: non-breaking, feature request, 4 - Waiting on Reviewer

#107 Jenkins improvememts
  CMakeLists.txt
  ci/conda/recipes/morpheus/morpheus_build.sh
  ci/iwyu/mappings.imp
  ci/scripts/common.sh
  ci/scripts/fix_all.sh
  ci/scripts/gitutils.py
  ci/scripts/jenkins/build.sh
  ci/scripts/jenkins/checks.sh
  ci/scripts/jenkins/common.sh
  ci/scripts/jenkins/docs.sh
  ci/scripts/jenkins/test.sh
Labels: non-breaking, improvement, 4 - Waiting on Reviewer

#158 Fix for CI check script
  ci/Jenkinsfile
  ci/scripts/jenkins/common.sh
Labels: non-breaking, feature request, 5 - Ready to Merge

#148 update cudf to 22.04, cuda to 11.5
  CONTRIBUTING.md
  ci/Jenkinsfile
  ci/conda/recipes/cudf/001-external-table.patch
  ci/conda/recipes/cudf/build.sh
  ci/conda/recipes/cudf/conda_build_config.yaml
  ci/conda/recipes/cudf/meta.yaml
  ci/conda/recipes/libcudf/001-external-table.patch
  ci/conda/recipes/libcudf/build.sh
  ci/conda/recipes/libcudf/conda_build_config.yaml
  ci/conda/recipes/libcudf/meta.yaml
  ci/conda/recipes/morpheus/conda_build_config.yaml
  ci/conda/recipes/morpheus/meta.yaml
  ci/conda/recipes/run_conda_build.sh
  ci/scripts/jenkins/build.sh
  cmake/import-rapids-cmake.cmake
  docker/Dockerfile
  docker/build_container.sh
  docker/conda/environments/cuda11.5_ci.yml
  docker/conda/environments/cuda11.5_dev.yml
  docker/conda/environments/cuda11.5_runtime.yml
  examples/abp_pcap_detection/abp_pcap_preprocessing.py
  morpheus/_lib/cudf_helpers.pyx
  morpheus/_lib/include/nvtext/subword_tokenize.hpp
  morpheus/_lib/src/utilities/cudf_util.cpp
  morpheus/stages/preprocess/preprocess_fil_stage.py
  pyproject.toml
Labels: breaking, feature request, 3 - Ready for Review

#146 Update mlflow-env.yml
  models/mlflow/docker/conda/mlflow-env.yml
Labels: non-breaking, improvement, 3 - Ready for Review

#163 Adding in pybind11-stubgen to the conda package
  ci/conda/recipes/morpheus/meta.yaml
Labels: bug, non-breaking, 2 - In Progress

#135 Include C++ Unittests in CI
  ci/Jenkinsfile
  ci/scripts/jenkins/build.sh
  ci/scripts/jenkins/checks.sh
  ci/scripts/jenkins/common.sh
  ci/scripts/jenkins/docs.sh
  ci/scripts/jenkins/test.sh
  morpheus/_lib/tests/CMakeLists.txt
Labels: enhancement, non-breaking, feature request, 5 - Ready to Merge

#142 Update morpheus_quickstart_guide.md
  docs/source/morpheus_quickstart_guide.md
Labels: non-breaking, doc, 3 - Ready for Review

#179 Add missing git-lfs package to docker container
  docker/Dockerfile
Labels: non-breaking, improvement, 5 - Ready to Merge

#180 Update to rapids 22.06
  CMakeLists.txt
  CONTRIBUTING.md
  ci/Jenkinsfile
  ci/conda/recipes/morpheus/conda_build_config.yaml
  ci/conda/recipes/morpheus/meta.yaml
  cmake/deps/patches/TritonClient.patch
  cmake/import-rapids-cmake.cmake
  docker/Dockerfile
  docker/build_container.sh
  docker/conda/environments/cuda11.5_dev.yml
Labels: non-breaking, feature request

#191 Rollback CI images and fix dev container
  CMakeLists.txt
  ci/Jenkinsfile
Labels: bug, non-breaking, 5 - Ready to Merge

#189 Fix GNN example and update installation instructions
  examples/gnn_fraud_detection_pipeline/README.md
  examples/gnn_fraud_detection_pipeline/requirements.yml
  examples/gnn_fraud_detection_pipeline/stages/classification_stage.py
  examples/gnn_fraud_detection_pipeline/stages/graph_construction_stage.py
  examples/gnn_fraud_detection_pipeline/stages/graph_sage_stage.py
Labels: non-breaking, doc, 5 - Ready to Merge

#193 nlp_si_detection example improvements
  examples/nlp_si_detection/README.md
  morpheus/_lib/src/python_modules/messages.cpp
Labels: non-breaking, improvement, 4 - Waiting on Author

#182 Update GNN FSI pipeline example & notebook.
  examples/gnn_fraud_detection_pipeline/model/hinsage-model.pt/keras_metadata.pb
  examples/gnn_fraud_detection_pipeline/model/hinsage-model.pt/saved_model.pb
  examples/gnn_fraud_detection_pipeline/model/hinsage-model.pt/variables/variables.data-00000-of-00001
  examples/gnn_fraud_detection_pipeline/model/hinsage-model.pt/variables/variables.index
  examples/gnn_fraud_detection_pipeline/model/xgb-model.pt
  models/training-tuning-scripts/fraud-detection-models/HinSAGE.py
  models/training-tuning-scripts/fraud-detection-models/evaluation.py
  models/training-tuning-scripts/fraud-detection-models/graph-sage-fraud-detection.ipynb
  models/training-tuning-scripts/fraud-detection-models/training.py
Labels: non-breaking, improvement, 3 - Ready for Review

#224 Use git version 2.35.3 in release build
  docker/Dockerfile
Labels: bug, non-breaking

#196 ransomware ds requirements
  models/README.md
  models/datasets/training-data/ransomware-training-data.csv
  models/model-information.csv
  models/ransomware-models/ransomw-model-short-rf-20220126.sav
  models/training-tuning-scripts/ransomware-models/ransomware-appshield-training.ipynb
Labels: non-breaking, feature request, 4 - Waiting on Reviewer

#147 Documentation fixes
  CONTRIBUTING.md
  README.md
  docs/source/basics/overview.rst
  docs/source/developer_guide/guides/1_simple_python_stage.md
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/developer_guide/guides/3_simple_cpp_stage.md
  docs/source/developer_guide/guides/4_source_cpp_stage.md
  docs/source/extra_info/troubleshooting.md
  docs/source/index.rst
  docs/source/morpheus_quickstart_guide.md
  examples/abp_nvsmi_detection/README.md
  examples/abp_nvsmi_detection/pipeline.png
  examples/abp_pcap_detection/README.md
  examples/abp_pcap_detection/abp_pcap_preprocessing.py
  examples/abp_pcap_detection/img/abp_pcap_detection.png
  examples/log_parsing/README.md
  examples/nlp_si_detection/README.md
  examples/nlp_si_detection/pipeline.png
  morpheus.code-workspace
  scripts/validation/val-run-pipeline.sh
Labels: non-breaking, doc, 3 - Ready for Review

#203 Fixes Pipeline.visualize
  morpheus/cli.py
  morpheus/pipeline/pipeline.py
  tests/test_pipe_viz.py
Labels: non-breaking, improvement, 5 - Ready to Merge

#234 Revert ransomware feature config changes
  examples/ransomware_detection/common/data_models.py
  examples/ransomware_detection/common/feature_extractor.py
  examples/ransomware_detection/stages/create_features.py
Labels: bug, non-breaking, 5 - Ready to Merge

#232 Add CLI Relative Path Fallback
  morpheus/cli.py
  tests/test_cli.py
Labels: non-breaking, feature request

#239 Missing 'supports_cpp_node' impl function
  examples/log_parsing/postprocessing.py
  examples/log_parsing/preprocessing.py
Labels: bug, non-breaking, 3 - Ready for Review, 4 - Waiting on Reviewer

#246 Pin cuda-python to 11.7.0
  docker/conda/environments/cuda11.5_dev.yml
Labels: non-breaking, improvement, 3 - Ready for Review

#242 Move Morpheus Data Files Out of LFS
  .gitattributes
  .lfsconfig
  ci/conda/recipes/morpheus/meta.yaml
  ci/scripts/jenkins/test.sh
  docker/Dockerfile
  docker/conda/environments/cuda11.5_ci.yml
  docker/conda/environments/cuda11.5_dev.yml
  docker/run_container_dev.sh
  docker/run_container_release.sh
  morpheus/data/bert-base-cased-hash.txt
  morpheus/data/bert-base-uncased-hash.txt
  morpheus/data/columns_ae.txt
  morpheus/data/columns_fil.txt
  morpheus/data/labels_ae.txt
  morpheus/data/labels_nlp.txt
  morpheus/data/labels_phishing.txt
  scripts/fetch_data.py
Labels: bug, non-breaking, 2 - In Progress

#252 Pin Conda Package `cuda-python <=11.7.0` to Fix Conda Build
  ci/conda/recipes/morpheus/meta.yaml
  docker/conda/environments/cuda11.5_dev.yml
Labels: bug, non-breaking

#249 Fix 22.06 style checks
  ci/scripts/gitutils.py
  docs/source/conf.py
  models/mlflow/docker/Dockerfile
  models/mlflow/docker/entrypoint.sh
  models/training-tuning-scripts/fraud-detection-models/HinSAGE.py
  models/training-tuning-scripts/hammah-models/hammah-20211017-script.py
  models/training-tuning-scripts/phishing-models/binary_sequence_classifier.py
  models/training-tuning-scripts/phishing-models/phish-bert-20211006-script.py
  models/training-tuning-scripts/phishing-models/sequence_classifier.py
  models/validation-inference-scripts/abp-models/abp-inference.py
  models/validation-inference-scripts/fraud-detection-models/inference.py
  models/validation-inference-scripts/hammah-models/hammah-inference.py
  models/validation-inference-scripts/hammah-models/requirements.txt
  models/validation-inference-scripts/log-parsing-models/log-parsing-inference.py
  models/validation-inference-scripts/phishing-models/phish-bert-20220113-inference-script.py
  morpheus/_lib/include/morpheus/objects/triton_in_out.hpp
  morpheus/_lib/include/nvtext/subword_tokenize.hpp
  tests/mock_triton_server/config.yml
Labels: non-breaking, feature request
