Repository nv-morpheus/Morpheus, pull requests merged in 2023-11, with the labels that each got.

#1325 Removed Mutex Related Milvus Tests
  morpheus/service/milvus_vector_db_service.py
  tests/test_milvus_vector_db_service.py
Labels: bug, non-breaking

#1333 Add docstrings and tests for RagNode
  examples/llm/rag/README.md
  morpheus/llm/nodes/rag_node.py
  tests/_utils/llm.py
  tests/llm/nodes/test_rag_node.py
  tests/llm/nodes/test_rag_node_pipe.py
Labels: non-breaking, improvement, sherlock

#1334 Remove overload of 'add_node' handling null inputs in lambda
  morpheus/_lib/llm/__init__.pyi
  morpheus/_lib/llm/module.cpp
Labels: bug, non-breaking, sherlock

#1335 re-work OpenAIChatNode as an LLMService/LLMClient
  docker/conda/environments/cuda11.8_dev.yml
  docker/conda/environments/cuda11.8_examples.yml
  examples/llm/agents/simple_pipeline.py
  examples/llm/completion/pipeline.py
  examples/llm/completion/run.py
  morpheus/llm/nodes/llm_generate_node.py
  morpheus/llm/nodes/openai_chat_node.py
  morpheus/llm/services/llm_service.py
  morpheus/llm/services/nemo_llm_service.py
  morpheus/llm/services/openai_chat_service.py
  tests/llm/nodes/conftest.py
  tests/llm/nodes/test_llm_generate_node.py
  tests/llm/services/conftest.py
  tests/llm/services/nemo_llm/conftest.py
  tests/llm/services/nemo_llm/test_nemo_llm_client.py
  tests/llm/services/nemo_llm/test_nemo_llm_service_pipe.py
  tests/llm/services/test_llm_service_pipe.py
  tests/llm/services/test_nemo_llm_client.py
  tests/llm/services/test_nemo_llm_service.py
  tests/llm/services/test_openai_chat_client.py
  tests/llm/services/test_openai_chat_service.py
Labels: non-breaking, improvement, sherlock

#1337 Docstrings and tests for ExtracterNode
  morpheus/llm/nodes/extracter_node.py
  tests/_utils/llm.py
  tests/io/test_data_record.py
  tests/llm/nodes/test_extractor_node.py
  tests/llm/test_extractor_simple_task_handler_pipe.py
Labels: non-breaking, improvement, sherlock

#1338 use asyncio runnable from mrc
  morpheus/_lib/llm/include/py_llm_engine_stage.hpp
Labels: non-breaking, improvement

#1332 Completion README.md
  docs/source/examples/llm/completion/README.md
  examples/llm/completion/README.md
  examples/llm/completion/pipeline.py
Labels: non-breaking, doc, sherlock

#1340 RetrieverNode Tests and Docs
  morpheus/llm/nodes/retriever_node.py
  tests/llm/nodes/test_llm_retriever_node.py
  tests/llm/nodes/test_llm_retriever_node_pipe.py
Labels: non-breaking, improvement

#1347 DFP container updates
  examples/digital_fingerprinting/production/Dockerfile
  examples/digital_fingerprinting/production/conda_env.yml
Labels: bug, non-breaking

#1348 Updated Milvus Tests and Exposed `release_resource` API
  docker/conda/environments/cuda11.8_dev.yml
  morpheus/service/vdb/milvus_vector_db_service.py
  morpheus/service/vdb/vector_db_service.py
  tests/test_milvus_vector_db_service.py
Labels: bug, non-breaking, sherlock

#1349 Add docs and tests for WebScraperStage
  examples/llm/common/web_scraper_stage.py
  tests/examples/llm/common/conftest.py
  tests/examples/llm/common/test_web_scraper_stage.py
  tests/mock_rest_server/mocks/www/index/GET.mock
Labels: non-breaking, improvement

#1316 `LLMContext` C++ unit tests and docs
  morpheus/_lib/include/morpheus/llm/llm_context.hpp
  morpheus/_lib/tests/CMakeLists.txt
  morpheus/_lib/tests/llm/test_llm_context.cpp
Labels: non-breaking, improvement

#1330 Docs for LLM C++ classes
  morpheus/_lib/include/morpheus/llm/input_map.hpp
  morpheus/_lib/include/morpheus/llm/llm_context.hpp
  morpheus/_lib/include/morpheus/llm/llm_engine.hpp
  morpheus/_lib/include/morpheus/llm/llm_lambda_node.hpp
  morpheus/_lib/include/morpheus/llm/llm_node.hpp
  morpheus/_lib/include/morpheus/llm/llm_node_base.hpp
  morpheus/_lib/include/morpheus/llm/llm_node_runner.hpp
  morpheus/_lib/include/morpheus/llm/llm_task.hpp
  morpheus/_lib/include/morpheus/llm/llm_task_handler.hpp
  morpheus/_lib/include/morpheus/llm/llm_task_handler_runner.hpp
  morpheus/_lib/include/morpheus/llm/utils.hpp
Labels: non-breaking, doc

#1350 C++ unit tests for LLMNodeRunner, LLMTaskHandlerRunner and LLMTask
  morpheus/_lib/src/llm/llm_node_runner.cpp
  morpheus/_lib/tests/CMakeLists.txt
  morpheus/_lib/tests/llm/test_llm_node_runner.cpp
  morpheus/_lib/tests/llm/test_llm_task.cpp
  morpheus/_lib/tests/llm/test_llm_task_handler_runner.cpp
Labels: non-breaking, improvement, sherlock

#1352 Update LLM Agents Pipeline README.md
  docs/source/examples/llm/agents/README.md
  examples/llm/agents/README.md
Labels: non-breaking, doc, sherlock

#1358 Add `cache_path` arg to `WebScraperStage`
  examples/llm/common/web_scraper_stage.py
  examples/llm/vdb_upload/pipeline.py
Labels: non-breaking, feature request

#1343 Commit models to LFS
  models/fraud-detection-models/graph.pkl
  models/fraud-detection-models/hyperparams.pkl
  models/fraud-detection-models/model.pt
  models/fraud-detection-models/xgb.pt
Labels: non-breaking, improvement

#1360 End to end test for vdb upload example
  examples/llm/vdb_upload/pipeline.py
  tests/llm/test_vdb_upload_pipe.py
  tests/tests_data/service/cisa_rss_feed.xml
  tests/tests_data/service/cisa_web_responses.json
  tests/tests_data/service/milvus_rss_data.json
Labels: non-breaking, improvement, sherlock

#1368 Add missing milvus mark for two tests which require milvus
  tests/llm/test_rag_standalone_pipe.py
Labels: bug, non-breaking, sherlock

#1365 Merge branch-23.11 into fea-sherlock to resolve conflicts -- prep for merge back into 23.11
  examples/digital_fingerprinting/production/Dockerfile
  examples/digital_fingerprinting/production/conda_env.yml
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_file_batcher_stage.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_inference_stage.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_rolling_window_stage.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_training.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/multi_file_source.py
  examples/digital_fingerprinting/production/morpheus/dfp/utils/regex_utils.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_duo_pipeline.py
  morpheus/utils/file_utils.py
  tests/examples/digital_fingerprinting/test_dfp_file_batcher_stage.py
  tests/tests_data/service/milvus_rss_data.json
Labels: non-breaking, improvement

#1371 Draft: fix for test_simple_request
  tests/common/test_http_server.py
Labels: bug, non-breaking

#1376 Caching Flag Accessible as a Parameter
  examples/llm/common/web_scraper_stage.py
  examples/llm/vdb_upload/pipeline.py
Labels: non-breaking, improvement, sherlock

#1381 Fix test_vdb_upload_pipe
  tests/llm/test_vdb_upload_pipe.py
  tests/tests_data/service/milvus_rss_data.json
Labels: bug, non-breaking, sherlock

#1357 Documentation patch for Examples
  docs/source/examples.md
Labels: non-breaking, doc

#1362 Stage documentation improvements
  docs/source/examples/doca/README.md
  docs/source/examples/index.rst
  docs/source/getting_started.md
  docs/source/stages/morpheus_stages.md
  morpheus/stages/input/rss_source_stage.py
  morpheus/stages/postprocess/ml_flow_drift_stage.py
Labels: non-breaking, doc

#1384 Register DataBricksDeltaLakeSourceStage with the CLI
  morpheus/cli/commands.py
Labels: bug, non-breaking

#1385 Add missing milvus marker
  tests/test_milvus_vector_db_service.py
Labels: bug, non-breaking

#1379 LLM C++ test and doc updates
  morpheus/_lib/include/morpheus/llm/llm_context.hpp
  morpheus/_lib/include/morpheus/llm/llm_engine.hpp
  morpheus/_lib/include/morpheus/llm/llm_task.hpp
  morpheus/_lib/include/morpheus/llm/utils.hpp
  morpheus/_lib/tests/llm/test_llm_context.cpp
  morpheus/_lib/tests/llm/test_utils.cpp
Labels: non-breaking, improvement, sherlock

#1388 Align model card requirements
  models/model-cards/abp-model-card.md
  models/model-cards/dfp-model-card.md
  models/model-cards/gnn-fsi-model-card.md
  models/model-cards/phishing-model-card.md
  models/model-cards/root-cause-analysis-model-card.md
Labels: non-breaking, doc

#1387 Docs update to indicate use of conda-merge to generate install files
  ci/conda/recipes/morpheus/meta.yaml
  docker/conda/environments/cuda11.8_dev.yml
  docker/conda/environments/cuda11.8_examples.yml
  docker/conda/environments/cuda11.8_runtime.yml
  docs/README.md
  examples/digital_fingerprinting/production/Dockerfile
  examples/digital_fingerprinting/production/morpheus/benchmarks/README.md
  examples/gnn_fraud_detection_pipeline/README.md
  examples/gnn_fraud_detection_pipeline/requirements.yml
  examples/llm/agents/README.md
  examples/llm/agents/requirements.yaml
  examples/llm/completion/README.md
  examples/llm/completion/requirements.yaml
  examples/llm/rag/requirements.yaml
  examples/llm/vdb_upload/requirements.yaml
  models/training-tuning-scripts/abp-models/requirements.yml
  models/training-tuning-scripts/dfp-models/requirements.yml
  models/training-tuning-scripts/fraud-detection-models/README.md
  models/training-tuning-scripts/fraud-detection-models/gnn-fraud-detection-training.ipynb
  models/training-tuning-scripts/fraud-detection-models/requirements.yml
  models/training-tuning-scripts/log-parsing-models/requirements.yml
  models/training-tuning-scripts/phishing-models/requirements.yml
  models/training-tuning-scripts/ransomware-models/requirements.yml
  models/training-tuning-scripts/root-cause-models/requirements.yml
  models/training-tuning-scripts/sid-models/requirements.yml
  models/validation-inference-scripts/fraud-detection-models/requirements.yml
  morpheus/llm/nodes/extracter_node.py
  morpheus/llm/services/nemo_llm_service.py
  morpheus/llm/services/openai_chat_service.py
  morpheus/stages/input/arxiv_source.py
  tests/benchmarks/README.md
  tests/examples/llm/common/conftest.py
  tests/llm/conftest.py
  tests/stages/arxiv/conftest.py
Labels: non-breaking, doc

#1364 Add source & stage decorators
  docs/source/developer_guide/guides/1_simple_python_stage.md
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/developer_guide/guides/3_simple_cpp_stage.md
  examples/developer_guide/1_simple_python_stage/pass_thru.py
  examples/developer_guide/1_simple_python_stage/pass_thru_deco.py
  examples/developer_guide/1_simple_python_stage/run.py
  examples/developer_guide/2_1_real_world_phishing/recipient_features_stage_deco.py
  examples/developer_guide/2_1_real_world_phishing/run.py
  examples/developer_guide/2_2_rabbitmq/README.md
  examples/developer_guide/2_2_rabbitmq/rabbitmq_source_stage.py
  examples/developer_guide/2_2_rabbitmq/rabbitmq_source_stage_deco.py
  examples/developer_guide/2_2_rabbitmq/read_simple.py
  morpheus/pipeline/stage_base.py
  morpheus/pipeline/stage_decorator.py
  tests/examples/developer_guide/test_pass_thru.py
  tests/examples/developer_guide/test_recipient_features_stage.py
  tests/pipeline/test_stage_decorator.py
Labels: non-breaking, feature request

#1390 Fix race condition in the C++ impl for the pre-process fil stage
  examples/abp_nvsmi_detection/README.md
  morpheus/_lib/src/stages/preprocess_fil.cpp
Labels: bug, non-breaking

#1392 Fix the SID Viz workflow shutdown process with the new pipeline shutdown process
  morpheus/pipeline/pipeline.py
  morpheus/stages/postprocess/generate_viz_frames_stage.py
Labels: bug, non-breaking
