Repository nv-morpheus/Morpheus, pull requests merged in 2023-10, with the labels that each got.

#1242 Add libwebp to meta.yaml for CVE 2307
  ci/conda/recipes/morpheus/meta.yaml
  tests/test_kafka_source_stage_pipe.py
Labels: bug, non-breaking

#630 Adds support to read and write to Databricks delta tables
  docker/Dockerfile
  docker/conda/environments/cuda11.8_dev.yml
  docs/source/conf.py
  morpheus/stages/input/databricks_deltalake_source_stage.py
  morpheus/stages/output/write_to_databricks_deltalake_stage.py
  tests/test_databricks_deltalake_source_stage.py
  tests/test_write_to_databricks_deltalake_stage.py
Labels: non-breaking, feature request

#1243 [BUG] Fix Control Message Utils & SQL Max Connections Exhaust
  morpheus/loaders/sql_loader.py
  morpheus/utils/control_message_utils.py
Labels: bug, non-breaking, ! - Hotfix

#1246 Forward-merge branch-23.07 to branch-23.11 [resolved conflicts]
  ci/conda/recipes/morpheus/meta.yaml
  ci/scripts/github/common.sh
  docker/conda/environments/cuda11.8_dev.yml
  docker/conda/environments/cuda11.8_examples.yml
  models/mlflow/docker/conda/mlflow-env.yml
  morpheus/loaders/sql_loader.py
  morpheus/utils/control_message_utils.py
Labels: bug, dependencies, non-breaking, ! - Hotfix

#1245 [DRAFT] Add model and experiment template 'click' options to dfp example pipelines, and make model names Databricks compatible.
  examples/digital_fingerprinting/production/morpheus/dfp/utils/dfp_arg_parser.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_duo_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_integrated_training_batch_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_integrated_training_streaming_pipeline.py
  morpheus/controllers/mlflow_model_writer_controller.py
Labels: enhancement, non-breaking, improvement

#1186 Update to clang-16 & boost-1.82
  ci/conda/recipes/morpheus/conda_build_config.yaml
  ci/scripts/common.sh
  docker/conda/environments/cuda11.8_dev.yml
  examples/developer_guide/4_rabbitmq_cpp_stage/cmake/Configure_SimpleAmqpClient.cmake
Labels: dependencies, non-breaking, improvement

#1257 [RELEASE] Morpheus v23.07.03 Hotfix
  CHANGELOG.md
  CMakeLists.txt
  ci/conda/recipes/morpheus/meta.yaml
  ci/scripts/github/common.sh
  docker/conda/environments/cuda11.8_dev.yml
  docker/conda/environments/cuda11.8_examples.yml
  examples/digital_fingerprinting/production/Dockerfile
  examples/digital_fingerprinting/production/docker-compose.yml
  models/mlflow/docker/conda/mlflow-env.yml
  morpheus/_lib/modules/module.cpp
  morpheus/loaders/sql_loader.py
  morpheus/utils/control_message_utils.py
  tests/test_kafka_source_stage_pipe.py
Labels: ! - Hotfix, ! - Release

#1262 Loosen nodejs version restriction
  docker/conda/environments/cuda11.8_dev.yml
Labels: dependencies, non-breaking, improvement

#1263 Resolve merge conflicts between 23.07 and 23.11
  CHANGELOG.md
  morpheus/_lib/modules/module.cpp
Labels: non-breaking

#1264 Fix documentation for morpheus.loaders.sql_loader
  morpheus/utils/control_message_utils.py
Labels: non-breaking, doc

#1225 Add a Vector Database Service to allow stages to read and write to VDBs
  docker/conda/environments/cuda11.8_dev.yml
  docs/source/conf.py
  morpheus/service/__init__.py
  morpheus/service/milvus_client.py
  morpheus/service/milvus_vector_db_service.py
  morpheus/service/vector_db_service.py
  morpheus/stages/output/write_to_vector_db.py
  morpheus/utils/vector_db_service_utils.py
  tests/conftest.py
  tests/test_milvus_vector_db_service.py
  tests/test_milvus_write_to_vector_db_stage_pipe.py
  tests/tests_data/service/milvus_idx_part_collection_conf.json
  tests/tests_data/service/milvus_simple_collection_conf.json
Labels: non-breaking, feature request, sherlock

#1266 Minor additions to llm tests
  morpheus/_lib/tests/llm/test_llm_node.cpp
  morpheus/_lib/tests/llm/test_utils.cpp
Labels: non-breaking, improvement, sherlock

#1269 Add unit tests for LLMUtils
  morpheus/_lib/src/llm/utils.cpp
  morpheus/_lib/tests/llm/test_utils.cpp
Labels: non-breaking, improvement, sherlock

#1273 Fix/update several existing tests
  docker/conda/environments/cuda11.8_dev.yml
  morpheus/cli/register_stage.py
  morpheus/cli/utils.py
  morpheus/controllers/rss_controller.py
  morpheus/stages/input/rss_source_stage.py
  morpheus/stages/preprocess/deserialize_stage.py
  morpheus/utils/type_utils.py
  tests/controllers/test_rss_controller.py
  tests/test_deserialize_stage_pipe.py
  tests/test_rss_source_stage_pipe.py
  tests/tests_data/service/milvus_simple_collection_conf.json
Labels: bug, non-breaking, sherlock

#1284 Skip milvus tests by default
  ci/scripts/github/test.sh
  pyproject.toml
  tests/_utils/__init__.py
  tests/conftest.py
  tests/test_milvus_vector_db_service.py
  tests/test_milvus_write_to_vector_db_stage_pipe.py
Labels: non-breaking, improvement, sherlock

#1289 Misc updates & fixes for the vdb_upload pipeline
  docker/conda/environments/cuda11.8_dev.yml
  docker/conda/environments/cuda11.8_examples.yml
  examples/llm/vdb_upload/README.md
  examples/llm/vdb_upload/run.py
  morpheus/stages/input/rss_source_stage.py
Labels: bug, non-breaking

#1285 RSS Controller Improvements
  morpheus/controllers/rss_controller.py
  morpheus/stages/input/rss_source_stage.py
  tests/controllers/test_rss_controller.py
  tests/test_rss_source_stage_pipe.py
Labels: non-breaking, improvement, sherlock

#1290 Make dfp_azure_pipeline inference output file configurable.
  examples/digital_fingerprinting/production/morpheus/dfp_azure_pipeline.py
Labels: non-breaking, improvement

#1295 Create LICENSE.psycopg2
  thirdparty/LICENSES/LICENSE.psycopg2
Labels: non-breaking, doc

#1296 Add tests & docstrings for PromptTemplateNode
  morpheus/_lib/llm/__init__.pyi
  morpheus/_lib/llm/module.cpp
  morpheus/_lib/src/llm/llm_context.cpp
  morpheus/cli/commands.py
  morpheus/llm/llm_engine_stage.py
  morpheus/llm/nodes/prompt_template_node.py
  morpheus/stages/input/arxiv_source.py
  tests/_utils/llm.py
  tests/llm/nodes/test_prompt_template_node.py
Labels: non-breaking, improvement, sherlock

#1308 Add integration test for PromptTemplateNode in a morpheus pipeline
  morpheus/_lib/src/llm/llm_context.cpp
  morpheus/llm/nodes/prompt_template_node.py
  morpheus/utils/concat_df.py
  tests/llm/nodes/test_prompt_template_node_pipe.py
Labels: non-breaking, improvement, sherlock

#1309 vdb_upload pipeline updates.
  docs/source/examples.md
  docs/source/examples/llm/README.md
  docs/source/examples/llm/agents/README.md
  docs/source/examples/llm/completion/README.md
  docs/source/examples/llm/rag/README.md
  docs/source/examples/llm/vdb_upload/README.md
  examples/llm/vdb_upload/README.md
  examples/llm/vdb_upload/requirements.yaml
Labels: non-breaking, doc

#1310 Tests, docstrings & cleanups for ArxivSource
  morpheus/stages/input/arxiv_source.py
  tests/stages/arxiv/conftest.py
  tests/stages/arxiv/test_arxiv_source.py
  tests/stages/arxiv/test_arxiv_source_pipe.py
  tests/tests_data/test.pdf
Labels: non-breaking, improvement

#1313 Remove pycoro in favor of mrc::pymrc::coro
  morpheus/_lib/CMakeLists.txt
  morpheus/_lib/__init__.py
  morpheus/_lib/llm/CMakeLists.txt
  morpheus/_lib/llm/__init__.pyi
  morpheus/_lib/llm/include/py_llm_engine_stage.hpp
  morpheus/_lib/llm/module.cpp
  morpheus/_lib/llm/src/py_llm_lambda_node.cpp
  morpheus/_lib/llm/src/py_llm_node_base.cpp
  morpheus/_lib/llm/src/py_llm_task_handler.cpp
  morpheus/_lib/pycoro/CMakeLists.txt
  morpheus/_lib/pycoro/__init__.pyi
  morpheus/_lib/pycoro/include/pycoro/pycoro.hpp
  morpheus/_lib/pycoro/module.cpp
  morpheus/_lib/pycoro/src/pycoro.cpp
  tests/llm/test_pycoro.py
Labels: non-breaking, improvement

#1318 Docstrings for LLMService & LLMClient
  docker/conda/environments/cuda11.8_dev.yml
  morpheus/llm/services/llm_service.py
  tests/llm/services/test_llm_service.py
Labels: non-breaking, improvement, sherlock

#1320 Pin cuda-python to 11.8.2 as a work around for 11.8.3 incompatibility.
  docker/conda/environments/cuda11.8_dev.yml
Labels: bug, non-breaking

#1311 Rag pipeline updates + misc docs fixes and improvments
  examples/digital_fingerprinting/production/morpheus/dfp/stages/multi_file_source.py
  examples/llm/common/utils.py
  examples/llm/completion/README.md
  examples/llm/rag/README.md
  examples/llm/rag/images/persistent_pipeline.png
  examples/llm/rag/persistant_pipeline.py
  examples/llm/rag/run.py
  examples/llm/rag/standalone_pipeline.py
  examples/llm/vdb_upload/README.md
  examples/llm/vdb_upload/pipeline.py
Labels: non-breaking, doc

#1324 Docstrings & Tests for SimpleTaskHandler
  morpheus/_lib/llm/__init__.pyi
  morpheus/_lib/llm/module.cpp
  morpheus/llm/task_handlers/simple_task_handler.py
  tests/_utils/llm.py
  tests/llm/task_handlers/test_simple_task_handler.py
  tests/llm/task_handlers/test_simple_task_handler_pipe.py
Labels: non-breaking, improvement, sherlock

#1327 Docstrings and tests for LangChainAgentNode
  morpheus/llm/nodes/langchain_agent_node.py
  tests/llm/nodes/conftest.py
  tests/llm/nodes/test_langchain_agent_node.py
  tests/llm/nodes/test_langchain_agent_node_pipe.py
Labels: non-breaking, improvement, sherlock
