Repository nv-morpheus/Morpheus, pull requests merged in 2023-05, with the labels that each got.

#911 Documentation review edits
  docs/README.md
  docs/source/basics/building_a_pipeline.md
  docs/source/cloud_deployment_guide.md
  docs/source/developer_guide/contributing.md
  docs/source/developer_guide/guides.md
  docs/source/developer_guide/guides/10_modular_pipeline_digital_fingerprinting.md
  docs/source/developer_guide/guides/1_simple_python_stage.md
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/developer_guide/guides/3_simple_cpp_stage.md
  docs/source/developer_guide/guides/4_source_cpp_stage.md
  docs/source/developer_guide/guides/5_digital_fingerprinting.md
  docs/source/developer_guide/guides/6_digital_fingerprinting_reference.md
  docs/source/developer_guide/guides/7_python_modules.md
  docs/source/developer_guide/guides/8_cpp_modules.md
  docs/source/developer_guide/guides/9_control_messages.md
  docs/source/extra_info/troubleshooting.md
  docs/source/getting_started.md
  docs/source/models_and_datasets.md
  docs/source/modules/examples/digital_fingerprinting/dfp_postprocessing.md
  docs/source/stages/morpheus_stages.md
  examples/README.md
  examples/abp_nvsmi_detection/README.md
  examples/abp_pcap_detection/README.md
  examples/developer_guide/2_2_rabbitmq/README.md
  examples/developer_guide/4_rabbitmq_cpp_stage/README.md
  examples/digital_fingerprinting/demo/README.md
  examples/digital_fingerprinting/demo/submit_messages.md
  examples/digital_fingerprinting/production/README.md
  examples/digital_fingerprinting/production/morpheus/benchmarks/README.md
  examples/digital_fingerprinting/starter/README.md
  examples/digital_fingerprinting/visualization/README.md
  examples/gnn_fraud_detection_pipeline/README.md
  examples/log_parsing/README.md
  examples/nlp_si_detection/README.md
  examples/ransomware_detection/README.md
  examples/root_cause_analysis/README.md
  examples/sid_visualization/README.md
  models/datasets/README.md
  models/mlflow/README.md
  models/triton-model-repo/README.md
Labels: non-breaking, doc, 3 - Ready for Review

#923 Enforce dtype for ColumnInfo and RenameColumn
  morpheus/utils/column_info.py
  tests/test_column_info.py
Labels: bug, non-breaking, 5 - Ready to Merge

#926 Auto-Comment on External Issues
  .github/workflows/label-external-issues.yml
Labels: non-breaking, improvement, 5 - Ready to Merge

#903 Add PyTorch to ONNX section to training notebooks
  models/phishing-models/phishing-bert-20221115.onnx
  models/phishing-models/phishing-bert-20221115.pt
  models/phishing-models/phishing-bert-20230421.onnx
  models/phishing-models/phishing-bert-20230421.pt
  models/sid-models/sid-minibert-20211021.onnx
  models/sid-models/sid-minibert-20211021.pth
  models/sid-models/sid-minibert-20230424.onnx
  models/sid-models/sid-minibert-20230424.pt
  models/training-tuning-scripts/log-parsing-models/log-parsing-training.ipynb
  models/training-tuning-scripts/phishing-models/phish-bert-training.ipynb
  models/training-tuning-scripts/root-cause-models/root-cause-bert.ipynb
  models/training-tuning-scripts/sid-models/sid-minibert-20230424-script.py
  models/training-tuning-scripts/sid-models/sid-minibert-20230424.ipynb
  models/triton-model-repo/phishing-bert-onnx/1/model.onnx
  models/triton-model-repo/sid-minibert-onnx/1/model.onnx
Labels: non-breaking, doc, 5 - Ready to Merge, Data Science

#930 remove unnecessary quotes from CMAKE_ARGS expression
  scripts/compile.sh
Labels: bug, non-breaking

#935 Fix race condition in CompareDataFrameStage
  morpheus/stages/output/compare_dataframe_stage.py
Labels: bug, non-breaking, 5 - Ready to Merge

#894 Migrate CLX parsers
  morpheus/data/public_suffix_list.dat
  morpheus/data/splunk_notable_regex.yaml
  morpheus/data/windows_event_regex.yaml
  morpheus/parsers/__init__.py
  morpheus/parsers/event_parser.py
  morpheus/parsers/ip.py
  morpheus/parsers/splunk_notable_parser.py
  morpheus/parsers/url_parser.py
  morpheus/parsers/windows_event_parser.py
  morpheus/parsers/zeek.py
  tests/test_ip.py
  tests/test_splunk_notable_parser.py
  tests/test_url_parser.py
  tests/test_windows_event_parser.py
  tests/test_zeek.py
  tests/tests_data/windows_event_logs.txt
Labels: non-breaking, feature request

#908 Fix early stopping code in dfencoder to use average loss of batches in validation set
  morpheus/models/dfencoder/autoencoder.py
  tests/dfencoder/test_autoencoder.py
Labels: bug, non-breaking, 3 - Ready for Review

#912 Improve DFP period functionality to allow for better sampling and ignoring period
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_file_batcher_stage.py
  examples/digital_fingerprinting/production/morpheus/dfp_duo_pipeline.py
Labels: non-breaking, improvement, 3 - Ready for Review

#946 Add COLLABORATOR to exclusion in label-external-issues.yml
  .github/workflows/label-external-issues.yml
Labels: non-breaking, improvement

#942 Add support for fsspec.core.OpenFile instances to the MonitorStage
  morpheus/utils/monitor_utils.py
  tests/test_error_pipe.py
  tests/test_monitor_stage.py
  tests/utils/stages/error_raiser.py
Labels: bug, non-breaking, 5 - Ready to Merge

#949 Helper scripts for running CI locally
  ci/scripts/bootstrap_local_ci.sh
  ci/scripts/github/build.sh
  ci/scripts/github/checks.sh
  ci/scripts/github/common.sh
  ci/scripts/github/docs.sh
  ci/scripts/github/test.sh
  ci/scripts/run_ci_local.sh
Labels: non-breaking, improvement, 5 - Ready to Merge

#940 Tests for stages in DFP Production Example
  docker/conda/environments/cuda11.8_examples.yml
  docs/source/developer_guide/guides/6_digital_fingerprinting_reference.md
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_file_batcher_stage.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_file_to_df.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_inference_stage.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_mlflow_model_writer.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_postprocessing_stage.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_rolling_window_stage.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_split_users_stage.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_training.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_viz_postproc.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/multi_file_source.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_modules_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_modules_pipeline.py
  morpheus/io/deserializers.py
  morpheus/io/serializers.py
  morpheus/io/utils.py
  morpheus/loaders/file_to_df_loader.py
  morpheus/modules/file_to_df.py
  morpheus/pipeline/preallocator_mixin.py
  morpheus/stages/output/compare_dataframe_stage.py
  morpheus/stages/output/write_to_file_stage.py
  morpheus/utils/downloader.py
  morpheus/utils/module_utils.py
  morpheus/utils/type_aliases.py
  setup.cfg
  tests/examples/digital_fingerprinting/conftest.py
  tests/examples/digital_fingerprinting/test_dfp_file_batcher_stage.py
  tests/examples/digital_fingerprinting/test_dfp_file_to_df.py
  tests/examples/digital_fingerprinting/test_dfp_inference_stage.py
  tests/examples/digital_fingerprinting/test_dfp_mlflow_model_writer.py
  tests/examples/digital_fingerprinting/test_dfp_postprocessing_stage.py
  tests/examples/digital_fingerprinting/test_dfp_preprocessing_stage.py
  tests/examples/digital_fingerprinting/test_dfp_rolling_window_stage.py
  tests/examples/digital_fingerprinting/test_dfp_split_users_stage.py
  tests/examples/digital_fingerprinting/test_dfp_training.py
  tests/examples/digital_fingerprinting/test_dfp_viz_postproc.py
  tests/examples/digital_fingerprinting/test_multifile_source.py
  tests/examples/digital_fingerprinting/test_write_to_s3_stage.py
  tests/examples/ransomware_detection/conftest.py
  tests/test_downloader.py
  tests/test_preallocation_pipe.py
  tests/tests_data/examples/developer_guide/email_with_addresses_first_10.jsonlines
  tests/utils/__init__.py
Labels: non-breaking, improvement, 3 - Ready for Review

#944 Multiple Input Kafka Topics Support
  docs/source/getting_started.md
  examples/digital_fingerprinting/production/morpheus/dfp_integrated_training_batch_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_integrated_training_streaming_pipeline.py
  morpheus/_lib/include/morpheus/stages/kafka_source.hpp
  morpheus/_lib/src/stages/kafka_source.cpp
  morpheus/_lib/stages/module.cpp
  morpheus/stages/input/control_message_kafka_source_stage.py
  morpheus/stages/input/kafka_source_stage.py
  morpheus/stages/output/compare_dataframe_stage.py
  tests/io/test_loader_registry.py
  tests/test_cli.py
  tests/test_kafka_source_stage_pipe.py
Labels: non-breaking, improvement, 3 - Ready for Review

#939 Migrate generic components from azure-ad workflow
  docs/source/modules/core/from_control_message.md
  docs/source/modules/core/multiplexer.md
  docs/source/modules/core/to_control_message.md
  docs/source/modules/morpheus_modules.md
  examples/digital_fingerprinting/production/morpheus/benchmarks/resource/pipelines_conf.json
  examples/digital_fingerprinting/production/morpheus/benchmarks/test_bench_e2e_dfp_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_deployment.py
  examples/digital_fingerprinting/production/morpheus/dfp/utils/config_generator.py
  examples/digital_fingerprinting/production/morpheus/dfp_integrated_training_batch_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_integrated_training_streaming_pipeline.py
  examples/digital_fingerprinting/production/morpheus/notebooks/dfp_azure_integrated_training.ipynb
  examples/digital_fingerprinting/production/morpheus/notebooks/dfp_duo_integrated_training.ipynb
  morpheus/modules/__init__.py
  morpheus/modules/from_control_message.py
  morpheus/modules/serialize.py
  morpheus/modules/to_control_message.py
  morpheus/stages/general/linear_modules_stage.py
  morpheus/stages/general/multi_port_modules_stage.py
  morpheus/utils/module_ids.py
  tests/modules/__init__.py
  tests/modules/multiplexer.py
  tests/modules/test_from_control_message.py
  tests/modules/test_to_control_message.py
  tests/test_multi_port_modules_stage.py
  tests/test_multi_port_pipeline.py
  tests/tests_data/control_messages/control_message.json
  tests/tests_data/control_messages/control_message_azure.json
  tests/tests_data/control_messages/control_message_duo.json
  tests/tests_data/control_messages/train.json
  tests/tests_data/control_messages/train_infer.json
Labels: non-breaking, feature request, 3 - Ready for Review

#954 Remove problematic test causing segfaults
  morpheus/_lib/CMakeLists.txt
  tests/test_appshield_source_stage.py
Labels: bug, non-breaking, 3 - Ready for Review

#950 Add Pylint to CI
  .pylintrc
  ci/scripts/github/common.sh
  ci/scripts/python_checks.sh
  docker/conda/environments/cuda11.8_dev.yml
  examples/developer_guide/2_1_real_world_phishing/run.py
  examples/digital_fingerprinting/production/morpheus/benchmarks/benchmark_conf_generator.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_viz_postproc.py
  examples/digital_fingerprinting/starter/run_cloudtrail_dfp.py
  morpheus.code-workspace
  morpheus/__init__.py
  morpheus/cli/__init__.py
  morpheus/cli/click_completion_tools.py
  morpheus/cli/run.py
  morpheus/cli/utils.py
  morpheus/config.py
  morpheus/io/serializers.py
  morpheus/modules/write_to_file.py
  morpheus/parsers/event_parser.py
  morpheus/stages/input/duo_source_stage.py
  morpheus/stages/output/write_to_file_stage.py
  morpheus/stages/postprocess/validation_stage.py
  morpheus/utils/cudf_subword_helper.py
  morpheus/utils/file_utils.py
  morpheus/utils/logger.py
  pyproject.toml
  setup.cfg
  tests/benchmarks/conftest.py
  tests/benchmarks/test_bench_e2e_pipelines.py
  tests/test_abp.py
  tests/test_abp_kafka.py
  tests/test_cli.py
  tests/test_config.py
  tests/test_dfp.py
  tests/test_dfp_kafka.py
  tests/test_windows_event_parser.py
  tests/test_zeek.py
  tests/utils/__init__.py
  tests/utils/dataset_manager.py
Labels: non-breaking, improvement, 3 - Ready for Review

#951 Fixing multi-sender stage configurations
  morpheus/pipeline/pipeline.py
  morpheus/pipeline/receiver.py
  morpheus/pipeline/single_port_stage.py
  morpheus/pipeline/stream_wrapper.py
  tests/test_nonlinear_pipeline.py
Labels: bug, non-breaking

#955 Remove/update tests which mock MRC builder objects
  morpheus/stages/general/multi_port_modules_stage.py
  pyproject.toml
  tests/examples/digital_fingerprinting/test_write_to_s3_stage.py
  tests/test_directory_watcher.py
  tests/test_filter_detections_stage.py
  tests/test_inference_stage.py
  tests/test_monitor_stage.py
  tests/test_trigger_stage.py
Labels: bug, non-breaking, 3 - Ready for Review

#959 fix_contrib_instructions
  docs/source/developer_guide/contributing.md
Labels: enhancement, non-breaking, improvement, 5 - Ready to Merge
