Repository nv-morpheus/Morpheus, pull requests merged in 2023-04, with the labels that each got.

#806 Use ARC V2 self-hosted runners for CPU jobs
  .github/workflows/ci_pipe.yml
Labels: non-breaking, improvement

#842 Replace usage of PreprocessLogParsingStage with PreprocessNLPStage
  examples/log_parsing/README.md
  examples/log_parsing/preprocessing.py
  examples/log_parsing/run.py
  morpheus/stages/preprocess/preprocess_nlp_stage.py
Labels: non-breaking, improvement, 3 - Ready for Review

#844 Suppress volatile warning when building code generated by Cython
  morpheus/_lib/cmake/libraries/cudf_helpers.cmake
Labels: non-breaking, improvement, 3 - Ready for Review

#820 Pre-allocate needed columns in abp_pcap_detection example
  examples/abp_pcap_detection/abp_pcap_preprocessing.py
  tests/conftest.py
  tests/examples/test_abp_pcap_preprocessing.py
  tests/tests_data/abp_pcap.jsonlines
  tests/tests_data/abp_pcap_expected_input_0.csv
  tests/utils.py
Labels: non-breaking, improvement, 3 - Ready for Review

#860 GitHub Infra Update -Delete QST Issue Template in Favor of Discussions, Remove Add to Project Action
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/submit_question.yml
Labels: non-breaking, improvement, 3 - Ready for Review

#847 Add dataset fixture to ease fetching DataFrames for tests
  tests/conftest.py
  tests/dfencoder/test_autoencoder.py
  tests/dfencoder/test_dfencoder_distributed_e2e.py
  tests/dfencoder/test_dfencoder_e2e.py
  tests/test_abp_kafka.py
  tests/test_add_classifications_stage.py
  tests/test_add_classifications_stage_pipe.py
  tests/test_add_scores_stage.py
  tests/test_add_scores_stage_pipe.py
  tests/test_cli.py
  tests/test_concat_df.py
  tests/test_conftest.py
  tests/test_deserialize_stage_pipe.py
  tests/test_dfp_kafka.py
  tests/test_file_in_out.py
  tests/test_filter_detections_stage_column_pipe.py
  tests/test_filter_detections_stage_pipe.py
  tests/test_inference_stage.py
  tests/test_inference_worker.py
  tests/test_kafka_source_stage_pipe.py
  tests/test_message_meta.py
  tests/test_multi_message.py
  tests/test_nonlinear_pipeline.py
  tests/test_phishing_kafka.py
  tests/test_pipe_viz.py
  tests/test_preallocation_pipe.py
  tests/test_sid_kafka.py
  tests/utils/__init__.py
  tests/utils/dataset_manager.py
  tests/utils/inference_worker.py
  tests/utils/stages/__init__.py
  tests/utils/stages/conv_msg.py
  tests/utils/stages/dfp_length_checker.py
  tests/utils/test_directories.py
Labels: non-breaking, improvement, 5 - Ready to Merge

#861 Use eval_batch_size for AutoEncoder loss stats
  morpheus/models/dfencoder/autoencoder.py
Labels: non-breaking, improvement

#888 Use new cudf C++ json writer
  morpheus/_lib/include/morpheus/io/serializers.hpp
  morpheus/_lib/src/io/serializers.cpp
  morpheus/_lib/src/stages/write_to_file.cpp
  morpheus/_lib/tests/test_file_in_out.cpp
Labels: breaking, improvement, 3 - Ready for Review

#878 Use ARC V2 self-hosted runners for GPU jobs
  .github/workflows/ci_pipe.yml
Labels: non-breaking, improvement

#891 Update gnn_fraud_detection_pipeline & ransomware_detection examples to use the same version of dask
  ci/conda/recipes/morpheus/meta.yaml
  docker/conda/environments/cuda11.8_dev.yml
  examples/gnn_fraud_detection_pipeline/requirements.yml
  examples/ransomware_detection/README.md
Labels: bug, non-breaking, 3 - Ready for Review

#893 Fix `get_anomaly_score_losses` in dfencoder to work without categorical features
  morpheus/models/dfencoder/autoencoder.py
  tests/dfencoder/test_autoencoder.py
Labels: bug, non-breaking, 3 - Ready for Review

#897 [ENH] Label External Issues: Update secret, add discussions
  .github/workflows/label-external-issues.yml
Labels: non-breaking, improvement, 3 - Ready for Review

#899 [ENH] Change external labeler to use the GH CLI for fine-grained token support
  .github/workflows/label-external-issues.yml
Labels: non-breaking, improvement, 3 - Ready for Review

#918 Add CONTRIBUTOR to triage label exception
  .github/workflows/label-external-issues.yml
Labels: non-breaking, improvement, 3 - Ready for Review
