Repository nv-morpheus/Morpheus, pull requests merged in 2023-08, with the labels that each got.

#1095 Reorganize C++ Tests
  morpheus/_lib/tests/CMakeLists.txt
  morpheus/_lib/tests/io/test_data_loader.cpp
  morpheus/_lib/tests/io/test_data_loader_registry.cpp
  morpheus/_lib/tests/io/test_io.hpp
  morpheus/_lib/tests/io/test_loaders.cpp
  morpheus/_lib/tests/messages/test_control_message.cpp
  morpheus/_lib/tests/messages/test_dev_doc_ex3.cpp
  morpheus/_lib/tests/messages/test_messages.hpp
  morpheus/_lib/tests/messages/test_sliced_message_meta.cpp
  morpheus/_lib/tests/modules/test_data_loader_module.cpp
  morpheus/_lib/tests/modules/test_modules.hpp
  morpheus/_lib/tests/test_cuda.cu
  morpheus/_lib/tests/test_deserializers.cpp
  morpheus/_lib/tests/test_dev_mem_info.cpp
  morpheus/_lib/tests/test_file_in_out.cpp
  morpheus/_lib/tests/test_main.cpp
  morpheus/_lib/tests/test_matx_util.cpp
  morpheus/_lib/tests/test_multi_slices.cpp
  morpheus/_lib/tests/test_tensor.cpp
  morpheus/_lib/tests/test_type_util.cpp
  morpheus/_lib/tests/test_utils/common.cpp
  morpheus/_lib/tests/test_utils/common.hpp
  scripts/compile.sh
Labels: non-breaking, improvement

#986 Implement rest data loader
  ci/iwyu/mappings.imp
  docs/source/loaders/core/rest_to_df_loader.md
  docs/source/loaders/index.md
  morpheus/_lib/include/morpheus/io/data_loader.hpp
  morpheus/_lib/src/io/data_loader.cpp
  morpheus/_lib/src/io/loaders/rest.cpp
  morpheus/_lib/src/modules/data_loader_module.cpp
  morpheus/_lib/tests/io/test_loaders.cpp
  tests/modules/test_morpheus_modules.py
Labels: enhancement, non-breaking, improvement, 4 - Waiting on Author

#1119 Add a --viz_direction flag to CLI
  morpheus/cli/commands.py
  tests/test_pipe_viz.py
Labels: non-breaking, feature request, 3 - Ready for Review, Priority 2

#1112 Slimmed down CI runners and published artifact urls
  .github/workflows/pull_request.yml
  ci/pylint/morpheus_lib_import_checker.py
  ci/runner/Dockerfile
  ci/scripts/github/build.sh
  ci/scripts/github/checks.sh
  ci/scripts/github/common.sh
  ci/scripts/github/docs.sh
  ci/scripts/github/test.sh
  ci/scripts/run_ci_local.sh
  docker/conda/environments/cuda11.8_dev.yml
  morpheus/loaders/file_to_df_loader.py
  morpheus/modules/payload_batcher.py
  morpheus/stages/doca/doca_source_stage.py
  morpheus/utils/loader_utils.py
  pyproject.toml
Labels: non-breaking, improvement, 3 - Ready for Review, Priority 2

#1088 Improve `gitutils.py` by using the Github CLI when available
  ci/scripts/copyright.py
  ci/scripts/gitutils.py
  morpheus/_lib/doca/__init__.pyi
  pyproject.toml
Labels: non-breaking, improvement, 3 - Ready for Review

#1113 Fix intermittent failures in test_dfencoder_distributed_e2e test
  morpheus/models/dfencoder/multiprocessing.py
  tests/dfencoder/test_dfencoder_distributed_e2e.py
Labels: bug, non-breaking, 3 - Ready for Review, Priority 2

#1120 Fix issue where DFPFileToDataFrameStage logs messages about S3 even when S3 is not in use
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_file_to_df.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_duo_pipeline.py
  examples/digital_fingerprinting/production/morpheus/notebooks/dfp_azure_inference.ipynb
  examples/digital_fingerprinting/production/morpheus/notebooks/dfp_azure_training.ipynb
  examples/digital_fingerprinting/production/morpheus/notebooks/dfp_duo_inference.ipynb
  examples/digital_fingerprinting/production/morpheus/notebooks/dfp_duo_training.ipynb
  tests/examples/digital_fingerprinting/test_dfp_file_to_df.py
Labels: bug, non-breaking, 3 - Ready for Review, Priority 2

#1118 Fix Tests broken by Test Reorganization
  morpheus/_lib/tests/CMakeLists.txt
  morpheus/_lib/tests/io/test_io.hpp
Labels: bug, non-breaking

#1116 update devcontainer base to 23.10
  .devcontainer/Dockerfile
Labels: non-breaking, improvement

#1137 Add `parser_kwargs` to `FileSourceStage` to support json files
  morpheus/_lib/include/morpheus/io/deserializers.hpp
  morpheus/_lib/include/morpheus/stages/file_source.hpp
  morpheus/_lib/src/io/deserializers.cpp
  morpheus/_lib/src/stages/file_source.cpp
  morpheus/_lib/stages/__init__.pyi
  morpheus/_lib/stages/module.cpp
  morpheus/_lib/tests/test_file_in_out.cpp
  morpheus/stages/input/file_source_stage.py
  tests/test_file_in_out.py
  tests/tests_data/simple.json
Labels: non-breaking, feature request

#1060 Less intrusive doc builds
  docs/source/conf.py
  docs/source/sphinxext/github_link.py
  morpheus/utils/nvt/__init__.py
  morpheus/utils/nvt/decorators.py
  morpheus/utils/nvt/mutate.py
  morpheus/utils/nvt/schema_converters.py
  morpheus/utils/schema_transforms.py
  tests/utils/nvt/integration/test_mutate_op.py
  tests/utils/nvt/test_mutate_op.py
Labels: non-breaking, doc, 3 - Ready for Review

#1134 Add tasks and metadata properties to python ControlMessage
  morpheus/_lib/include/morpheus/messages/control.hpp
  morpheus/_lib/messages/__init__.pyi
  morpheus/_lib/messages/module.cpp
  morpheus/_lib/src/messages/control.cpp
  tests/messages/test_control_message.py
Labels: non-breaking, improvement

#1135 Prefer conda package over pip dependencies
  .devcontainer/bin/dev-pytest-kafka-install
  ci/scripts/github/common.sh
  docker/Dockerfile
  docker/conda/environments/cuda11.8_dev.yml
  docker/conda/environments/cuda11.8_runtime.yml
  docker/conda/environments/requirements.txt
  setup.py
Labels: non-breaking, improvement

#1159 Use `copy-pr-bot`
  .github/copy-pr-bot.yaml
  .github/ops-bot.yaml
Labels: non-breaking, improvement

#1157 Update to handle GitHub CLI not installed
  ci/scripts/gitutils.py
Labels: bug, non-breaking, 3 - Ready for Review

#1121 Update TimeSeries stage to also work with Production DFP
  morpheus/stages/postprocess/timeseries_stage.py
  tests/benchmarks/test_bench_e2e_pipelines.py
  tests/test_dfp.py
  tests/test_dfp_kafka.py
Labels: bug, non-breaking, 3 - Ready for Review

#1160 Scope Zookeeper & Kafka fixtures to session
  tests/_utils/__init__.py
  tests/_utils/kafka.py
  tests/conftest.py
  tests/test_abp_kafka.py
  tests/test_kafka_source_stage_pipe.py
  tests/test_phishing_kafka.py
Labels: non-breaking, improvement, 3 - Ready for Review, Priority 2

#1165 Make manual_seed an autouse fixture for gnn_fraud_detection_pipeline tests
  tests/examples/gnn_fraud_detection_pipeline/conftest.py
  tests/examples/gnn_fraud_detection_pipeline/test_classification_stage.py
  tests/examples/gnn_fraud_detection_pipeline/test_graph_sage_stage.py
Labels: bug, non-breaking, 3 - Ready for Review, Priority 1

#1108 ABP nvsmi sample data generation
  examples/abp_nvsmi_detection/README.md
  examples/abp_nvsmi_detection/nvsmi_data_extract.py
  models/abp-models/abp-nvsmi-xgb-20210310.bst
  models/abp-models/abp-nvsmi-xgb-20230831.bst
  models/data/columns_fil.txt
  models/training-tuning-scripts/abp-models/abp_nvsmi_xgb_training.ipynb
  models/training-tuning-scripts/abp-models/abp_nvsmi_xgb_training.py
  models/triton-model-repo/abp-nvsmi-xgb/1/abp-nvsmi-xgb.bst
  models/triton-model-repo/abp-nvsmi-xgb/config.pbtxt
  morpheus/cli/commands.py
  tests/test_abp.py
  tests/test_abp_kafka.py
Labels: non-breaking, improvement
