Repository nv-morpheus/Morpheus, pull requests merged in 2023-03, with the labels that each got.

#739 [FEA]: External issue label
  .github/workflows/label-external-issues.yml
Labels: non-breaking, improvement, 5 - Ready to Merge

#737 Create types.hpp
  .gitignore
  morpheus/_lib/include/morpheus/messages/memory/inference_memory.hpp
  morpheus/_lib/include/morpheus/messages/memory/response_memory.hpp
  morpheus/_lib/include/morpheus/messages/memory/response_memory_probs.hpp
  morpheus/_lib/include/morpheus/messages/memory/tensor_memory.hpp
  morpheus/_lib/include/morpheus/messages/multi.hpp
  morpheus/_lib/include/morpheus/objects/rmm_tensor.hpp
  morpheus/_lib/include/morpheus/objects/tensor.hpp
  morpheus/_lib/include/morpheus/objects/tensor_object.hpp
  morpheus/_lib/include/morpheus/types.hpp
  morpheus/_lib/include/morpheus/utilities/tensor_util.hpp
  morpheus/_lib/src/messages/memory/inference_memory.cpp
  morpheus/_lib/src/messages/memory/inference_memory_fil.cpp
  morpheus/_lib/src/messages/memory/inference_memory_nlp.cpp
  morpheus/_lib/src/messages/memory/response_memory.cpp
  morpheus/_lib/src/messages/memory/response_memory_probs.cpp
  morpheus/_lib/src/messages/memory/tensor_memory.cpp
  morpheus/_lib/src/messages/multi_tensor.cpp
  morpheus/_lib/src/stages/add_classification.cpp
  morpheus/_lib/src/stages/add_scores.cpp
  morpheus/_lib/src/stages/preprocess_fil.cpp
  morpheus/_lib/src/stages/preprocess_nlp.cpp
  morpheus/_lib/src/stages/triton_inference.cpp
  morpheus/_lib/src/utilities/cupy_util.cpp
  morpheus/_lib/src/utilities/tensor_util.cpp
  morpheus/_lib/tests/test_tensor.cpp
Labels: non-breaking, improvement, 3 - Ready for Review

#655 Fix Python bindings for TensorMemory
  ci/iwyu/mappings.imp
  morpheus/_lib/include/morpheus/messages/memory/inference_memory.hpp
  morpheus/_lib/include/morpheus/messages/memory/inference_memory_fil.hpp
  morpheus/_lib/include/morpheus/messages/memory/inference_memory_nlp.hpp
  morpheus/_lib/include/morpheus/messages/memory/response_memory.hpp
  morpheus/_lib/include/morpheus/messages/memory/response_memory_probs.hpp
  morpheus/_lib/include/morpheus/messages/memory/tensor_memory.hpp
  morpheus/_lib/include/morpheus/messages/multi_inference.hpp
  morpheus/_lib/include/morpheus/messages/multi_inference_fil.hpp
  morpheus/_lib/include/morpheus/messages/multi_inference_nlp.hpp
  morpheus/_lib/include/morpheus/messages/multi_response.hpp
  morpheus/_lib/include/morpheus/messages/multi_response_probs.hpp
  morpheus/_lib/include/morpheus/messages/multi_tensor.hpp
  morpheus/_lib/include/morpheus/utilities/cupy_util.hpp
  morpheus/_lib/src/messages/memory/inference_memory.cpp
  morpheus/_lib/src/messages/memory/inference_memory_fil.cpp
  morpheus/_lib/src/messages/memory/inference_memory_nlp.cpp
  morpheus/_lib/src/messages/memory/response_memory.cpp
  morpheus/_lib/src/messages/memory/response_memory_probs.cpp
  morpheus/_lib/src/messages/memory/tensor_memory.cpp
  morpheus/_lib/src/messages/multi_inference.cpp
  morpheus/_lib/src/messages/multi_inference_fil.cpp
  morpheus/_lib/src/messages/multi_inference_nlp.cpp
  morpheus/_lib/src/messages/multi_response.cpp
  morpheus/_lib/src/messages/multi_response_probs.cpp
  morpheus/_lib/src/messages/multi_tensor.cpp
  morpheus/_lib/src/objects/mutable_table_ctx_mgr.cpp
  morpheus/_lib/src/python_modules/messages.cpp
  morpheus/_lib/src/stages/preprocess_fil.cpp
  morpheus/_lib/src/utilities/cupy_util.cpp
  morpheus/messages/__init__.py
  morpheus/messages/memory/__init__.py
  morpheus/messages/memory/inference_memory.py
  morpheus/messages/memory/response_memory.py
  morpheus/messages/memory/tensor_memory.py
  morpheus/messages/multi_ae_message.py
  morpheus/messages/multi_inference_message.py
  morpheus/messages/multi_message.py
  morpheus/messages/multi_response_message.py
  morpheus/messages/multi_tensor_message.py
  morpheus/messages/tensor_memory.py
  tests/conftest.py
  tests/test_inference_stage.py
  tests/test_messages.py
  tests/test_tensor_memory.py
Labels: bug, breaking, 5 - Ready to Merge

#742 Use AWS OIDC to get AWS creds
  .github/workflows/ci_pipe.yml
  .github/workflows/pull_request.yml
Labels: non-breaking, improvement

#745 Update workflow `permissions` block
  .github/workflows/ci_pipe.yml
  .github/workflows/pull_request.yml
Labels: non-breaking, improvement

#718 Replace soon to be deprecated docker base gpuci/miniforge-cuda
  docker/Dockerfile
  docker/build_container.sh
  docker/run_container_dev.sh
  docker/run_container_release.sh
  models/mlflow/README.md
  models/mlflow/docker/Dockerfile
  scripts/compile.sh
Labels: bug, non-breaking, 3 - Ready for Review

#743 23.01 back-patch of #742 - Use AWS OIDC to get AWS creds
  .github/workflows/ci_pipe.yml
  .github/workflows/pull_request.yml
Labels: bug, non-breaking, 3 - Ready for Review

#750 [BUG] Add write permission to triage labeler action
  .github/workflows/label-external-issues.yml
Labels: bug, non-breaking

#749 Make use of new MRC_PTR_CAST
  docker/conda/environments/cuda11.5_dev.yml
  morpheus/_lib/include/morpheus/messages/multi.hpp
  morpheus/_lib/src/messages/multi.cpp
  morpheus/_lib/src/messages/multi_tensor.cpp
Labels: non-breaking, improvement, 3 - Ready for Review

#748 Update to CUDA 11.8
  .devcontainer/opt/morpheus/bin/post-attach-command.sh
  .github/workflows/ci_pipe.yml
  ci/conda/recipes/morpheus/conda_build_config.yaml
  ci/conda/recipes/morpheus/meta.yaml
  ci/conda/recipes/run_conda_build.sh
  ci/runner/Dockerfile
  docker/Dockerfile
  docker/build_container.sh
  docker/conda/environments/cuda11.8_dev.yml
  docker/conda/environments/cuda11.8_runtime.yml
  examples/digital_fingerprinting/production/conda_env.yml
  examples/gnn_fraud_detection_pipeline/requirements.yml
  models/mlflow/docker/Dockerfile
Labels: non-breaking, feature request

#755 Updating to driver 525
  .github/workflows/ci_pipe.yml
  .github/workflows/pull_request.yml
  ci/runner/Dockerfile
  ci/scripts/github/build.sh
  docs/source/developer_guide/contributing.md
Labels: non-breaking, improvement

#751 [FEA] Create a PR template
  .github/PULL_REQUEST_TEMPLATE.md
  ci/scripts/copyright.py
Labels: non-breaking, feature request

#772 Fix intermittent test failure in tests/test_message_meta.py
  tests/test_message_meta.py
Labels: bug, non-breaking, 3 - Ready for Review, Priority 1

#774 Fix source code links from docs
  docs/source/conf.py
Labels: non-breaking, doc, 3 - Ready for Review

#714 Fix detecting index column when reading from CSV in C++
  ci/iwyu/mappings.imp
  morpheus/_lib/include/morpheus/io/deserializers.hpp
  morpheus/_lib/include/morpheus/io/serializers.hpp
  morpheus/_lib/include/morpheus/objects/file_types.hpp
  morpheus/_lib/src/io/deserializers.cpp
  morpheus/_lib/src/messages/meta.cpp
  morpheus/_lib/src/objects/file_types.cpp
  morpheus/_lib/src/python_modules/common.cpp
  morpheus/_lib/src/python_modules/stages.cpp
  morpheus/_lib/src/stages/file_source.cpp
  morpheus/_lib/tests/CMakeLists.txt
  morpheus/_lib/tests/test_deserializers.cpp
  morpheus/_lib/tests/test_file_in_out.cpp
  morpheus/io/deserializers.py
  tests/test_file_in_out.py
  tests/tests_data/filter_probs_w_id_col.csv
Labels: bug, non-breaking, 3 - Ready for Review

#780 Fix MultiAEMessage constructor
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_training.py
  morpheus/messages/multi_ae_message.py
Labels: bug, non-breaking, 3 - Ready for Review

#783 Fix the conda build
  ci/conda/recipes/morpheus/morpheus_build.sh
  ci/conda/recipes/run_conda_build.sh
  docker/Dockerfile
  docker/conda/environments/cuda11.8_dev.yml
Labels: bug, non-breaking

#778 Change userid_column_name to match the command line equivelants
  examples/digital_fingerprinting/starter/run_cloudtrail_dfp.py
Labels: bug, non-breaking, 3 - Ready for Review

#730 Avoid copy of source data in AddClassificationsStage and FilterDetectionsStage
  CMakeLists.txt
  morpheus/_lib/CMakeLists.txt
  morpheus/_lib/cmake/libraries/cuda_utils.cmake
  morpheus/_lib/cmake/libraries/cudf_helpers.cmake
  morpheus/_lib/cmake/libraries/morpheus.cmake
  morpheus/_lib/cmake/libraries/morpheus_utils.cmake
  morpheus/_lib/include/morpheus/objects/dev_mem_info.hpp
  morpheus/_lib/include/morpheus/objects/memory_descriptor.hpp
  morpheus/_lib/include/morpheus/objects/python_data_table.hpp
  morpheus/_lib/include/morpheus/objects/rmm_tensor.hpp
  morpheus/_lib/include/morpheus/objects/table_info.hpp
  morpheus/_lib/include/morpheus/objects/table_info_data.hpp
  morpheus/_lib/include/morpheus/objects/tensor_object.hpp
  morpheus/_lib/include/morpheus/utilities/cudf_util.hpp
  morpheus/_lib/include/morpheus/utilities/matx_util.hpp
  morpheus/_lib/include/morpheus/utilities/tensor_util.hpp
  morpheus/_lib/src/objects/data_table.cpp
  morpheus/_lib/src/objects/dev_mem_info.cpp
  morpheus/_lib/src/objects/memory_descriptor.cpp
  morpheus/_lib/src/objects/python_data_table.cpp
  morpheus/_lib/src/objects/rmm_tensor.cpp
  morpheus/_lib/src/objects/table_info_data.cpp
  morpheus/_lib/src/objects/tensor.cpp
  morpheus/_lib/src/stages/add_scores_stage_base.cpp
  morpheus/_lib/src/stages/filter_detection.cpp
  morpheus/_lib/src/stages/preprocess_fil.cpp
  morpheus/_lib/src/utilities/matx_util.cu
  morpheus/_lib/tests/CMakeLists.txt
  morpheus/_lib/tests/test_dev_mem_info.cpp
  morpheus/_lib/tests/test_tensor.cpp
Labels: non-breaking, improvement, 3 - Ready for Review

#787 Cleanup all uses of `import morpheus._lib.common`
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/developer_guide/guides/6_digital_fingerprinting_reference.md
  examples/developer_guide/2_1_real_world_phishing/recipient_features_stage.py
  examples/developer_guide/2_2_rabbitmq/read_simple.py
  examples/developer_guide/4_rabbitmq_cpp_stage/read_simple.py
  examples/digital_fingerprinting/production/morpheus/benchmarks/test_bench_e2e_dfp_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_file_to_df.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_inference.ipynb
  examples/digital_fingerprinting/production/morpheus/dfp_azure_modules_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_training.ipynb
  examples/digital_fingerprinting/production/morpheus/dfp_duo_inference.ipynb
  examples/digital_fingerprinting/production/morpheus/dfp_duo_modules_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_duo_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_duo_training.ipynb
  examples/digital_fingerprinting/visualization/dfp_viz_azure_pipeline.py
  examples/digital_fingerprinting/visualization/dfp_viz_duo_pipeline.py
  examples/ransomware_detection/stages/create_features.py
  examples/sid_visualization/run.py
  morpheus/cli/commands.py
  morpheus/cli/utils.py
  morpheus/common/__init__.py
  morpheus/io/deserializers.py
  morpheus/modules/file_to_df.py
  morpheus/modules/filter_detections.py
  morpheus/modules/write_to_file.py
  morpheus/pipeline/preallocator_mixin.py
  morpheus/pipeline/stream_wrapper.py
  morpheus/stages/input/autoencoder_source_stage.py
  morpheus/stages/input/azure_source_stage.py
  morpheus/stages/input/cloud_trail_source_stage.py
  morpheus/stages/input/duo_source_stage.py
  morpheus/stages/input/file_source_stage.py
  morpheus/stages/output/write_to_file_stage.py
  morpheus/stages/postprocess/add_classifications_stage.py
  morpheus/stages/postprocess/add_scores_stage.py
  morpheus/stages/postprocess/add_scores_stage_base.py
  morpheus/stages/postprocess/filter_detections_stage.py
  morpheus/stages/postprocess/validation_stage.py
  morpheus/utils/directory_watcher.py
  scripts/compare_data_files.py
  tests/test_abp_kafka.py
  tests/test_cli.py
  tests/test_deserialize_stage_pipe.py
  tests/test_dfp_kafka.py
  tests/test_file_in_out.py
  tests/test_filter_detections_stage.py
  tests/test_filter_detections_stage_column_pipe.py
  tests/test_kafka_source_stage_pipe.py
  tests/test_message_meta.py
  tests/test_multi_message.py
  tests/test_multi_segment.py
  tests/test_nonlinear_pipeline.py
  tests/test_phishing_kafka.py
  tests/test_preallocation_pipe.py
  tests/test_serialize_stage_pipe.py
  tests/test_sid_kafka.py
  tests/test_tensor_memory.py
  tests/test_write_to_kafka_stage_pipe.py
  tests/utils.py
Labels: non-breaking, improvement

#763 Migrate dfencoder to morpheus repo
  ci/scripts/github/build.sh
  ci/scripts/github/test.sh
  docker/conda/environments/cuda11.8_dev.yml
  docker/conda/environments/requirements.txt
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_training.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_mlflow_model_writer.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_training.py
  examples/digital_fingerprinting/production/morpheus/dfp/utils/model_cache.py
  examples/digital_fingerprinting/production/morpheus/dfp/utils/user_model_manager.py
  models/training-tuning-scripts/dfp-models/hammah-20211017-script.py
  models/training-tuning-scripts/dfp-models/hammah-20211017.ipynb
  models/training-tuning-scripts/phishing-models/phish-bert-training.ipynb
  models/training-tuning-scripts/root-cause-models/root-cause-bert.ipynb
  models/training-tuning-scripts/root-cause-models/root-cause-bert.py
  morpheus/_lib/cmake/libraries/morpheus.cmake
  morpheus/messages/multi_ae_message.py
  morpheus/messages/multi_inference_ae_message.py
  morpheus/models/__init__.py
  morpheus/models/dfencoder/__init__.py
  morpheus/models/dfencoder/autoencoder.py
  morpheus/models/dfencoder/dataframe.py
  morpheus/models/dfencoder/logging.py
  morpheus/models/dfencoder/scalers.py
  morpheus/modules/mlflow_model_writer.py
  morpheus/stages/inference/triton_inference_stage.py
  morpheus/stages/preprocess/train_ae_stage.py
  morpheus/utils/seed.py
  pyproject.toml
  setup.cfg
  setup.py
  tests/conftest.py
  tests/dfencoder/test_autoencoder.py
  tests/dfencoder/test_encoder_dataframe.py
  tests/dfencoder/test_pkg.py
  tests/dfencoder/test_scalers.py
  tests/test_conftest.py
  tests/test_dfp.py
  tests/test_filter_detections_stage.py
  tests/test_filter_detections_stage_column_pipe.py
  tests/test_message_meta.py
  tests/test_multi_message.py
  tests/test_nonlinear_pipeline.py
  tests/test_tensor_memory.py
  thirdparty/LICENSES/LICENSE.dfencoder
Labels: breaking, improvement, 3 - Ready for Review

#777 End-to-end dfencoder test
  models/datasets/validation-data/dfp_training_feature_samples.csv
  tests/dfencoder/test_dfencoder_e2e.py
Labels: non-breaking, improvement, 3 - Ready for Review

#792 Fix abp_pcap_detection example
  examples/abp_pcap_detection/abp_pcap_preprocessing.py
  morpheus/messages/multi_message.py
  tests/test_multi_message.py
Labels: bug, non-breaking, 3 - Ready for Review

#789 Update mlflow base image and python versions for CVE
  models/mlflow/docker/Dockerfile
  models/mlflow/docker/conda/mlflow-env.yml
Labels: enhancement, dependencies, non-breaking, improvement, 3 - Ready for Review

#802 Fix for log_parsing and ransomware_detection examples
  examples/log_parsing/messages.py
  examples/log_parsing/preprocessing.py
  examples/ransomware_detection/stages/preprocessing.py
Labels: bug, non-breaking, 3 - Ready for Review

#764 Have conda-build test cuml installation
  .devcontainer/initialize-command.sh
  ci/conda/recipes/morpheus/meta.yaml
  cmake/dependencies.cmake
  docker/Dockerfile
Labels: bug, non-breaking

#770 Add support for Parquet file input
  docs/source/developer_guide/guides/6_digital_fingerprinting_reference.md
  examples/digital_fingerprinting/production/morpheus/dfp_azure_inference.ipynb
  examples/digital_fingerprinting/production/morpheus/dfp_azure_training.ipynb
  examples/digital_fingerprinting/production/morpheus/dfp_duo_inference.ipynb
  examples/digital_fingerprinting/production/morpheus/dfp_duo_training.ipynb
  morpheus/_lib/include/morpheus/io/serializers.hpp
  morpheus/_lib/include/morpheus/objects/file_types.hpp
  morpheus/_lib/include/morpheus/stages/add_classification.hpp
  morpheus/_lib/include/morpheus/stages/add_scores.hpp
  morpheus/_lib/include/morpheus/stages/add_scores_stage_base.hpp
  morpheus/_lib/include/morpheus/stages/deserialize.hpp
  morpheus/_lib/include/morpheus/stages/file_source.hpp
  morpheus/_lib/include/morpheus/stages/filter_detection.hpp
  morpheus/_lib/include/morpheus/stages/kafka_source.hpp
  morpheus/_lib/include/morpheus/stages/preallocate.hpp
  morpheus/_lib/include/morpheus/stages/preprocess_fil.hpp
  morpheus/_lib/include/morpheus/stages/preprocess_nlp.hpp
  morpheus/_lib/include/morpheus/stages/serialize.hpp
  morpheus/_lib/include/morpheus/stages/triton_inference.hpp
  morpheus/_lib/include/morpheus/stages/write_to_file.hpp
  morpheus/_lib/src/io/deserializers.cpp
  morpheus/_lib/src/io/serializers.cpp
  morpheus/_lib/src/objects/file_types.cpp
  morpheus/_lib/src/python_modules/common.cpp
  morpheus/_lib/src/stages/write_to_file.cpp
  morpheus/common/__init__.py
  morpheus/io/deserializers.py
  morpheus/io/serializers.py
  tests/test_file_in_out.py
  tests/tests_data/filter_probs.parquet
  tests/utils.py
Labels: non-breaking, feature request, 3 - Ready for Review

#752 Add InMemorySinkStage
  morpheus/pipeline/linear_pipeline.py
  morpheus/stages/input/in_memory_source_stage.py
  morpheus/stages/output/compare_dataframe_stage.py
  morpheus/stages/output/in_memory_sink_stage.py
  morpheus/stages/postprocess/validation_stage.py
  morpheus/utils/compare_df.py
  morpheus/utils/concat_df.py
  tests/conftest.py
  tests/dfencoder/test_autoencoder.py
  tests/stages/__init__.py
  tests/stages/conv_msg.py
  tests/stages/dfp_length_checker.py
  tests/test_add_classifications_stage_pipe.py
  tests/test_add_scores_stage_pipe.py
  tests/test_cli.py
  tests/test_concat_df.py
  tests/test_deserialize_stage_pipe.py
  tests/test_file_in_out.py
  tests/test_filter_detections_stage_column_pipe.py
  tests/test_filter_detections_stage_pipe.py
  tests/test_kafka_source_stage_pipe.py
  tests/test_multi_segment.py
  tests/test_nonlinear_pipeline.py
  tests/test_phishing_kafka.py
  tests/test_pipe_viz.py
  tests/test_preallocation_pipe.py
  tests/test_serialize_stage_pipe.py
  tests/test_sid_kafka.py
  tests/test_triton_inference_stage.py
  tests/test_validation_stage_pipe.py
  tests/test_write_to_kafka_stage_pipe.py
  tests/utils.py
Labels: non-breaking, feature request, 3 - Ready for Review

#812 Fix debug log message caused by breaking the long string
  morpheus/stages/postprocess/filter_detections_stage.py
Labels: bug, non-breaking, 3 - Ready for Review

#813 Set default DFP container version to 23.03
  ci/conda/recipes/morpheus/meta.yaml
  examples/digital_fingerprinting/production/docker-compose.yml
Labels: bug, non-breaking, 3 - Ready for Review

#758 Document adding cuML and fix the gnn_fraud_detection_pipeline example
  docker/conda/environments/cuda11.8_dev.yml
  docs/source/developer_guide/contributing.md
  examples/gnn_fraud_detection_pipeline/README.md
  examples/gnn_fraud_detection_pipeline/requirements.yml
  examples/gnn_fraud_detection_pipeline/stages/graph_sage_stage.py
Labels: bug, non-breaking, 3 - Ready for Review

#805 Convert `MonitorStage` to a component
  morpheus/stages/general/monitor_stage.py
  tests/test_monitor_stage.py
Labels: non-breaking, improvement

#775 Add multi-gpu and dataloader support for dfencoder
  ci/scripts/github/common.sh
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_training.py
  models/datasets/validation-data/dfp_dataloader_test/inference/dfp_inference_samples.csv
  models/datasets/validation-data/dfp_dataloader_test/preset_cats.json
  models/datasets/validation-data/dfp_dataloader_test/preset_numerical_scaler_params.json
  models/datasets/validation-data/dfp_dataloader_test/train/dfp_train_samples.csv
  models/datasets/validation-data/dfp_dataloader_test/validation/dfp_validation_samples.csv
  morpheus/models/dfencoder/__init__.py
  morpheus/models/dfencoder/ae_module.py
  morpheus/models/dfencoder/autoencoder.py
  morpheus/models/dfencoder/dataframe.py
  morpheus/models/dfencoder/dataloader.py
  morpheus/models/dfencoder/distributed_ae.py
  morpheus/models/dfencoder/logging.py
  morpheus/models/dfencoder/multiprocessing.py
  tests/dfencoder/test_autoencoder.py
  tests/dfencoder/test_dfencoder_distributed_e2e.py
  tests/dfencoder/test_dfencoder_e2e.py
Labels: non-breaking, improvement, 3 - Ready for Review

#821 Fix handling of message offsets in ae pre-processing and timeseries stage
  morpheus/stages/postprocess/timeseries_stage.py
  morpheus/stages/preprocess/preprocess_ae_stage.py
Labels: bug, non-breaking, 3 - Ready for Review, Priority 0

#828 Add Node.js install instructions to DFP Viz readme
  examples/digital_fingerprinting/visualization/README.md
Labels: non-breaking, doc
