Repository nv-morpheus/Morpheus, pull requests merged in 2023-02, with the labels that each got.

#662 Checking out a specific commit, requires a non-shallow checkout
  examples/developer_guide/4_rabbitmq_cpp_stage/cmake/Configure_rabbitmq.cmake
Labels: bug, non-breaking, 3 - Ready for Review, Priority 0

#666 Remove duplicate menu entry for the getting_started guide
  docs/source/index.rst
Labels: non-breaking, doc, 3 - Ready for Review, ! - Hotfix, Priority 0

#663 WriteToFileStage optionally emit a flush on each message received
  morpheus/_lib/include/morpheus/io/serializers.hpp
  morpheus/_lib/include/morpheus/stages/write_to_file.hpp
  morpheus/_lib/src/io/serializers.cpp
  morpheus/_lib/src/python_modules/stages.cpp
  morpheus/_lib/src/stages/write_to_file.cpp
  morpheus/stages/output/write_to_file_stage.py
  tests/test_file_in_out_stage_pipe.py
  tests/test_write_to_file_stage.py
Labels: non-breaking, improvement, 3 - Ready for Review

#664 Benchmarks for DFP Production Pipeline
  docs/source/developer_guide/guides/6_digital_fingerprinting_reference.md
  examples/digital_fingerprinting/production/morpheus/benchmarks/README.md
  examples/digital_fingerprinting/production/morpheus/benchmarks/__init__.py
  examples/digital_fingerprinting/production/morpheus/benchmarks/conftest.py
  examples/digital_fingerprinting/production/morpheus/benchmarks/dfp_config.py
  examples/digital_fingerprinting/production/morpheus/benchmarks/resource/modules_conf.json
  examples/digital_fingerprinting/production/morpheus/benchmarks/resource/pipelines_conf.json
  examples/digital_fingerprinting/production/morpheus/benchmarks/test_bench_e2e_dfp_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_modules_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_duo_modules_pipeline.py
Labels: non-breaking, feature request, 3 - Ready for Review

#673 [BUG] DFP benchmark related pytest error
  examples/digital_fingerprinting/production/morpheus/benchmarks/README.md
  pyproject.toml
Labels: bug, breaking, 2 - In Progress

#677 Add Pytest 'testpaths'
  pyproject.toml
Labels: bug, breaking, 3 - Ready for Review

#679 Adopt v0.12.0 of rabbitmq-c and return to using a shallow checkout
  examples/developer_guide/4_rabbitmq_cpp_stage/cmake/Configure_rabbitmq.cmake
  examples/developer_guide/4_rabbitmq_cpp_stage/cmake/dependencies.cmake
Labels: non-breaking, improvement, 3 - Ready for Review

#682 Move duplicated one-liner to TensorUtils
  morpheus/_lib/include/morpheus/utilities/tensor_util.hpp
  morpheus/_lib/src/objects/dev_mem_info.cpp
  morpheus/_lib/src/objects/rmm_tensor.cpp
  morpheus/_lib/src/stages/triton_inference.cpp
  morpheus/_lib/src/utilities/tensor_util.cpp
Labels: non-breaking, improvement, 3 - Ready for Review

#683 Update DFPRollingWindowStage to emit correct window
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_rolling_window_stage.py
Labels: bug, non-breaking

#669 Training/Inference Module DFP Production
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_inference.py
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_inference_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_postprocessing.py
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_training_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp/utils/config_generator.py
  examples/digital_fingerprinting/production/morpheus/dfp/utils/derive_args.py
  examples/digital_fingerprinting/production/morpheus/dfp/utils/module_ids.py
  examples/digital_fingerprinting/production/morpheus/dfp/utils/schema_utils.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_modules_inference.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_modules_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_modules_training.py
  examples/digital_fingerprinting/production/morpheus/dfp_duo_modules_inference.py
  examples/digital_fingerprinting/production/morpheus/dfp_duo_modules_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_duo_modules_training.py
  morpheus/modules/file_to_df.py
  morpheus/modules/filter_detections.py
  morpheus/modules/serialize.py
  morpheus/modules/write_to_file.py
  morpheus/utils/module_ids.py
Labels: non-breaking, feature request, 3 - Ready for Review

#676 Fix CLI parsing of C++ enum values
  morpheus.code-workspace
  morpheus/cli/commands.py
  morpheus/cli/register_stage.py
  morpheus/cli/utils.py
  morpheus/stages/input/file_source_stage.py
  morpheus/stages/input/kafka_source_stage.py
  morpheus/stages/output/write_to_file_stage.py
  morpheus/stages/postprocess/filter_detections_stage.py
  tests/test_cli.py
Labels: bug, non-breaking, 3 - Ready for Review, ! - Hotfix

#695 fix incorrect line and byte count benchmarks
  examples/digital_fingerprinting/production/morpheus/benchmarks/conftest.py
  tests/benchmarks/conftest.py
Labels: bug, non-breaking, 3 - Ready for Review

#671 Update contributing.md
  docs/source/developer_guide/contributing.md
Labels: non-breaking, doc, 3 - Ready for Review

#693 Update `sccache` bucket
  .github/workflows/ci_pipe.yml
  .github/workflows/pull_request.yml
  ci/scripts/github/build.sh
  ci/scripts/github/common.sh
Labels: non-breaking, improvement

#710 Add unittest to ensure the kafka source is respecting the pipeline batch size
  tests/test_kafka_source_stage_pipe.py
  tests/utils.py
Labels: bug, non-breaking, 3 - Ready for Review

#661 Clean up use of find/delete for CVE
  docker/Dockerfile
  models/mlflow/docker/Dockerfile
Labels: non-breaking, improvement, 3 - Ready for Review

#722 Fixing triton inference stage resource pool
  examples/ransomware_detection/stages/create_features.py
  examples/sid_visualization/run.py
  morpheus.code-workspace
  morpheus/stages/inference/triton_inference_stage.py
  tests/test_triton_inference_stage.py
Labels: bug, non-breaking, ! - Hotfix

#719 Run clang-format on entire repo
  examples/developer_guide/3_simple_cpp_stage/_lib/pass_thru.hpp
  morpheus/_lib/include/morpheus/messages/memory/response_memory.hpp
  morpheus/_lib/include/morpheus/messages/memory/response_memory_probs.hpp
  morpheus/_lib/include/morpheus/messages/memory/tensor_memory.hpp
  morpheus/_lib/include/morpheus/messages/multi.hpp
  morpheus/_lib/include/morpheus/messages/multi_inference.hpp
  morpheus/_lib/include/morpheus/messages/multi_response.hpp
  morpheus/_lib/include/morpheus/messages/multi_response_probs.hpp
  morpheus/_lib/include/morpheus/messages/multi_tensor.hpp
  morpheus/_lib/include/morpheus/objects/fiber_queue.hpp
  morpheus/_lib/include/morpheus/objects/python_data_table.hpp
  morpheus/_lib/include/morpheus/objects/rmm_tensor.hpp
  morpheus/_lib/include/morpheus/objects/tensor.hpp
  morpheus/_lib/include/morpheus/objects/wrapped_tensor.hpp
  morpheus/_lib/include/morpheus/stages/kafka_source.hpp
  morpheus/_lib/include/morpheus/stages/serialize.hpp
  morpheus/_lib/include/morpheus/stages/triton_inference.hpp
  morpheus/_lib/include/morpheus/utilities/cudf_util.hpp
  morpheus/_lib/include/morpheus/utilities/cupy_util.hpp
  morpheus/_lib/include/morpheus/utilities/stage_util.hpp
  morpheus/_lib/include/morpheus/utilities/table_util.hpp
  morpheus/_lib/src/messages/memory/inference_memory_fil.cpp
  morpheus/_lib/src/messages/memory/inference_memory_nlp.cpp
  morpheus/_lib/src/messages/memory/response_memory.cpp
  morpheus/_lib/src/messages/memory/response_memory_probs.cpp
  morpheus/_lib/src/messages/memory/tensor_memory.cpp
  morpheus/_lib/src/messages/multi.cpp
  morpheus/_lib/src/messages/multi_inference.cpp
  morpheus/_lib/src/messages/multi_inference_fil.cpp
  morpheus/_lib/src/messages/multi_inference_nlp.cpp
  morpheus/_lib/src/messages/multi_response.cpp
  morpheus/_lib/src/messages/multi_response_probs.cpp
  morpheus/_lib/src/messages/multi_tensor.cpp
  morpheus/_lib/src/objects/dev_mem_info.cpp
  morpheus/_lib/src/objects/fiber_queue.cpp
  morpheus/_lib/src/objects/file_types.cpp
  morpheus/_lib/src/objects/python_data_table.cpp
  morpheus/_lib/src/objects/tensor.cpp
  morpheus/_lib/src/objects/wrapped_tensor.cpp
  morpheus/_lib/src/stages/serialize.cpp
  morpheus/_lib/src/utilities/cudf_util.cpp
  morpheus/_lib/src/utilities/matx_util.cu
  morpheus/_lib/src/utilities/string_util.cpp
  morpheus/_lib/src/utilities/table_util.cpp
  morpheus/_lib/tests/test_cuda.cu
  morpheus/_lib/tests/test_main.cpp
Labels: non-breaking, improvement, 3 - Ready for Review

#709 Fix DFPTraining validation set option
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_training.py
Labels: bug, non-breaking, 3 - Ready for Review

#734 New base test class that invokes an embedded Python interpreter
  morpheus/_lib/tests/CMakeLists.txt
  morpheus/_lib/tests/test_morpheus.cpp
  morpheus/_lib/tests/test_morpheus.hpp
Labels: non-breaking, improvement, 3 - Ready for Review
