Repository nv-morpheus/Morpheus, pull requests merged in 2023-07, with the labels that each got.

#1011 Move hard-coded path in E2E benchmarks to config json
  tests/benchmarks/e2e_test_configs.json
  tests/benchmarks/test_bench_e2e_pipelines.py
Labels: bug, non-breaking, 3 - Ready for Review

#989 Grafana DFP dashboard
  .gitattributes
  examples/digital_fingerprinting/production/docker-compose.yml
  examples/digital_fingerprinting/production/grafana/README.md
  examples/digital_fingerprinting/production/grafana/config/dashboards.yaml
  examples/digital_fingerprinting/production/grafana/config/grafana.ini
  examples/digital_fingerprinting/production/grafana/dashboards/DFP_Dashboard.json
  examples/digital_fingerprinting/production/grafana/datasources/datasources.yaml
  examples/digital_fingerprinting/production/grafana/img/screenshot.png
  examples/digital_fingerprinting/production/morpheus/dfp_azure_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_duo_pipeline.py
Labels: non-breaking, feature request, 3 - Ready for Review

#1015 Upgrade to pytorch 2.0.1 conda package
  ci/conda/recipes/morpheus/meta.yaml
  ci/conda/recipes/run_conda_build.sh
  docker/Dockerfile
  docker/conda/environments/cuda11.8_dev.yml
  docker/conda/environments/requirements.txt
  models/training-tuning-scripts/log-parsing-models/log-parsing-training.ipynb
  models/training-tuning-scripts/log-parsing-models/requirements.txt
  models/training-tuning-scripts/phishing-models/requirements.txt
  models/training-tuning-scripts/root-cause-models/requirements.txt
  models/validation-inference-scripts/dfp-models/requirements.txt
  models/validation-inference-scripts/phishing-models/requirements.txt
  models/validation-inference-scripts/root-cause-models/requirements.txt
  setup.py
Labels: non-breaking, improvement

#1019 Remove PIP_FIND_LINKS for torch from setup.py
  setup.py
Labels: non-breaking, improvement, 3 - Ready for Review

#1020 Update to CUDF 23.06
  CMakeLists.txt
  ci/conda/recipes/morpheus/conda_build_config.yaml
  ci/conda/recipes/morpheus/meta.yaml
  docker/Dockerfile
  docker/build_container.sh
  docker/conda/environments/cuda11.8_dev.yml
  docker/conda/environments/cuda11.8_examples.yml
  docs/source/developer_guide/contributing.md
  examples/digital_fingerprinting/production/conda_env.yml
  examples/digital_fingerprinting/production/morpheus/benchmarks/README.md
  examples/gnn_fraud_detection_pipeline/requirements.yml
  examples/ransomware_detection/README.md
  morpheus/_lib/src/io/serializers.cpp
Labels: non-breaking, feature request

#1030 New CI images with rapids 23.06
  .github/workflows/pull_request.yml
  ci/scripts/run_ci_local.sh
Labels: non-breaking, improvement, 3 - Ready for Review

#1027 Fix release and dev container builds
  ci/conda/recipes/morpheus/meta.yaml
  ci/conda/recipes/morpheus/morpheus_build.sh
  ci/conda/recipes/run_conda_build.sh
  docker/conda/environments/cuda11.8_dev.yml
Labels: bug, non-breaking

#1033 Remove `loop` from several `asyncio` API calls
  morpheus/stages/postprocess/generate_viz_frames_stage.py
  morpheus/utils/producer_consumer_queue.py
Labels: bug, non-breaking

#1024 Remove conda's base pip (CVE)
  docker/Dockerfile
Labels: dependencies, non-breaking, improvement, 3 - Ready for Review, Priority 0

#1023 Adopt s3fs 2023.6 per #1022
  docker/conda/environments/cuda11.8_examples.yml
  examples/digital_fingerprinting/production/conda_env.yml
  examples/digital_fingerprinting/production/mlflow/Dockerfile
Labels: bug, non-breaking, 3 - Ready for Review, Priority 1

#938 Integrate NVTabular into Morpheus Core and replace existing column_info based workflows.
  ci/scripts/bootstrap_local_ci.sh
  docker/conda/environments/cuda11.8_dev.yml
  docker/conda/environments/requirements.txt
  morpheus/utils/column_info.py
  morpheus/utils/nvt/__init__.py
  morpheus/utils/nvt/decorators.py
  morpheus/utils/nvt/extensions/__init__.py
  morpheus/utils/nvt/extensions/morpheus_ext.py
  morpheus/utils/nvt/mutate.py
  morpheus/utils/nvt/patches/__init__.py
  morpheus/utils/nvt/patches/merlin_patches.py
  morpheus/utils/nvt/schema_converters.py
  morpheus/utils/nvt/transforms.py
  morpheus/utils/schema_transforms.py
  setup.py
  tests/examples/digital_fingerprinting/test_dfp_file_to_df.py
  tests/examples/digital_fingerprinting/test_dfp_preprocessing_stage.py
  tests/examples/ransomware_detection/test_create_features.py
  tests/test_column_info.py
  tests/utils/__init__.py
  tests/utils/dataset_manager.py
  tests/utils/nvt/__init__.py
  tests/utils/nvt/integration/__init__.py
  tests/utils/nvt/integration/test_mutate_op.py
  tests/utils/nvt/test_json_flatten_transform.py
  tests/utils/nvt/test_mutate_op.py
  tests/utils/nvt/test_schema_converters.py
  tests/utils/nvt/test_transforms.py
  tests/utils/stages/error_raiser.py
Labels: enhancement, non-breaking, improvement, 5 - Ready to Merge, Priority 0

#1035 SID visualization updates
  examples/sid_visualization/README.md
Labels: non-breaking, improvement

#1037 Update docs and examples to use Triton 23.06
  .devcontainer/docker-compose.yml
  docs/source/basics/building_a_pipeline.md
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/getting_started.md
  examples/abp_nvsmi_detection/README.md
  examples/abp_pcap_detection/README.md
  examples/log_parsing/README.md
  examples/nlp_si_detection/README.md
  examples/ransomware_detection/README.md
  examples/root_cause_analysis/README.md
  examples/sid_visualization/docker-compose.yml
  scripts/validation/val-globals.sh
  scripts/validation/val-utils.sh
  tests/benchmarks/README.md
Labels: non-breaking, improvement, 3 - Ready for Review

#1039 Fix documentation builds
  ci/scripts/github/docs.sh
  docker/conda/environments/cuda11.8_dev.yml
  docs/CMakeLists.txt
  docs/README.md
  docs/conda_docs.yml
  docs/source/conf.py
  docs/source/control_message_guide.md
  docs/source/developer_guide/contributing.md
  docs/source/developer_guide/guides.md
  docs/source/developer_guide/guides/10_modular_pipeline_digital_fingerprinting.md
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/developer_guide/guides/5_digital_fingerprinting.md
  docs/source/developer_guide/guides/6_digital_fingerprinting_reference.md
  docs/source/developer_guide/guides/8_cpp_modules.md
  docs/source/developer_guide/guides/index.rst
  docs/source/examples/index.rst
  docs/source/extra_info/glossary.md
  docs/source/getting_started.md
  docs/source/index.rst
  docs/source/loaders/core/file_to_df_loader.md
  docs/source/loaders/core/fsspec_loader.md
  docs/source/loaders/index.md
  docs/source/models_and_datasets.md
  docs/source/modules/core/data_loader.md
  docs/source/modules/index.md
  docs/source/modules/morpheus_modules.md
  docs/source/sphinxext/github_link.py
  docs/source/stages/morpheus_stages.md
  examples/abp_nvsmi_detection/README.md
  examples/digital_fingerprinting/production/morpheus/benchmarks/README.md
  examples/digital_fingerprinting/production/morpheus/dfp/modules/__init__.py
  morpheus.code-workspace
  morpheus/_lib/cudf_helpers.pyx
  morpheus/_lib/include/morpheus/objects/table_info.hpp
  morpheus/_lib/include/morpheus/stages/kafka_source.hpp
  morpheus/_lib/src/messages/multi_tensor.cpp
  morpheus/_lib/src/stages/kafka_source.cpp
  morpheus/_lib/src/utilities/cudf_util.cpp
  morpheus/_lib/src/utilities/matx_util.cu
  morpheus/io/data_manager.py
  morpheus/io/data_record.py
  morpheus/io/data_storage/in_memory.py
  morpheus/loaders/__init__.py
  morpheus/messages/memory/__init__.py
  morpheus/models/dfencoder/__init__.py
  morpheus/models/dfencoder/autoencoder.py
  morpheus/models/dfencoder/scalers.py
  morpheus/modules/__init__.py
  morpheus/modules/file_batcher.py
  morpheus/modules/mlflow_model_writer.py
  morpheus/modules/serialize.py
  morpheus/modules/to_control_message.py
  morpheus/parsers/ip.py
  morpheus/utils/nvt/mutate.py
  morpheus/utils/schema_transforms.py
  pyproject.toml
  tests/examples/ransomware_detection/test_create_features.py
Labels: non-breaking, doc, 3 - Ready for Review, Priority 0

#1053 Fix fetch_example_data.py to work with s3fs v2303.6
  examples/digital_fingerprinting/fetch_example_data.py
Labels: bug, non-breaking, 3 - Ready for Review

#1051 Fix models scripts/notebooks
  models/training-tuning-scripts/abp-models/abp-nvsmi-xgb-20210310.ipynb
  models/training-tuning-scripts/dfp-models/hammah-20211017.ipynb
  models/validation-inference-scripts/dfp-models/hammah_inference.py
  models/validation-inference-scripts/dfp-models/periodicity_detection.py
Labels: bug, non-breaking, 5 - Ready to Merge, Data Science

#1049 Clean up CLX references in docstring
  morpheus/parsers/ip.py
  tests/test_zeek.py
Labels: non-breaking, doc

#1040 Update docs to use `docker compose`
  ci/conda/channel/README.md
  docker/conda/environments/cuda11.8_dev.yml
  docs/source/developer_guide/contributing.md
  docs/source/developer_guide/guides/5_digital_fingerprinting.md
  examples/digital_fingerprinting/demo/README.md
  examples/digital_fingerprinting/production/README.md
  examples/digital_fingerprinting/production/grafana/README.md
  examples/digital_fingerprinting/production/morpheus/benchmarks/README.md
  examples/digital_fingerprinting/visualization/README.md
  examples/sid_visualization/README.md
  scripts/validation/kafka_testing.md
Labels: non-breaking, doc

#1056 Changing GRPC requirement from `grpc-cpp` to `libgrpc`
  docker/conda/environments/cuda11.8_dev.yml
Labels: non-breaking, improvement

#1054 Add note about needing docker-compose v1.28+ for DFP
  docs/source/developer_guide/guides/5_digital_fingerprinting.md
  examples/digital_fingerprinting/production/README.md
Labels: non-breaking, doc, 3 - Ready for Review

#1038 Example Documentation Updates
  ci/conda/recipes/morpheus/meta.yaml
  ci/scripts/cpp_checks.sh
  examples/digital_fingerprinting/demo/README.md
  examples/digital_fingerprinting/demo/bin/start.sh
  examples/digital_fingerprinting/production/README.md
  examples/digital_fingerprinting/production/conda_env.yml
  examples/digital_fingerprinting/production/docker-compose.yml
  examples/digital_fingerprinting/starter/README.md
  examples/doca/README.md
  examples/doca/run.py
  examples/root_cause_analysis/README.md
  morpheus/_lib/doca/include/doca_source.hpp
Labels: non-breaking, improvement

#1057 Support building the Morpheus containers when Morpheus is a submodule
  ci/conda/recipes/morpheus/meta.yaml
  ci/conda/recipes/run_conda_build.sh
  docker/Dockerfile
  docker/build_container.sh
  docker/build_container_release.sh
  docker/run_container_release.sh
Labels: non-breaking, improvement

#1070 Fix DocaSourceStage docstring
  morpheus/stages/doca/doca_source_stage.py
Labels: non-breaking, improvement

#1069 Setting `sqlalchemy` restrictions to be compatible with our version of `pandas`
  ci/conda/recipes/morpheus/meta.yaml
  docker/Dockerfile
  docker/build_container.sh
  docker/conda/environments/cuda11.8_dev.yml
Labels: bug, non-breaking

#1071 23.07 doc fixes
  docs/source/_static/py_properties.css
  docs/source/basics/building_a_pipeline.md
  docs/source/basics/overview.rst
  docs/source/conf.py
  docs/source/developer_guide/contributing.md
  docs/source/developer_guide/guides/10_modular_pipeline_digital_fingerprinting.md
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/developer_guide/guides/3_simple_cpp_stage.md
  docs/source/developer_guide/guides/4_source_cpp_stage.md
  docs/source/developer_guide/guides/7_python_modules.md
  docs/source/developer_guide/guides/9_control_messages.md
  docs/source/getting_started.md
  docs/source/modules/core/serialize.md
  docs/source/modules/examples/digital_fingerprinting/dfp_rolling_window.md
  docs/source/modules/index.md
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_preproc.py
  morpheus/_lib/tests/CMakeLists.txt
  morpheus/_lib/tests/messages/test_dev_doc_ex3.cpp
  morpheus/messages/message_meta.py
  morpheus/messages/multi_message.py
  morpheus/messages/multi_tensor_message.py
  morpheus/parsers/windows_event_parser.py
  morpheus/stages/doca/doca_source_stage.py
  morpheus/stages/input/appshield_source_stage.py
  morpheus/stages/input/file_source_stage.py
  morpheus/stages/preprocess/deserialize_stage.py
  morpheus/stages/preprocess/preprocess_nlp_stage.py
Labels: non-breaking, doc, 3 - Ready for Review, Priority 0

#1076 Add missing production DFP docstring
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_preprocessing_stage.py
Labels: non-breaking, doc, 3 - Ready for Review

#1092 Resolve forward merger conflices for `branch-23.11`
  CHANGELOG.md
Labels: bug, non-breaking

#1099 Move data dir to models
  .github/workflows/pull_request.yml
  ci/scripts/run_ci_local.sh
  models/data/bert-base-cased-hash.txt
  models/data/bert-base-cased-vocab.txt
  models/data/bert-base-uncased-hash.txt
  models/data/bert-base-uncased-vocab.txt
  models/data/columns_ae.txt
  models/data/columns_ae_azure.txt
  models/data/columns_ae_cloudtrail.txt
  models/data/columns_ae_duo.txt
  models/data/columns_fil.txt
  models/data/labels_ae.txt
  models/data/labels_nlp.txt
  models/data/labels_phishing.txt
  models/data/public_suffix_list.dat
  models/data/splunk_notable_regex.yaml
  models/data/windows_event_regex.yaml
  models/training-tuning-scripts/log-parsing-models/resources/bert-base-cased-hash.txt
  models/training-tuning-scripts/sid-models/resources/bert-base-cased-hash.txt
  models/training-tuning-scripts/sid-models/resources/bert-base-cased-vocab.txt
  models/training-tuning-scripts/sid-models/resources/bert-base-uncased-hash.txt
  models/training-tuning-scripts/sid-models/resources/bert-base-uncased-vocab.txt
  morpheus/data
  tests/test_cli.py
Labels: bug, non-breaking, 3 - Ready for Review, ! - Hotfix, Priority 0

#1103 [RELEASE] Morpheus v23.07.02 Hotfix
  .github/workflows/pull_request.yml
  CHANGELOG.md
  ci/scripts/run_ci_local.sh
  models/data/bert-base-cased-hash.txt
  models/data/bert-base-cased-vocab.txt
  models/data/bert-base-uncased-hash.txt
  models/data/bert-base-uncased-vocab.txt
  models/data/columns_ae.txt
  models/data/columns_ae_azure.txt
  models/data/columns_ae_cloudtrail.txt
  models/data/columns_ae_duo.txt
  models/data/columns_fil.txt
  models/data/labels_ae.txt
  models/data/labels_nlp.txt
  models/data/labels_phishing.txt
  models/data/public_suffix_list.dat
  models/data/splunk_notable_regex.yaml
  models/data/windows_event_regex.yaml
  models/training-tuning-scripts/log-parsing-models/resources/bert-base-cased-hash.txt
  models/training-tuning-scripts/sid-models/resources/bert-base-cased-hash.txt
  models/training-tuning-scripts/sid-models/resources/bert-base-cased-vocab.txt
  models/training-tuning-scripts/sid-models/resources/bert-base-uncased-hash.txt
  models/training-tuning-scripts/sid-models/resources/bert-base-uncased-vocab.txt
  morpheus/data
  tests/test_cli.py
Labels: ! - Hotfix, ! - Release

#1083 Fix local CI building from a specific commit
  ci/scripts/bootstrap_local_ci.sh
Labels: bug, non-breaking, 3 - Ready for Review
