Repository nv-morpheus/Morpheus, pull requests merged in 2023-12, with the labels that each got.

#1398 Fixing the hammah and phishing validation pipelines
  models/datasets/validation-data/phishing-email-validation-data.jsonlines
  morpheus.code-workspace
  morpheus/cli/commands.py
  scripts/validation/val-run-pipeline.sh
  tests/benchmarks/test_bench_e2e_pipelines.py
  tests/test_phishing.py
  tests/test_phishing_kafka.py
Labels: bug, non-breaking

#1406 Cloud deployment guide fixes
  docs/source/cloud_deployment_guide.md
Labels: non-breaking, doc

#1408 Convert `models/ransomware-models/ransomw-model-short-rf-20220126.sav` to LFS
  models/ransomware-models/ransomw-model-short-rf-20220126.sav
Labels: bug, non-breaking

#1412 [HOTFIX] Morpheus v23.11.01
  CHANGELOG.md
  docs/source/cloud_deployment_guide.md
  models/ransomware-models/ransomw-model-short-rf-20220126.sav
Labels: ! - Hotfix, ! - Release

#1414 Add benchmark for completion pipeline
  examples/llm/completion/pipeline.py
  examples/llm/completion/run.py
  tests/benchmarks/README.md
  tests/benchmarks/conftest.py
  tests/benchmarks/test_bench_completion_pipeline.py
  tests/conftest.py
  tests/llm/conftest.py
  tests/llm/test_agents_simple_pipe.py
  tests/tests_data/countries.csv
Labels: non-breaking, improvement

#1429 Fixes to modular DFP examples and benchmarks
  docs/source/developer_guide/guides/10_modular_pipeline_digital_fingerprinting.md
  examples/digital_fingerprinting/production/morpheus/benchmarks/README.md
  examples/digital_fingerprinting/production/morpheus/benchmarks/benchmark_conf_generator.py
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_payload_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_payload_load_train_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_payload_load_training.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_payload_lti.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_payload_training.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_streaming_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_streaming_lti.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_streaming_training.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_payload_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_payload_load_train_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_payload_lti.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_payload_only_load.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_payload_training.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_streaming_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_streaming_lti.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_streaming_only_load.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_streaming_payload.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_streaming_training.json
  examples/digital_fingerprinting/production/morpheus/dfp_integrated_training_batch_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_integrated_training_streaming_pipeline.py
Labels: bug, non-breaking, dfp

#1434 Document incompatible mlflow models issue
  docs/source/extra_info/troubleshooting.md
Labels: non-breaking, doc

#1421 Add benchmarks for stand-alone RAG & vdb upload pipelines
  tests/_utils/milvus.py
  tests/benchmarks/README.md
  tests/benchmarks/conftest.py
  tests/benchmarks/test_bench_completion_pipeline.py
  tests/benchmarks/test_bench_rag_standalone_pipeline.py
  tests/benchmarks/test_bench_vdb_upload_pipeline.py
  tests/llm/test_rag_standalone_pipe.py
Labels: non-breaking, improvement

#1437 Update phishing-model-card.md
  models/model-cards/phishing-model-card.md
Labels: non-breaking, doc

#1438 Update gnn-fsi-model-card.md
  models/model-cards/gnn-fsi-model-card.md
Labels: non-breaking, doc

#1439 Update abp-model-card.md
  models/model-cards/abp-model-card.md
Labels: non-breaking, doc

#1436 Improve camouflage startup issues
  tests/conftest.py
Labels: bug, non-breaking

#1444 Optionally skip ci based on a label in the pr
  .github/workflows/pull_request.yml
Labels: non-breaking, improvement

#1443 Refactor verification of optional dependencies
  morpheus/controllers/elasticsearch_controller.py
  morpheus/controllers/rss_controller.py
  morpheus/llm/services/nemo_llm_service.py
  morpheus/llm/services/openai_chat_service.py
  morpheus/service/vdb/milvus_vector_db_service.py
  morpheus/stages/input/databricks_deltalake_source_stage.py
  morpheus/stages/output/write_to_databricks_deltalake_stage.py
  morpheus/utils/verify_dependencies.py
Labels: non-breaking, improvement

#1445 Add a --manual_seed flag to the CLI
  morpheus/cli/commands.py
  tests/test_cli.py
Labels: non-breaking, improvement

#1441 Use dependencies.yaml as source-of-truth for environment files.
  .devcontainer/opt/morpheus/bin/post-attach-command.sh
  .github/workflows/ci_pipe.yml
  .github/workflows/pr.yaml
  .gitmodules
  .pre-commit-config.yaml
  ci/check_style.sh
  ci/conda/recipes/python-dbg/meta.yaml
  ci/release/update-version.sh
  ci/scripts/copyright.py
  ci/scripts/github/build.sh
  ci/scripts/github/checks.sh
  ci/scripts/github/common.sh
  ci/scripts/github/docs.sh
  ci/scripts/github/test.sh
  ci/scripts/run_ci_local.sh
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/dev_cuda-118_arch-x86_64.yaml
  dependencies.yaml
Labels: non-breaking, improvement

#1440 Updating the workspace settings to remove deprecated python options
  morpheus.code-workspace
Labels: bug, non-breaking
