Repository nv-morpheus/Morpheus, pull requests merged in 2023-06, with the labels that each got.

#966 Fix build issues & tests
  docker/Dockerfile
  docker/conda/environments/cuda11.8_dev.yml
  tests/test_downloader.py
Labels: bug, non-breaking, 3 - Ready for Review

#969 Update .bashrc in container to activate morpheus conda environment
  docker/Dockerfile
Labels: bug, non-breaking, 3 - Ready for Review

#988 Install pytest-kafka via pip/pypi
  .devcontainer/bin/dev-pytest-kafka-install
  .github/workflows/pull_request.yml
  ci/runner/Dockerfile
  ci/scripts/download_kafka.py
  ci/scripts/run_ci_local.sh
  docker/conda/environments/cuda11.8_dev.yml
  docker/conda/environments/requirements.txt
  morpheus.code-workspace
  pyproject.toml
  scripts/validation/kafka_testing.md
  tests/conftest.py
Labels: non-breaking, improvement, 3 - Ready for Review

#981 Remove duplicate log message in output when using pre-allocation
  morpheus/pipeline/preallocator_mixin.py
  morpheus/stages/input/file_source_stage.py
Labels: bug, non-breaking, 3 - Ready for Review

#978 DFP MultiFileSource optionally poll for file updates
  docs/source/developer_guide/guides/5_digital_fingerprinting.md
  docs/source/developer_guide/guides/6_digital_fingerprinting_reference.md
  examples/digital_fingerprinting/production/README.md
  examples/digital_fingerprinting/production/morpheus/dfp/stages/multi_file_source.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_duo_pipeline.py
  morpheus/cli/run.py
  pyproject.toml
  tests/examples/digital_fingerprinting/test_multifile_source.py
Labels: non-breaking, feature request, 3 - Ready for Review

#985 Warn and cast to cudf, when the C++ impl for MessageMeta receives a pandas DF
  ci/scripts/cpp_checks.sh
  morpheus/_lib/src/messages/meta.cpp
  morpheus/modules/from_control_message.py
  tests/modules/test_to_control_message.py
  tests/test_message_meta.py
  tests/utils/dataset_manager.py
Labels: bug, non-breaking, 3 - Ready for Review

#983 Fix logging of wrong feature_columns in CLI and exception in auto-complete
  docs/source/cloud_deployment_guide.md
  examples/abp_nvsmi_detection/README.md
  morpheus/cli/commands.py
  scripts/validation/val-run-pipeline.sh
  tests/test_cli.py
Labels: bug, breaking, 3 - Ready for Review

#990 Fix "No module named 'versioneer'" error
  setup.py
Labels: bug, non-breaking

#992 Document how to build the examples
  docs/source/developer_guide/guides.md
  docs/source/developer_guide/guides/1_simple_python_stage.md
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/developer_guide/guides/3_simple_cpp_stage.md
  docs/source/developer_guide/guides/4_source_cpp_stage.md
Labels: non-breaking, doc, 3 - Ready for Review, Priority 2

#998 Fixing build with MRC breaking changes
  morpheus/_lib/include/morpheus/modules/data_loader_module.hpp
  morpheus/_lib/src/modules/data_loader_module.cpp
  morpheus/_lib/tests/modules/test_data_loader_module.cpp
Labels: bug, non-breaking

#997 Use cuda-toolkit in release container build
  ci/conda/recipes/morpheus/meta.yaml
Labels: bug, non-breaking, 3 - Ready for Review

#1007 Use size_t for element counts & byte sizes
  morpheus/_lib/include/morpheus/objects/dev_mem_info.hpp
  morpheus/_lib/include/morpheus/objects/rmm_tensor.hpp
  morpheus/_lib/include/morpheus/objects/tensor.hpp
  morpheus/_lib/include/morpheus/objects/tensor_object.hpp
  morpheus/_lib/include/morpheus/types.hpp
  morpheus/_lib/include/morpheus/utilities/tensor_util.hpp
  morpheus/_lib/src/objects/dev_mem_info.cpp
  morpheus/_lib/src/objects/rmm_tensor.cpp
  morpheus/_lib/src/objects/tensor.cpp
  morpheus/_lib/src/utilities/cupy_util.cpp
  morpheus/_lib/src/utilities/matx_util.cu
  morpheus/_lib/tests/CMakeLists.txt
  morpheus/_lib/tests/test_cuda.cu
  morpheus/_lib/tests/test_dev_mem_info.cpp
  tests/test_tensor_memory.py
Labels: bug, breaking, 3 - Ready for Review, Priority 1

#1006 DFP Model Card ++
  models/model-cards/dfp-model-card.md
Labels: non-breaking, doc, 5 - Ready to Merge

#1002 Bring forward some CVE fixes from 23.03 release
  ci/conda/recipes/morpheus/meta.yaml
  docker/Dockerfile
  docker/conda/environments/cuda11.8_dev.yml
  docker/conda/environments/cuda11.8_examples.yml
  models/mlflow/docker/Dockerfile
  models/mlflow/docker/conda/mlflow-env.yml
Labels: dependencies, non-breaking, improvement, 3 - Ready for Review, Priority 0

#1003 Fix pybind11 link errors
  morpheus/_lib/cmake/libmorpheus.cmake
Labels: bug, non-breaking

#1014 Model card ++ for ABP, Phishing, Root cause analysis
  models/model-cards/abp-model-card.md
  models/model-cards/phishing-model-card.md
  models/model-cards/root-cause-analysis-model-card.md
Labels: non-breaking, improvement, 5 - Ready to Merge, Data Science

#1010 GNN FSI modelcard++
  models/model-cards/gnn-fsi-model-card.md
Labels: non-breaking, doc, 5 - Ready to Merge
