Repository nv-morpheus/Morpheus, pull requests merged in 2023-01, with the labels that each got.

#535 Add Morpheus devcontainer
  .devcontainer/Dockerfile
  .devcontainer/README.md
  .devcontainer/bin/dev-kafka-logs
  .devcontainer/bin/dev-kafka-produce
  .devcontainer/bin/dev-kafka-start
  .devcontainer/bin/dev-kafka-stop
  .devcontainer/bin/dev-triton-start
  .devcontainer/bin/dev-triton-stop
  .devcontainer/bin/setup-morpheus-env
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/init.sh
  morpheus.code-workspace
Labels: non-breaking, improvement

#573 Add a glossary to docs
  docs/source/extra_info/glossary.md
  docs/source/index.rst
Labels: non-breaking, doc, 3 - Ready for Review

#581 Document DFP output fields
  docs/source/developer_guide/guides/5_digital_fingerprinting.md
Labels: non-breaking, doc, 3 - Ready for Review

#590 Fix spelling mistakes & bad copy/paste
  docs/source/developer_guide/guides/2_real_world_phishing.md
Labels: non-breaking, doc, 3 - Ready for Review

#574 Misc updates for README.md
  examples/abp_nvsmi_detection/README.md
  examples/gnn_fraud_detection_pipeline/README.md
  examples/log_parsing/README.md
  examples/nlp_si_detection/README.md
  examples/ransomware_detection/README.md
  examples/root_cause_analysis/README.md
Labels: non-breaking, doc, 3 - Ready for Review

#596 Typo(fix): missing equal operator in `--load_model`
  docs/source/developer_guide/guides/2_real_world_phishing.md
Labels: non-breaking, doc, 3 - Ready for Review

#598 Ensure Kafka & Triton deps are documented when used
  .gitignore
  .tmp/.gitkeep
  docs/source/basics/building_a_pipeline.md
  docs/source/basics/building_a_pipeline.rst
  docs/source/examples.md
  docs/source/examples/basic_usage/README.md
  docs/source/examples/basic_usage/img
  docs/source/examples/index.rst
  docs/source/img/monitor_throughput.png
  docs/source/img/multi_monitor_throughput.png
  docs/source/img/nlp_kitchen_sink.png
  docs/source/img/remove_fields_from_json_objects.png
  docs/source/img/simple_identity.png
  examples/basic_usage/README.md
  examples/basic_usage/img/simple_identity.png
  scripts/validation/kafka_testing.md
Labels: non-breaking, doc, 3 - Ready for Review

#585 Removed outdated comments
  examples/abp_pcap_detection/run.py
  examples/gnn_fraud_detection_pipeline/run.py
  examples/log_parsing/run.py
  examples/ransomware_detection/run.py
  examples/sid_visualization/run.py
  morpheus/stages/postprocess/serialize_stage.py
  morpheus/stages/preprocess/deserialize_stage.py
Labels: non-breaking, doc, 3 - Ready for Review

#592 Stated explicitly regarding helm chart names
  docs/source/cloud_deployment_guide.md
Labels: non-breaking, doc, 3 - Ready for Review

#605 Update DFPMLFlowModelWriterStage to no longer save mean and std metrics
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_mlflow_model_writer.py
Labels: non-breaking, improvement, 3 - Ready for Review

#612 Model and dataset documentation update
  README.md
  docs/source/getting_started.md
  docs/source/index.rst
  docs/source/models_and_datasets.md
Labels: non-breaking, doc, 3 - Ready for Review

#602 Remove unused `cudf_kwargs` constructor argument from FileSourceStage & NLPVizFileSource
  docs/source/developer_guide/guides/1_simple_python_stage.md
  examples/abp_nvsmi_detection/README.md
  examples/gnn_fraud_detection_pipeline/README.md
  examples/nlp_si_detection/README.md
  examples/root_cause_analysis/README.md
  examples/sid_visualization/README.md
  examples/sid_visualization/run.py
  morpheus/stages/input/file_source_stage.py
Labels: bug, breaking, 3 - Ready for Review

#597 Log parsing model training for split logs and smaller models
  models/training-tuning-scripts/log-parsing-models/log-parsing-training.ipynb
Labels: non-breaking, improvement, 3 - Ready for Review

#579 Add validation set option to DFP training
  docs/source/developer_guide/guides/5_digital_fingerprinting.md
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_training.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_duo_pipeline.py
Labels: non-breaking, improvement, 3 - Ready for Review

#621 Update meta.yaml
  ci/conda/recipes/morpheus/meta.yaml
Labels: bug, dependencies, non-breaking, 3 - Ready for Review, Priority 0

#608 Fix production DFP pipeline run commands
  docs/source/developer_guide/guides/5_digital_fingerprinting.md
  examples/digital_fingerprinting/production/README.md
Labels: non-breaking, doc, 3 - Ready for Review

#633 Updated gitignore
  .gitignore
  examples/digital_fingerprinting/production/morpheus/dfp_detections_azure.csv
  examples/digital_fingerprinting/production/morpheus/dfp_detections_duo.csv
Labels: bug, non-breaking, 3 - Ready for Review

#634 Updating the CI image to use Driver 520
  .github/workflows/ci_pipe.yml
  .github/workflows/pull_request.yml
  ci/runner/Dockerfile
  ci/runner/README.md
Labels: non-breaking, improvement

#629 Add GitHub CLI support to devcontainer
  .devcontainer/bin/setup-morpheus-env
  .devcontainer/devcontainer.json
  .devcontainer/init.sh
Labels: enhancement, non-breaking, feature request

#635 Add md & rst files to copyright.py checks and Fix copyright year in Sphinx footer
  ci/conda/channel/README.md
  ci/scripts/copyright.py
  docs/README.md
  docs/source/basics/overview.rst
  docs/source/cloud_deployment_guide.md
  docs/source/conf.py
  docs/source/developer_guide/architecture.md
  docs/source/developer_guide/contributing.md
  docs/source/developer_guide/guides.md
  docs/source/developer_guide/guides/1_simple_python_stage.md
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/developer_guide/guides/3_simple_cpp_stage.md
  docs/source/developer_guide/guides/4_source_cpp_stage.md
  docs/source/developer_guide/guides/5_digital_fingerprinting.md
  docs/source/developer_guide/guides/index.rst
  docs/source/examples.md
  docs/source/examples/index.rst
  docs/source/extra_info/glossary.md
  docs/source/extra_info/known_issues.md
  docs/source/extra_info/performance.md
  docs/source/extra_info/troubleshooting.md
  docs/source/getting_started.md
  docs/source/index.rst
  docs/source/models_and_datasets.md
  docs/source/py_api.rst
  examples/README.md
  examples/abp_nvsmi_detection/README.md
  examples/abp_pcap_detection/README.md
  examples/developer_guide/2_2_rabbitmq/README.md
  examples/developer_guide/4_rabbitmq_cpp_stage/README.md
  examples/digital_fingerprinting/README.md
  examples/digital_fingerprinting/production/README.md
  examples/digital_fingerprinting/starter/README.md
  examples/digital_fingerprinting/visualization/README.md
  examples/gnn_fraud_detection_pipeline/README.md
  examples/log_parsing/README.md
  examples/nlp_si_detection/README.md
  examples/ransomware_detection/README.md
  examples/root_cause_analysis/README.md
  models/README.md
  models/datasets/README.md
  models/mlflow/README.md
  models/training-tuning-scripts/fraud-detection-models/README.md
  models/triton-model-repo/README.md
  models/triton-model-repo/phishing-bert-trt/1/README.md
  models/triton-model-repo/sid-minibert-trt/1/README.md
  morpheus/_lib/README.md
  scripts/validation/kafka_testing.md
  tests/benchmarks/README.md
Labels: non-breaking, doc, 3 - Ready for Review

#628 Add missing docstrings
  examples/digital_fingerprinting/production/morpheus/dfp_azure_inference.ipynb
  examples/digital_fingerprinting/production/morpheus/dfp_azure_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_training.ipynb
  examples/digital_fingerprinting/production/morpheus/dfp_duo_inference.ipynb
  examples/digital_fingerprinting/production/morpheus/dfp_duo_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_duo_training.ipynb
  examples/digital_fingerprinting/visualization/dfp_viz_azure_pipeline.py
  examples/digital_fingerprinting/visualization/dfp_viz_duo_pipeline.py
  morpheus/_lib/include/morpheus/stages/filter_detection.hpp
  morpheus/cli/click_completion_tools.py
  morpheus/cli/commands.py
  morpheus/config.py
  morpheus/messages/message_base.py
  morpheus/messages/multi_ae_message.py
  morpheus/messages/multi_message.py
  morpheus/messages/multi_response_message.py
  morpheus/pipeline/linear_pipeline.py
  morpheus/pipeline/pipeline.py
  morpheus/pipeline/receiver.py
  morpheus/pipeline/source_stage.py
  morpheus/pipeline/stream_wrapper.py
  morpheus/stages/general/linear_modules_stage.py
  morpheus/stages/general/monitor_stage.py
  morpheus/stages/inference/inference_stage.py
  morpheus/stages/inference/triton_inference_stage.py
  morpheus/stages/input/autoencoder_source_stage.py
  morpheus/stages/input/azure_source_stage.py
  morpheus/stages/input/cloud_trail_source_stage.py
  morpheus/stages/input/duo_source_stage.py
  morpheus/stages/input/kafka_source_stage.py
  morpheus/stages/postprocess/generate_viz_frames_stage.py
  morpheus/stages/postprocess/timeseries_stage.py
  morpheus/utils/atomic_integer.py
  morpheus/utils/column_info.py
  morpheus/utils/compare_df.py
  morpheus/utils/directory_watcher.py
  morpheus/utils/logger.py
  morpheus/utils/producer_consumer_queue.py
  morpheus/utils/type_utils.py
  pyproject.toml
  tests/test_column_info.py
  tests/test_inference_stage.py
Labels: breaking, doc, 3 - Ready for Review

#637 Split up the DFP guide
  docs/source/developer_guide/guides.md
  docs/source/developer_guide/guides/5_digital_fingerprinting.md
  docs/source/developer_guide/guides/6_digital_fingerprinting_reference.md
  docs/source/developer_guide/guides/index.rst
Labels: non-breaking, doc, 3 - Ready for Review

#640 Updating Code of Conduct
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_request_correction.yml
  .github/ISSUE_TEMPLATE/documentation_request_new.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  CODE_OF_CONDUCT.md
  docs/source/developer_guide/contributing.md
Labels: non-breaking, doc

#642 Update NGC version references
  docs/source/cloud_deployment_guide.md
  examples/digital_fingerprinting/production/Dockerfile
  examples/digital_fingerprinting/starter/README.md
  models/mlflow/README.md
Labels: non-breaking, doc, 3 - Ready for Review, Priority 0

#645 Update torch to 1.13.1+cu116
  docker/conda/environments/requirements.txt
  models/training-tuning-scripts/phishing-models/requirements.txt
  models/training-tuning-scripts/root-cause-models/requirements.txt
  models/validation-inference-scripts/dfp-models/requirements.txt
  models/validation-inference-scripts/phishing-models/requirements.txt
  models/validation-inference-scripts/root-cause-models/requirements.txt
  setup.py
Labels: dependencies, non-breaking, improvement, 3 - Ready for Review

#652 23.01 doc fixes
  README.md
  docs/README.md
  docs/source/getting_started.md
  examples/sid_visualization/README.md
Labels: non-breaking, doc, 3 - Ready for Review

#653 Fix docstring for InferenceMemoryAE
  morpheus/messages/multi_inference_message.py
Labels: non-breaking, doc, 3 - Ready for Review

#648 Update protobuf to 3.20.2
  docker/conda/environments/cuda11.5_dev.yml
  docker/conda/environments/requirements.txt
Labels: dependencies, non-breaking, improvement, 3 - Ready for Review
