Repository nv-morpheus/Morpheus, pull requests merged in 2023-09, with the labels that each got.

#1154 Command line examples for module-based DFP pipelines
  docs/source/developer_guide/guides/10_modular_pipeline_digital_fingerprinting.md
  examples/digital_fingerprinting/production/README.md
  examples/digital_fingerprinting/production/morpheus/benchmarks/README.md
  examples/digital_fingerprinting/production/morpheus/benchmarks/conftest.py
  examples/digital_fingerprinting/production/morpheus/benchmarks/resource/pipelines_conf.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_payload_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_payload_load_train_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_payload_load_training.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_payload_lti.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_payload_lti_s3.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_payload_training.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_streaming_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_streaming_lti.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_streaming_training.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_payload_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_payload_load_train_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_payload_lti.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_payload_only_load.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_payload_training.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_streaming_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_streaming_lti.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_streaming_only_load.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_streaming_payload.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_streaming_training.json
  examples/digital_fingerprinting/production/morpheus/dfp/utils/dfp_arg_parser.py
  tests/test_cli.py
Labels: non-breaking, doc, 3 - Ready for Review

#1149 RSS Source Stage for Reading RSS Feeds
  docker/conda/environments/cuda11.8_dev.yml
  morpheus/cli/commands.py
  morpheus/controllers/__init__.py
  morpheus/controllers/rss_controller.py
  morpheus/stages/input/rss_source_stage.py
  tests/controllers/test_rss_controller.py
  tests/test_rss_source_stage_pipe.py
  tests/tests_data/rss_feed_atom.xml
Labels: non-breaking, feature request, 3 - Ready for Review

#1123 Eliminate redundant code blocks in modules and stages
  examples/digital_fingerprinting/production/morpheus/dfp/modules/__init__.py
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_inference.py
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_monitor.py
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_training.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_file_batcher_stage.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_file_to_df.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_mlflow_model_writer.py
  examples/digital_fingerprinting/production/morpheus/dfp/utils/dfp_arg_parser.py
  examples/digital_fingerprinting/production/morpheus/dfp/utils/model_cache.py
  examples/ransomware_detection/common/feature_extractor.py
  morpheus/controllers/file_to_df_controller.py
  morpheus/controllers/filter_detections_controller.py
  morpheus/controllers/mlflow_model_writer_controller.py
  morpheus/controllers/monitor_controller.py
  morpheus/controllers/serialize_controller.py
  morpheus/controllers/write_to_file_controller.py
  morpheus/loaders/file_to_df_loader.py
  morpheus/modules/file_to_df.py
  morpheus/modules/filter_detections.py
  morpheus/modules/mlflow_model_writer.py
  morpheus/modules/serialize.py
  morpheus/modules/write_to_file.py
  morpheus/stages/general/monitor_stage.py
  morpheus/stages/output/write_to_file_stage.py
  morpheus/stages/postprocess/filter_detections_stage.py
  morpheus/stages/postprocess/serialize_stage.py
  morpheus/utils/column_info.py
  morpheus/utils/monitor_utils.py
  morpheus/utils/schema_transforms.py
  tests/examples/digital_fingerprinting/test_dfp_file_to_df.py
  tests/examples/digital_fingerprinting/test_dfp_mlflow_model_writer.py
  tests/test_cli.py
  tests/test_filter_detections_stage.py
  tests/test_monitor_stage.py
  tests/test_serialize_stage.py
  tests/utils/nvt/test_schema_converters.py
Labels: non-breaking, improvement, 3 - Ready for Review

#1168 GitHub Project Automation and Infra Updates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/label-external-issues.yml
  .github/workflows/project_automation_set_in_progress.yml
  .github/workflows/project_automation_set_in_review.yml
  .github/workflows/project_automation_set_roadmap.yml
  .github/workflows/project_automation_sync_pr_issues.yml
  .github/workflows/project_automation_track_pr_dates.yml
Labels: non-breaking, feature request

#1188 Update feature length for test_abp_fil_e2e benchmark
  tests/benchmarks/e2e_test_configs.json
Labels: bug, non-breaking, 3 - Ready for Review, Priority 2

#1195 Adopt updated camouflage-server & fix test_dfp_mlflow_model_writer
  .github/workflows/pull_request.yml
  ci/runner/Dockerfile
  ci/scripts/github/common.sh
  ci/scripts/run_ci_local.sh
  docker/Dockerfile
  docker/conda/environments/cuda11.8_dev.yml
  docs/source/developer_guide/contributing.md
  scripts/validation/kafka_testing.md
Labels: non-breaking, improvement, 3 - Ready for Review, Priority 2

#1200 Add `review_requested` as a trigger & increased timeouts for camouflage
  .github/workflows/project_automation_set_in_review.yml
  tests/conftest.py
Labels: bug, non-breaking

#1155 Update dfp_training stage to support ControlMessages or MultiDFPMessages
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_training.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_training.py
  models/training-tuning-scripts/dfp-models/hammah-20211017-script.py
  morpheus/controllers/mlflow_model_writer_controller.py
  morpheus/models/dfencoder/__init__.py
  morpheus/models/dfencoder/autoencoder.py
  morpheus/models/dfencoder/dataloader.py
  morpheus/stages/preprocess/train_ae_stage.py
  tests/dfencoder/test_autoencoder.py
  tests/dfencoder/test_dfencoder_distributed_e2e.py
  tests/dfencoder/test_dfencoder_e2e.py
  tests/examples/digital_fingerprinting/test_dfp_mlflow_model_writer.py
  tests/examples/digital_fingerprinting/test_dfp_training.py
Labels: non-breaking, improvement

#1161 Update Downloader utility class to use static dask cluster
  docs/source/developer_guide/guides/10_modular_pipeline_digital_fingerprinting.md
  morpheus/utils/downloader.py
  tests/examples/digital_fingerprinting/test_dfp_file_to_df.py
  tests/test_downloader.py
Labels: bug, non-breaking

#1212 Fix Kafka offset checking test
  tests/_utils/kafka.py
  tests/test_kafka_source_stage_pipe.py
Labels: bug, non-breaking

#1219 CI test stage no longer depends on build stage
  .github/workflows/ci_pipe.yml
Labels: non-breaking, feature request

#1216 Update DFP training model_kwargs
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_training_pipe.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_training.py
Labels: bug, non-breaking

#1205 ABP PCAP detection readme update
  examples/abp_pcap_detection/README.md
Labels: non-breaking, doc

#1169 KafkaSourceStage OAuth Callback Support
  morpheus/_lib/include/morpheus/stages/kafka_source.hpp
  morpheus/_lib/src/stages/kafka_source.cpp
  morpheus/_lib/stages/__init__.pyi
  morpheus/_lib/stages/module.cpp
Labels: non-breaking, feature request

#1193 Add development deps to dependencies.yaml
  dependencies.yaml
Labels: non-breaking, improvement
