Repository nv-morpheus/Morpheus, pull requests merged in 2024-11, with the labels that each got.

#2031 Fix for duplicate row IDs in `log_parsing` output
  examples/log_parsing/postprocessing.py
  python/morpheus/morpheus/_lib/include/morpheus/objects/table_info.hpp
  python/morpheus/morpheus/_lib/include/morpheus/stages/deserialize.hpp
  tests/examples/log_parsing/test_postprocessing.py
Labels: bug, non-breaking

#1958 Benchmark updates/fixes
  conda/environments/all_cuda-125_arch-x86_64.yaml
  conda/environments/dev_cuda-125_arch-x86_64.yaml
  dependencies.yaml
  tests/benchmarks/README.md
  tests/benchmarks/e2e_test_configs.json
  tests/benchmarks/test_bench_completion_pipeline.py
  tests/benchmarks/test_bench_e2e_pipelines.py
  tests/benchmarks/test_bench_rag_standalone_pipeline.py
  tests/benchmarks/test_bench_vdb_upload_pipeline.py
Labels: bug, non-breaking

#2032 Copy data files needed by root_cause_analysis to examples/data
  examples/data/root-cause-validation-data-input.jsonlines
  examples/root_cause_analysis/README.md
Labels: bug, non-breaking

#2027 Add known issue for dask shutdown
  docs/source/extra_info/known_issues.md
  examples/ransomware_detection/README.md
Labels: non-breaking, doc

#2036 Model updates and cleanup following upgrade to to triton 24.09
  models/README.md
  models/ransomware-models/ransomw-model-long-rf/checkpoint.tl
  models/ransomware-models/ransomw-model-medium-rf/checkpoint.tl
  models/triton-model-repo/phishing-bert-trt/1/README.md
  models/triton-model-repo/phishing-bert-trt/config.pbtxt
  models/triton-model-repo/sid-minibert-trt/1/README.md
  models/triton-model-repo/sid-minibert-trt/config.pbtxt
Labels: bug, non-breaking

#2039 Pin boto3 and s3fs to compatible versions to resolve access denied errors
  conda/environments/all_cuda-125_arch-x86_64.yaml
  conda/environments/examples_cuda-125_arch-x86_64.yaml
  dependencies.yaml
  examples/digital_fingerprinting/production/conda/environments/dfp_example_cuda-125_arch-x86_64.yaml
Labels: bug, dependencies, non-breaking, conda-build

#2041 Various Lint fixes
  ci/iwyu/mappings.imp
  examples/developer_guide/3_simple_cpp_stage/src/simple_cpp_stage/_lib/pass_thru.hpp
  python/morpheus/morpheus/_lib/include/morpheus/objects/memory_descriptor.hpp
  python/morpheus/morpheus/_lib/include/morpheus/utilities/json_types.hpp
  python/morpheus/morpheus/_lib/include/morpheus/utilities/stage_util.hpp
  python/morpheus/morpheus/_lib/src/io/deserializers.cpp
  python/morpheus/morpheus/_lib/src/objects/dtype.cpp
  python/morpheus/morpheus/_lib/src/objects/mutable_table_ctx_mgr.cpp
  python/morpheus/morpheus/_lib/src/objects/rmm_tensor.cpp
  python/morpheus/morpheus/_lib/src/objects/tensor.cpp
  python/morpheus/morpheus/_lib/src/utilities/table_util.cpp
  python/morpheus/morpheus/_lib/tests/messages/test_message_meta.cpp
  python/morpheus/morpheus/_lib/tests/test_deserializers.cpp
  python/morpheus/morpheus/_lib/tests/test_dev_mem_info.cpp
  python/morpheus_llm/morpheus_llm/_lib/src/llm/llm_engine.cpp
  python/morpheus_llm/morpheus_llm/_lib/src/llm/llm_node_runner.cpp
  python/morpheus_llm/morpheus_llm/_lib/tests/llm/test_llm_task_handler_runner.cpp
  tests/_utils/__init__.py
  tests/scripts/data/dfp_old_namespace_data.py
  tests/scripts/data/llm_old_namespace_data.py
Labels: bug, non-breaking

#2052 Update DFP class and file paths
  docs/source/developer_guide/guides/10_modular_pipeline_digital_fingerprinting.md
  docs/source/developer_guide/guides/6_digital_fingerprinting_reference.md
  docs/source/extra_info/troubleshooting.md
Labels: non-breaking, doc

#2059 Document location of third party source repository
  ci/release/update-version.sh
  docker/Dockerfile
  thirdparty/README.md
Labels: non-breaking, doc

#2040 Update `compare_df` to display the diff report on column differences not just rows
  python/morpheus/morpheus/utils/compare_df.py
  scripts/compare_data_files.py
Labels: bug, non-breaking

#2050 Update DFP integrated pipeline to use MRC `Router` node
  docs/source/developer_guide/guides/10_modular_pipeline_digital_fingerprinting.md
  docs/source/developer_guide/guides/6_digital_fingerprinting_reference.md
  docs/source/extra_info/troubleshooting.md
  examples/digital_fingerprinting/production/dfp_integrated_training_batch_pipeline.py
  python/morpheus_dfp/morpheus_dfp/modules/dfp_deployment.py
  python/morpheus_dfp/morpheus_dfp/modules/dfp_inference_pipe.py
  python/morpheus_dfp/morpheus_dfp/modules/dfp_preproc.py
  python/morpheus_dfp/morpheus_dfp/modules/dfp_training_pipe.py
  python/morpheus_dfp/morpheus_dfp/utils/dfp_arg_parser.py
Labels: non-breaking, feature request

#2054 Avoid compiler warnings
  examples/developer_guide/3_simple_cpp_stage/CMakeLists.txt
  examples/developer_guide/4_rabbitmq_cpp_stage/CMakeLists.txt
  python/morpheus/morpheus/_lib/cmake/libmorpheus.cmake
  python/morpheus_llm/morpheus_llm/_lib/cmake/libmorpheus_llm.cmake
Labels: non-breaking, improvement

#2067 Pin mlflow version to avoid breaking changes in v2.18
  conda/environments/all_cuda-125_arch-x86_64.yaml
  conda/environments/dev_cuda-125_arch-x86_64.yaml
  conda/environments/examples_cuda-125_arch-x86_64.yaml
  conda/environments/runtime_cuda-125_arch-x86_64.yaml
  dependencies.yaml
Labels: bug, non-breaking

#2061 Allow running something other than bash when using docker scripts
  docker/run_container_dev.sh
  docker/run_container_release.sh
Labels: non-breaking, improvement

#1937 Add parquet support to write_to_file_stage.py
  python/morpheus/morpheus/controllers/write_to_file_controller.py
  tests/morpheus/stages/test_write_to_file_stage_pipe.py
Labels: non-breaking, improvement

#2049 Misc cleanups to example pipelines
  docs/source/developer_guide/guides/2_real_world_phishing.md
  examples/abp_nvsmi_detection/README.md
  examples/abp_pcap_detection/README.md
  examples/abp_pcap_detection/run.py
  examples/cpu_only/README.md
  examples/cpu_only/run.py
  examples/developer_guide/2_1_real_world_phishing/run.py
  examples/gnn_fraud_detection_pipeline/README.md
  examples/gnn_fraud_detection_pipeline/run.py
  examples/log_parsing/README.md
  examples/log_parsing/run.py
  examples/nlp_si_detection/README.md
  examples/nlp_si_detection/run.sh
  examples/ransomware_detection/README.md
  examples/ransomware_detection/run.py
  examples/root_cause_analysis/README.md
  python/morpheus/morpheus/config.py
  tests/morpheus/test_config.py
Labels: non-breaking, improvement

#1950 Improve `SharedProcessPool` tests performance
  tests/morpheus/stages/test_multi_processing_stage.py
  tests/morpheus/utils/test_shared_process_pool.py
Labels: non-breaking, improvement

#2064 Execute CI on the main branch
  .github/workflows/pr.yaml
  ci/conda/recipes/morpheus-libs/meta.yaml
  ci/conda/recipes/morpheus/meta.yaml
Labels: bug, non-breaking, conda-build
