Repository nv-morpheus/Morpheus, pull requests merged in 2024-08, with the labels that each got.

#1731 Batch incoming DOCA raw packet data
  examples/doca/README.md
  examples/doca/run_udp_convert.py
  examples/doca/run_udp_raw.py
  examples/doca/vdb_realtime/sender/send.py
  examples/doca/vdb_realtime/vdb.py
  morpheus/_lib/doca/CMakeLists.txt
  morpheus/_lib/doca/__init__.pyi
  morpheus/_lib/doca/include/morpheus/doca/common.hpp
  morpheus/_lib/doca/include/morpheus/doca/doca_convert_stage.hpp
  morpheus/_lib/doca/include/morpheus/doca/doca_kernels.hpp
  morpheus/_lib/doca/include/morpheus/doca/doca_source_stage.hpp
  morpheus/_lib/doca/include/morpheus/doca/packet_data_buffer.hpp
  morpheus/_lib/doca/include/morpheus/doca/packets.hpp
  morpheus/_lib/doca/module.cpp
  morpheus/_lib/doca/src/doca_context.cpp
  morpheus/_lib/doca/src/doca_convert.cpp
  morpheus/_lib/doca/src/doca_convert_kernel.cu
  morpheus/_lib/doca/src/doca_convert_stage.cpp
  morpheus/_lib/doca/src/doca_source_kernel.cu
  morpheus/_lib/doca/src/doca_source_stage.cpp
  morpheus/_lib/doca/src/packet_data_buffer.cpp
  morpheus/stages/doca/doca_convert_stage.py
Labels: non-breaking, improvement

#1830 Remove automock for merlin as we no longer have/use merlin
  docs/source/conf.py
Labels: non-breaking, doc

#1829 Add tests to confirm that a mis-configured MultiPortModulesStage will raise an exception rather than segfaulting
  morpheus/pipeline/pipeline.py
  tests/test_multi_port_pipeline.py
  tests/test_multi_segment.py
Labels: bug, non-breaking

#1831 Improved type-hints for stage and source decorators
  morpheus/pipeline/stage_decorator.py
Labels: bug, non-breaking

#1842 Fix isort config marking `_utils` as known first party
  python/morpheus/setup.cfg
Labels: bug, non-breaking

#1840 Fix usage of the C++ impl of `write_df_to_file`
  python/morpheus/morpheus/io/serializers.py
Labels: bug, non-breaking

#1839 Fix shutdown on Ctrl+C for Python source stages
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/developer_guide/guides/4_source_cpp_stage.md
  examples/developer_guide/2_2_rabbitmq/rabbitmq_source_stage.py
  examples/developer_guide/4_rabbitmq_cpp_stage/src/rabbitmq_cpp_stage/rabbitmq_source_stage.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/multi_file_source.py
  python/morpheus/morpheus/controllers/rss_controller.py
  python/morpheus/morpheus/modules/input/rss_source.py
  python/morpheus/morpheus/pipeline/single_output_source.py
  python/morpheus/morpheus/stages/input/appshield_source_stage.py
  python/morpheus/morpheus/stages/input/arxiv_source.py
  python/morpheus/morpheus/stages/input/autoencoder_source_stage.py
  python/morpheus/morpheus/stages/input/control_message_kafka_source_stage.py
  python/morpheus/morpheus/stages/input/http_client_source_stage.py
  python/morpheus/morpheus/stages/input/http_server_source_stage.py
  python/morpheus/morpheus/stages/input/kafka_source_stage.py
  python/morpheus/morpheus/stages/input/rss_source_stage.py
  python/morpheus/morpheus/utils/directory_watcher.py
Labels: bug, non-breaking

#1843 Update location of morpheus setup and data files in VS settings
  morpheus.code-workspace
Labels: bug, non-breaking

#1854 Move isort settings into pyproject.toml
  ci/scripts/common.sh
  ci/scripts/python_checks.sh
  pyproject.toml
  python/morpheus/setup.cfg
Labels: bug, non-breaking

#1855 Update `isort` settings file path in `fix_all.sh`
  ci/scripts/fix_all.sh
Labels: bug, non-breaking

#1856 Update Kafka DL script to `2.13-3.8.0`
  ci/scripts/download_kafka.py
Labels: bug, non-breaking

#1860 Revert PR_1736 "Always run the PR builder step even if others are cancelled"
  .github/workflows/pr.yaml
Labels: bug, non-breaking

#1861 Replace pdf parsing libs
  .github/workflows/pr.yaml
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/dev_cuda-121_arch-x86_64.yaml
  conda/environments/examples_cuda-121_arch-x86_64.yaml
  dependencies.yaml
  examples/llm/vdb_upload/module/content_extractor_module.py
Labels: non-breaking, feature request, ! - Hotfix

#1863 [RELEASE] Morpheus v24.06.01
  .github/workflows/pr.yaml
  CHANGELOG.md
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/dev_cuda-121_arch-x86_64.yaml
  conda/environments/examples_cuda-121_arch-x86_64.yaml
  dependencies.yaml
  examples/llm/vdb_upload/module/content_extractor_module.py
Labels: ! - Release

#1869 Fix `Unregistered type : mrc::pymrc::coro::BoostFibersMainPyAwaitable` error
  ci/scripts/common.sh
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/dev_cuda-121_arch-x86_64.yaml
  dependencies.yaml
  docs/source/developer_guide/contributing.md
  python/morpheus/morpheus/_lib/stages/__init__.pyi
  python/morpheus/morpheus/_lib/stages/module.cpp
  scripts/validation/val-run-pipeline.sh
Labels: bug, non-breaking

#1859 Run yapf, flake8, isort as part of pre-commit
  .pre-commit-config.yaml
  ci/scripts/fix_all.sh
  ci/scripts/python_checks.sh
  morpheus.code-workspace
  pyproject.toml
  python/morpheus/morpheus/_lib/common/__init__.pyi
  python/morpheus/morpheus/_lib/cudf_helpers/__init__.pyi
  python/morpheus/morpheus/_lib/doca/__init__.pyi
  python/morpheus/morpheus/_lib/messages/__init__.pyi
  python/morpheus/morpheus/_lib/modules/__init__.pyi
  python/morpheus/morpheus/_lib/stages/__init__.pyi
  python/morpheus/setup.cfg
  python/morpheus_llm/morpheus_llm/_lib/llm/__init__.pyi
Labels: non-breaking, improvement

#1865 Remove cloudtrail debug log from autoencoder source stage
  python/morpheus/morpheus/stages/input/autoencoder_source_stage.py
Labels: non-breaking, improvement

#1866 Prefer `len(os.sched_getaffinity(0))` over `os.cpu_count()`
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/developer_guide/guides/6_digital_fingerprinting_reference.md
  examples/abp_pcap_detection/run.py
  examples/developer_guide/2_1_real_world_phishing/run.py
  examples/developer_guide/2_2_rabbitmq/read_simple.py
  examples/developer_guide/2_2_rabbitmq/write_simple.py
  examples/developer_guide/4_rabbitmq_cpp_stage/README.md
  examples/developer_guide/4_rabbitmq_cpp_stage/src/read_simple.py
  examples/developer_guide/4_rabbitmq_cpp_stage/src/write_simple.py
  examples/digital_fingerprinting/production/grafana/run.py
  examples/digital_fingerprinting/production/morpheus/dfp/utils/config_generator.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_duo_pipeline.py
  examples/digital_fingerprinting/production/morpheus/notebooks/dfp_azure_inference.ipynb
  examples/digital_fingerprinting/production/morpheus/notebooks/dfp_azure_training.ipynb
  examples/digital_fingerprinting/production/morpheus/notebooks/dfp_duo_inference.ipynb
  examples/digital_fingerprinting/production/morpheus/notebooks/dfp_duo_training.ipynb
  examples/digital_fingerprinting/starter/run_cloudtrail_dfp.py
  examples/digital_fingerprinting/visualization/dfp_viz_azure_pipeline.py
  examples/digital_fingerprinting/visualization/dfp_viz_duo_pipeline.py
  examples/doca/run_udp_convert.py
  examples/gnn_fraud_detection_pipeline/run.py
  examples/llm/agents/run.py
  examples/llm/completion/run.py
  examples/llm/rag/run.py
  examples/llm/vdb_upload/run.py
  examples/log_parsing/run.py
  examples/ransomware_detection/run.py
  examples/sid_visualization/run.py
  python/morpheus/morpheus/cli/commands.py
  python/morpheus/morpheus/stages/input/http_server_source_stage.py
  python/morpheus/morpheus/stages/output/http_server_sink_stage.py
  tests/common/test_http_server.py
Labels: non-breaking, improvement
