Repository nv-morpheus/Morpheus, pull requests merged in 2024-10, with the labels that each got.

#1911 Build morpheus_llm by default
  CMakeLists.txt
Labels: bug, non-breaking

#1921 Remove debug log in `HttpServerSourceStage` when the queue is empty
  python/morpheus/morpheus/stages/input/http_server_source_stage.py
Labels: non-breaking, feature request

#1929 Remove `SharedProcessPool.terminate()` related tests to avoid stack traces and blocking remote-ci
  tests/utils/test_shared_process_pool.py
Labels: bug, non-breaking

#1927 Ensure that `pytest` is able to run without optional dependencies
  python/morpheus_llm/morpheus_llm/error.py
  python/morpheus_llm/morpheus_llm/llm/nodes/langchain_agent_node.py
  python/morpheus_llm/morpheus_llm/llm/services/nemo_llm_service.py
  python/morpheus_llm/morpheus_llm/llm/services/nvfoundation_llm_service.py
  python/morpheus_llm/morpheus_llm/llm/services/openai_chat_service.py
  python/morpheus_llm/morpheus_llm/service/vdb/faiss_vdb_service.py
  python/morpheus_llm/morpheus_llm/service/vdb/milvus_vector_db_service.py
  tests/benchmarks/conftest.py
  tests/benchmarks/test_bench_agents_simple_pipeline.py
  tests/conftest.py
  tests/llm/conftest.py
  tests/llm/nodes/test_langchain_agent_node.py
  tests/llm/services/conftest.py
  tests/llm/services/test_nvfoundation_llm_service.py
  tests/llm/test_agents_simple_pipe.py
  tests/utils/test_shared_process_pool.py
Labels: bug, non-breaking

#1930 Remove unused pymysql dependency from DFP mlflow container
  examples/digital_fingerprinting/production/.env.sample
  examples/digital_fingerprinting/production/mlflow/Dockerfile
Labels: non-breaking, improvement

#1935 Set lower CPU usage for `test_shared_process_pool.py` to avoid slowing down the test
  tests/utils/test_shared_process_pool.py
Labels: non-breaking, improvement

#1922 Better handle exceptions generated in the `LLMEngine` to not show the `stoul` error
  python/morpheus/morpheus/_lib/include/morpheus/pybind11/json.hpp
  python/morpheus/morpheus/_lib/messages/__init__.pyi
  python/morpheus_llm/morpheus_llm/_lib/include/morpheus_llm/llm/llm_context.hpp
  python/morpheus_llm/morpheus_llm/_lib/include/morpheus_llm/llm/llm_lambda_node.hpp
  python/morpheus_llm/morpheus_llm/_lib/llm/__init__.pyi
  python/morpheus_llm/morpheus_llm/_lib/llm/module.cpp
  python/morpheus_llm/morpheus_llm/_lib/llm/src/py_llm_lambda_node.cpp
  python/morpheus_llm/morpheus_llm/_lib/src/llm/llm_context.cpp
  python/morpheus_llm/morpheus_llm/_lib/tests/llm/test_llm_context.cpp
  python/morpheus_llm/morpheus_llm/_lib/tests/llm/test_llm_engine.cpp
  python/morpheus_llm/morpheus_llm/_lib/tests/llm/test_llm_node.cpp
  python/morpheus_llm/morpheus_llm/_lib/tests/llm/test_llm_node_runner.cpp
  python/morpheus_llm/morpheus_llm/llm/nodes/llm_generate_node.py
  python/morpheus_llm/morpheus_llm/llm/services/llm_service.py
  python/morpheus_llm/morpheus_llm/llm/services/nemo_llm_service.py
  python/morpheus_llm/morpheus_llm/llm/services/nvfoundation_llm_service.py
  python/morpheus_llm/morpheus_llm/llm/services/openai_chat_service.py
  tests/llm/conftest.py
  tests/llm/nodes/test_llm_generate_node.py
  tests/llm/services/test_nemo_llm_client.py
  tests/llm/services/test_nvfoundation_llm_service.py
  tests/llm/services/test_openai_chat_service.py
Labels: bug, non-breaking

#1941 Update cuda version for docker containers
  .devcontainer/cuda12.5-conda/devcontainer.json
  docker/Dockerfile
  docker/build_container.sh
Labels: bug, non-breaking

#1942 Move tests/common to tests/morpheus/common
  examples/ransomware_detection/stages/create_features.py
  examples/ransomware_detection/stages/preprocessing.py
  tests/examples/ransomware_detection/test_create_features.py
  tests/examples/ransomware_detection/test_preprocessing.py
  tests/morpheus/common/test_determine_file_type.py
  tests/morpheus/common/test_fiber_queue.py
  tests/morpheus/common/test_http_server.py
Labels: enhancement, non-breaking, feature request, conda-build

#1946 Script for updating the namespace due to compartmentalization changes
  scripts/data/namespace_update_data.py
  scripts/morpheus_namespace_update.py
Labels: non-breaking, feature request

#1931 Fix dask error in DFP Integrated training pipeline
  python/morpheus/morpheus/controllers/file_to_df_controller.py
  python/morpheus/morpheus/loaders/file_to_df_loader.py
Labels: bug, non-breaking

#1947 Reduce the number of warnings emitted
  .github/workflows/ci_pipe.yml
  examples/gnn_fraud_detection_pipeline/stages/model.py
  examples/llm/common/utils.py
  examples/llm/vdb_upload/langchain.py
  examples/llm/vdb_upload/module/content_extractor_module.py
  examples/llm/vdb_upload/module/file_source_pipe.py
  examples/llm/vdb_upload/module/rss_source_pipe.py
  examples/llm/vdb_upload/module/schema_transform.py
  examples/llm/vdb_upload/module/vdb_resource_tagging_module.py
  examples/llm/vdb_upload/module/web_scraper_module.py
  pyproject.toml
  python/morpheus/morpheus/modules/schemas/deserialize_schema.py
  python/morpheus/morpheus/modules/schemas/multi_file_source_schema.py
  python/morpheus/morpheus/modules/schemas/rss_source_schema.py
  python/morpheus/morpheus/stages/input/arxiv_source.py
  python/morpheus/morpheus/stages/input/http_server_source_stage.py
  python/morpheus/morpheus/utils/column_info.py
  python/morpheus_llm/morpheus_llm/modules/schemas/write_to_vector_db_schema.py
  tests/_utils/test_directories.py
  tests/conftest.py
  tests/examples/gnn_fraud_detection_pipeline/conftest.py
  tests/examples/llm/common/conftest.py
  tests/examples/ransomware_detection/conftest.py
  tests/morpheus/conftest.py
  tests/morpheus/stages/test_multi_processing_stage.py
  tests/morpheus/utils/test_downloader.py
  tests/morpheus_dfp/conftest.py
  tests/morpheus_llm/stages/arxiv/conftest.py
  tests/morpheus_llm/stages/arxiv/test_arxiv_source.py
Labels: non-breaking, improvement

#1906 Support LLM pipelines in CPU-only mode
  examples/llm/agents/run.py
  examples/llm/agents/simple_pipeline.py
  examples/llm/completion/pipeline.py
  examples/llm/completion/run.py
  python/morpheus_llm/morpheus_llm/llm/nodes/extracter_node.py
  python/morpheus_llm/morpheus_llm/llm/task_handlers/simple_task_handler.py
  python/morpheus_llm/morpheus_llm/stages/llm/llm_engine_stage.py
  tests/morpheus_llm/llm/nodes/test_extractor_node.py
  tests/morpheus_llm/llm/nodes/test_manual_extractor_node.py
  tests/morpheus_llm/llm/task_handlers/test_simple_task_handler.py
Labels: breaking, improvement

#1924 Update documentation to reflect CPU-only execution mode
  conda/environments/examples_cuda-125_arch-x86_64.yaml
  dependencies.yaml
  docs/README.md
  docs/source/basics/building_a_pipeline.md
  docs/source/basics/overview.rst
  docs/source/cloud_deployment_guide.md
  docs/source/developer_guide/contributing.md
  docs/source/developer_guide/guides/10_modular_pipeline_digital_fingerprinting.md
  docs/source/developer_guide/guides/1_simple_python_stage.md
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/developer_guide/guides/3_simple_cpp_stage.md
  docs/source/developer_guide/guides/4_source_cpp_stage.md
  docs/source/developer_guide/guides/5_digital_fingerprinting.md
  docs/source/developer_guide/guides/6_digital_fingerprinting_reference.md
  docs/source/developer_guide/guides/9_control_messages.md
  examples/abp_nvsmi_detection/README.md
  examples/cpu_only/README.md
  examples/developer_guide/1_simple_python_stage/pass_thru_deco.py
  examples/developer_guide/2_2_rabbitmq/README.md
  examples/developer_guide/4_rabbitmq_cpp_stage/README.md
  examples/developer_guide/4_rabbitmq_cpp_stage/src/rabbitmq_cpp_stage/rabbitmq_source_stage.py
  examples/gnn_fraud_detection_pipeline/README.md
  examples/llm/agents/README.md
  examples/llm/agents/run.py
  examples/llm/completion/README.md
  examples/llm/completion/run.py
  examples/ransomware_detection/README.md
  examples/root_cause_analysis/README.md
  python/morpheus/morpheus/io/deserializers.py
  python/morpheus/morpheus/utils/type_aliases.py
  python/morpheus/morpheus/utils/type_utils.py
Labels: non-breaking, doc

#1928 Provide a timeout to the queue.get call in `HttpServerSourceStage` to avoid spinlocking
  python/morpheus/morpheus/stages/input/http_server_source_stage.py
Labels: bug, non-breaking

#1957 Include requirements files in the morpheus packages
  ci/conda/recipes/morpheus-libs/morpheus_core_test.sh
  ci/conda/recipes/morpheus-libs/morpheus_dfp_test.sh
  ci/conda/recipes/morpheus-libs/morpheus_llm_test.sh
  dependencies.yaml
  python/morpheus/CMakeLists.txt
  python/morpheus/MANIFEST.in
  python/morpheus/morpheus/requirements_morpheus_core.txt
  python/morpheus_dfp/CMakeLists.txt
  python/morpheus_dfp/MANIFEST.in
  python/morpheus_dfp/morpheus_dfp/requirements_morpheus_dfp.txt
  python/morpheus_llm/CMakeLists.txt
  python/morpheus_llm/MANIFEST.in
  python/morpheus_llm/morpheus_llm/requirements_morpheus_llm.txt
Labels: non-breaking, feature request, conda-build

#1954 Unit tests for the namespace update script
  scripts/morpheus_namespace_update.py
  tests/conftest.py
  tests/scripts/conftest.py
  tests/scripts/data/dfp_old_namespace_data.py
  tests/scripts/data/llm_old_namespace_data.py
  tests/scripts/test_namespace_update.py
Labels: non-breaking, feature request

#1953 Improve test performance
  tests/_utils/kafka.py
  tests/conftest.py
  tests/morpheus/common/test_http_server.py
  tests/morpheus/stages/test_kafka_source_stage_pipe.py
  tests/morpheus_llm/llm/nodes/test_llm_retriever_node_pipe.py
  tests/morpheus_llm/llm/test_rag_standalone_pipe.py
  tests/morpheus_llm/services/test_milvus_vector_db_service.py
Labels: bug, non-breaking

#1964 Morpheus docs update post compartmentalization
  ci/vale/styles/config/vocabularies/morpheus/accept.txt
  docs/CMakeLists.txt
  docs/source/conda_packages.md
  docs/source/getting_started.md
  docs/source/index.rst
  docs/source/py_api.rst
  docs/source/stages/morpheus_stages.md
  python/morpheus_dfp/morpheus_dfp/modules/dfp_deployment.py
  python/morpheus_dfp/morpheus_dfp/modules/dfp_inference.py
  python/morpheus_dfp/morpheus_dfp/modules/dfp_inference_pipe.py
  python/morpheus_dfp/morpheus_dfp/modules/dfp_rolling_window.py
  python/morpheus_dfp/morpheus_dfp/modules/dfp_split_users.py
  python/morpheus_dfp/morpheus_dfp/modules/dfp_training.py
  python/morpheus_dfp/morpheus_dfp/modules/dfp_training_pipe.py
Labels: non-breaking, feature request

#1932 Document each of the Conda environment files
  ci/vale/styles/config/vocabularies/morpheus/accept.txt
  docs/source/developer_guide/contributing.md
Labels: non-breaking, doc

#1967 Add `**kwargs` back to `NVFoundationLLMClient.generate_batch()` and `generate_batch_async()`
  python/morpheus_llm/morpheus_llm/llm/services/nvfoundation_llm_service.py
Labels: bug, non-breaking

#1962 devcontainer: replace `VAULT_HOST` with `AWS_ROLE_ARN`
  .devcontainer/Dockerfile
  .devcontainer/cuda12.5-conda/devcontainer.json
Labels: non-breaking, improvement

#1975 Ensure timestamps are copied in `LLMEngineStage`
  python/morpheus/morpheus/_lib/include/morpheus/messages/control.hpp
  python/morpheus/morpheus/_lib/messages/__init__.pyi
  python/morpheus/morpheus/_lib/messages/module.cpp
  python/morpheus/morpheus/_lib/src/messages/control.cpp
  python/morpheus/morpheus/messages/control_message.py
  python/morpheus_llm/morpheus_llm/stages/llm/llm_engine_stage.py
  tests/morpheus/messages/test_control_message.py
  tests/morpheus_llm/stages/test_llm_engine_stage_pipe.py
Labels: bug, non-breaking

#1969 Add CPU-only documentation
  docs/source/basics/cpu_only_mode.md
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/getting_started.md
  docs/source/index.rst
Labels: non-breaking, doc

#1982 Incorporate review comments in the conda packages documentation
  docs/source/conda_packages.md
Labels: non-breaking, doc

#1984 Fix `onnx-to-trt` utility
  conda/environments/model-utils_cuda-125_arch-x86_64.yaml
  dependencies.yaml
  models/triton-model-repo/README.md
  models/triton-model-repo/sid-minibert-trt/1/README.md
  python/morpheus/morpheus/utils/onnx_to_trt.py
Labels: bug, non-breaking

#1986 Update `val-run-all.sh` to run cpp pipeline only
  scripts/validation/val-run-all.sh
Labels: bug, non-breaking

#1974 Install sentence-transformers via pip to avoid CPU-torch conda dependencies
  .github/workflows/pr.yaml
  ci/release/update-version.sh
  ci/runner/Dockerfile
  ci/scripts/github/test.sh
  ci/scripts/run_ci_local.sh
  conda/environments/all_cuda-125_arch-x86_64.yaml
  conda/environments/examples_cuda-125_arch-x86_64.yaml
  dependencies.yaml
Labels: bug, non-breaking, conda-build

#1976 Populate all the LFS data needed for running examples within the release container
  docker/Dockerfile
  examples/data/log-parsing-config-20220418.json
  examples/data/log-parsing-validation-data-input.csv
  examples/log_parsing/README.md
  examples/log_parsing/run.py
Labels: bug, non-breaking

#1992 Fix minor issues with LLM example documentation
  examples/llm/agents/README.md
  examples/llm/completion/README.md
  examples/llm/rag/README.md
  examples/llm/vdb_upload/README.md
Labels: non-breaking, doc

#1998 Remove temporary DFP todo list
  python/morpheus_dfp/todo.md
Labels: non-breaking, improvement

#1977 Fix missing dependency in DFP Grafana example
  conda/environments/all_cuda-125_arch-x86_64.yaml
  conda/environments/examples_cuda-125_arch-x86_64.yaml
  dependencies.yaml
  examples/digital_fingerprinting/production/conda_env.yml
Labels: bug, non-breaking

#1995 Fix AttributeError: 'int' object has no attribute 'item'
  docs/source/developer_guide/guides/5_digital_fingerprinting.md
  examples/digital_fingerprinting/production/Dockerfile
  examples/digital_fingerprinting/production/docker-compose.yml
  examples/digital_fingerprinting/production/launch.sh
  examples/digital_fingerprinting/production/morpheus/benchmarks/README.md
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_payload_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_payload_load_train_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_payload_load_training.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_payload_lti.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_payload_training.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_streaming_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_streaming_lti.json
  examples/digital_fingerprinting/production/morpheus/control_messages/azure_streaming_training.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_payload_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_payload_load_train_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_payload_lti.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_payload_only_load.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_payload_training.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_streaming_inference.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_streaming_lti.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_streaming_only_load.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_streaming_payload.json
  examples/digital_fingerprinting/production/morpheus/control_messages/duo_streaming_training.json
  examples/digital_fingerprinting/visualization/README.md
  python/morpheus_dfp/morpheus_dfp/stages/dfp_rolling_window_stage.py
Labels: bug, non-breaking

#2004 Fix CUDF's `Column.from_column_view` by copying it and adjusting.
  python/morpheus/morpheus/_lib/cudf_helpers.pyx
  python/morpheus/morpheus/_lib/cudf_helpers/__init__.pyi
  python/morpheus/morpheus/_lib/tests/messages/test_message_meta.cpp
Labels: bug, non-breaking

#2003 Fix up file paths in the DFP README
  examples/digital_fingerprinting/production/README.md
Labels: bug, non-breaking

#2009 Fix mis-leading deserialize stage comments
  examples/abp_nvsmi_detection/README.md
  examples/nlp_si_detection/README.md
  examples/root_cause_analysis/README.md
Labels: non-breaking, doc

#2008 Update Morpheus docs to use cuda 12.5
  .github/workflows/ci_pipe.yml
  docs/source/developer_guide/contributing.md
  docs/source/developer_guide/guides/5_digital_fingerprinting.md
  docs/source/getting_started.md
  examples/abp_nvsmi_detection/README.md
Labels: non-breaking, doc

#2006 Fix offset calculation when taking a slice of a `SlicedMessageMeta`
  python/morpheus/morpheus/_lib/src/messages/meta.cpp
  tests/morpheus/apps/test_sid.py
  tests/morpheus/apps/test_sid_kafka.py
Labels: bug, non-breaking

#2016 Fixup file paths in the modular digital fingerprinting documentation.
  docs/source/developer_guide/guides/10_modular_pipeline_digital_fingerprinting.md
Labels: bug, non-breaking

#2017 Set the version in the conda packages docs
  docs/source/conda_packages.md
Labels: non-breaking, doc

#2015 Fix `DeserializeStage` to ensure output messages correctly contain the correct rows for each batch
  python/morpheus/morpheus/_lib/src/messages/meta.cpp
  python/morpheus/morpheus/_lib/src/stages/deserialize.cpp
  tests/morpheus/pipeline/test_file_in_out.py
Labels: bug, non-breaking

#1971 Install morpheus-dfp conda package in the DFP container
  dependencies.yaml
  docs/source/conda_packages.md
  examples/digital_fingerprinting/production/Dockerfile
  examples/digital_fingerprinting/production/README.md
  examples/digital_fingerprinting/production/conda/environments/dfp_example_cuda-125_arch-x86_64.yaml
  examples/digital_fingerprinting/production/docker-compose.yml
  examples/digital_fingerprinting/production/docker/entrypoint.sh
Labels: non-breaking, feature request

#2001 Update to Triton Inference Server container version 24.09
  .devcontainer/docker-compose.yml
  docs/source/getting_started.md
  models/docker/Dockerfile
  models/docker/build_container.sh
  models/ransomware-models/ransomw-model-short-rf/checkpoint.tl
  models/triton-model-repo/log-parsing-onnx/config.pbtxt
Labels: non-breaking, improvement

#1963 Adding implementation of Router Nodes
  ci/iwyu/mappings.imp
  python/morpheus/morpheus/_lib/messages/module.cpp
  python/morpheus/morpheus/_lib/src/stages/file_source.cpp
  python/morpheus/morpheus/_lib/src/stages/kafka_source.cpp
  python/morpheus/morpheus/_lib/src/stages/write_to_file.cpp
  python/morpheus/morpheus/_lib/stages/module.cpp
  python/morpheus/morpheus/stages/general/router_stage.py
  python/morpheus_llm/morpheus_llm/_lib/llm/src/py_llm_lambda_node.cpp
  tests/morpheus/stages/test_router_stage_pipe.py
Labels: non-breaking, feature request

#2024 Fix `log_parsing` example pipeline null output issue
  examples/log_parsing/inference.py
  python/morpheus/morpheus/stages/inference/inference_stage.py
  tests/examples/log_parsing/test_inference.py
  tests/morpheus/stages/test_inference_stage.py
Labels: bug, non-breaking
