Repository nv-morpheus/Morpheus, pull requests merged in 2024-09, with the labels that each got.

#1857 ensure columns are strings before concatenation
  python/morpheus/morpheus/utils/column_info.py
  tests/test_column_info.py
Labels: bug, non-breaking

#1858 Warn when `Config`'s `pipeline_batch_size < model_max_batch_size`
  python/morpheus/morpheus/config.py
  tests/test_config.py
Labels: non-breaking, improvement

#1885 Drop 'CI Pipeline / Check' dependency from the 'package-core' job
  .github/workflows/ci_pipe.yml
Labels: bug, non-breaking, conda-core-build

#1880 Run pre-commit on all files, not just python
  .pre-commit-config.yaml
  pyproject.toml
Labels: non-breaking, improvement

#1879 Remove `TODO` statements from documentation
  ci/vale/styles/config/vocabularies/morpheus/reject.txt
  docs/source/developer_guide/architecture.md
  examples/digital_fingerprinting/demo/review_results.md
Labels: non-breaking, doc

#1894 Fix DFP integrated training Azure pipeline
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_training.py
Labels: bug, non-breaking

#1896 Fix `Can't find 'action.yml'` CI error
  .github/workflows/pr.yaml
Labels: bug, non-breaking

#1889 Move vector db stages to morpheus-llm
  examples/doca/vdb_realtime/vdb.py
  examples/llm/common/utils.py
  examples/llm/vdb_upload/pipeline.py
  examples/llm/vdb_upload/vdb_utils.py
  python/morpheus_llm/morpheus_llm/llm/nodes/rag_node.py
  python/morpheus_llm/morpheus_llm/llm/nodes/retriever_node.py
  python/morpheus_llm/morpheus_llm/modules/__init__.py
  python/morpheus_llm/morpheus_llm/modules/output/__init__.py
  python/morpheus_llm/morpheus_llm/modules/output/write_to_vector_db.py
  python/morpheus_llm/morpheus_llm/modules/schemas/__init__.py
  python/morpheus_llm/morpheus_llm/modules/schemas/write_to_vector_db_schema.py
  python/morpheus_llm/morpheus_llm/service/__init__.py
  python/morpheus_llm/morpheus_llm/service/vdb/__init__.py
  python/morpheus_llm/morpheus_llm/service/vdb/faiss_vdb_service.py
  python/morpheus_llm/morpheus_llm/service/vdb/milvus_client.py
  python/morpheus_llm/morpheus_llm/service/vdb/milvus_vector_db_service.py
  python/morpheus_llm/morpheus_llm/service/vdb/utils.py
  python/morpheus_llm/morpheus_llm/service/vdb/vector_db_service.py
  python/morpheus_llm/morpheus_llm/stages/output/__init__.py
  python/morpheus_llm/morpheus_llm/stages/output/write_to_vector_db_stage.py
  tests/_utils/milvus.py
  tests/benchmarks/test_bench_vdb_upload_pipeline.py
  tests/llm/nodes/test_llm_retriever_node_pipe.py
  tests/llm/test_vdb_upload_pipe.py
  tests/test_faiss_vector_db_service.py
  tests/test_milvus_vector_db_service.py
  tests/test_milvus_write_to_vector_db_stage_pipe.py
Labels: non-breaking, feature request

#1907 Fix conda path for missing llm packages
  python/morpheus_llm/morpheus_llm/llm/services/nemo_llm_service.py
  python/morpheus_llm/morpheus_llm/llm/services/openai_chat_service.py
Labels: bug, non-breaking

#1901 Remove redundant copy of the `load_labels_file` method
  docs/source/developer_guide/guides/6_digital_fingerprinting_reference.md
  examples/digital_fingerprinting/production/grafana/run.py
  examples/digital_fingerprinting/production/morpheus/dfp/utils/config_generator.py
  examples/digital_fingerprinting/production/morpheus/dfp_azure_pipeline.py
  examples/digital_fingerprinting/production/morpheus/dfp_duo_pipeline.py
  examples/digital_fingerprinting/production/morpheus/notebooks/dfp_azure_inference.ipynb
  examples/digital_fingerprinting/production/morpheus/notebooks/dfp_azure_training.ipynb
  examples/digital_fingerprinting/production/morpheus/notebooks/dfp_duo_inference.ipynb
  examples/digital_fingerprinting/production/morpheus/notebooks/dfp_duo_training.ipynb
  examples/digital_fingerprinting/visualization/dfp_viz_azure_pipeline.py
  examples/digital_fingerprinting/visualization/dfp_viz_duo_pipeline.py
  python/morpheus/morpheus/cli/commands.py
  python/morpheus/morpheus/cli/utils.py
  python/morpheus/morpheus/utils/file_utils.py
Labels: bug, non-breaking

#1902 Avoid memory leak warnings from `pypdfium2`
  examples/llm/cli.py
Labels: bug, non-breaking

#1905 Update `WriteToVectorDBStage` to re-raise errors from the underlying database
  python/morpheus_llm/morpheus_llm/modules/output/write_to_vector_db.py
  tests/test_milvus_write_to_vector_db_stage_pipe.py
Labels: bug, non-breaking

#1878 Implement `MultiProcessingStage`
  python/morpheus/morpheus/stages/general/multi_processing_stage.py
  python/morpheus/morpheus/utils/shared_process_pool.py
  tests/test_multi_processing_stage.py
  tests/utils/test_shared_process_pool.py
Labels: non-breaking, feature request

#1914 Fixing the docker build when Morpheus is a submodule
  docker/Dockerfile
  docs/source/developer_guide/contributing.md
Labels: bug, non-breaking
