Repository nv-morpheus/Morpheus, pull requests merged in 2024-06, with the labels that each got.

#1710 Allow passing `metadata` to `LangChainAgentNode._run_single`
  morpheus/llm/nodes/langchain_agent_node.py
  tests/llm/nodes/test_langchain_agent_node.py
  tests/llm/nodes/test_langchain_agent_node_pipe.py
  tests/llm/test_agents_simple_pipe.py
Labels: non-breaking, improvement

#1724 Enable Python install by default in `compile.sh`
  docs/source/developer_guide/guides.md
  docs/source/developer_guide/guides/3_simple_cpp_stage.md
  docs/source/developer_guide/guides/4_source_cpp_stage.md
  examples/developer_guide/4_rabbitmq_cpp_stage/README.md
  scripts/compile.sh
Labels: non-breaking, improvement

#1716 Improve the logging tests and add support for resetting the logger
  morpheus/utils/logger.py
  tests/benchmarks/conftest.py
  tests/conftest.py
  tests/test_cli.py
  tests/test_dfp_kafka.py
  tests/test_logger.py
  tests/tests_data/logging.json
Labels: non-breaking, improvement

#1699 Add group by column stage
  morpheus/stages/preprocess/group_by_column_stage.py
  tests/stages/test_group_by_column_stage.py
Labels: non-breaking, improvement

#1723 Replace `isinstance` check with with `callable` in `LLMService.create`
  morpheus/llm/services/llm_service.py
  morpheus/utils/logger.py
  tests/benchmarks/conftest.py
  tests/conftest.py
  tests/llm/services/test_llm_service.py
  tests/llm/services/test_openai_chat_service.py
  tests/test_cli.py
  tests/test_dfp_kafka.py
  tests/test_logger.py
  tests/tests_data/logging.json
Labels: non-breaking, improvement

#1730 Updating all uses of the `secrets.PROJECT_MANAGEMENT_PAT` to use a registered Github App
  .github/workflows/label-external-issues.yml
  .github/workflows/project_automation_set_in_progress.yml
  .github/workflows/project_automation_set_in_review.yml
  .github/workflows/project_automation_set_roadmap.yml
  .github/workflows/project_automation_sync_pr_issues.yml
  .github/workflows/project_automation_track_pr_dates.yml
Labels: bug, non-breaking

#1714 Added tests for `NVFoundationLLMService` and `FaissVectorDbService`
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/dev_cuda-121_arch-x86_64.yaml
  conda/environments/examples_cuda-121_arch-x86_64.yaml
  conda/environments/runtime_cuda-121_arch-x86_64.yaml
  dependencies.yaml
  morpheus.code-workspace
  morpheus/llm/services/nvfoundation_llm_service.py
  morpheus/llm/services/openai_chat_service.py
  morpheus/service/vdb/faiss_vdb_service.py
  tests/conftest.py
  tests/llm/services/test_llm_service_pipe.py
  tests/llm/services/test_nvfoundation_llm_service.py
  tests/llm/services/test_openai_chat_client.py
  tests/llm/services/test_openai_chat_service.py
  tests/llm/test_completion_pipe.py
  tests/test_faiss_vector_db_service.py
Labels: non-breaking, improvement

#1736 Always run the PR builder step even if others are cancelled
  .github/workflows/pr.yaml
Labels: non-breaking, improvement

#1538 Add struct column support to `cudf_helpers`
  morpheus/_lib/cudf_helpers.pyx
  morpheus/_lib/cudf_helpers/__init__.pyi
  morpheus/messages/message_meta.py
  tests/_utils/dataset_manager.py
  tests/llm/nodes/test_llm_retriever_node_pipe.py
  tests/messages/test_control_message.py
  tests/messages/test_message_meta.py
  tests/tests_data/test_dataframe.jsonlines
Labels: bug, non-breaking

#1749 Fixes for C++ impl for `DeserializeStage` and add missing `get_info` overloads to `SlicedMessageMeta`
  morpheus/_lib/include/morpheus/messages/meta.hpp
  morpheus/_lib/src/messages/meta.cpp
  morpheus/_lib/src/stages/preprocess_fil.cpp
  morpheus/_lib/tests/messages/test_sliced_message_meta.cpp
  morpheus/stages/preprocess/deserialize_stage.py
Labels: bug, non-breaking

#1751 Misc improvements for sid_visualization example
  examples/sid_visualization/README.md
  examples/sid_visualization/run.py
Labels: non-breaking, improvement

#1755 Disable shared memory by default, and fix `--stop_after` flag for `vdb_upload` example
  examples/llm/vdb_upload/run.py
  examples/llm/vdb_upload/vdb_config.yaml
  examples/llm/vdb_upload/vdb_utils.py
Labels: bug, non-breaking

#1759 Remove setting of `prog_name`, this implies that an executable named `morpheus_llm` exists
  examples/llm/main.py
Labels: bug, non-breaking

#1729 DOCA: fix optional deps + remove PreallocatorMixin from source stage
  ci/runner/Dockerfile
  docker/Dockerfile
  docker/optional_deps/doca.sh
  examples/doca/README.md
  examples/doca/run_tcp.py
  morpheus/stages/doca/doca_source_stage.py
Labels: bug, non-breaking

#1756 Fix `RabbitMQ` output path
  examples/developer_guide/2_2_rabbitmq/README.md
  examples/developer_guide/2_2_rabbitmq/read_simple.py
  examples/developer_guide/4_rabbitmq_cpp_stage/README.md
  examples/developer_guide/4_rabbitmq_cpp_stage/src/read_simple.py
Labels: non-breaking, improvement

#1750 Fix conda errors in release container
  docker/Dockerfile
  examples/digital_fingerprinting/production/Dockerfile
Labels: bug, non-breaking, dfp, conda-build

#1735 resolve rapids-dependency-file-generator warning
  .github/workflows/pr.yaml
  .pre-commit-config.yaml
  ci/check_style.sh
  ci/runner/Dockerfile
  ci/scripts/github/build.sh
  ci/scripts/github/checks.sh
  ci/scripts/github/docs.sh
  ci/scripts/github/test.sh
  ci/scripts/run_ci_local.sh
Labels: bug, non-breaking

#1762 Clarify Documentation: Run fetch_data.py Outside Docker Container
  docs/source/examples.md
  docs/source/getting_started.md
Labels: non-breaking, doc

#1748 Add GIT_CLONE_PROTECTION_ACTIVE env config to fix build script
  docker/Dockerfile
Labels: bug, non-breaking

#1739 Fix triton multi threading when using the C++ stage
  morpheus/_lib/include/morpheus/stages/triton_inference.hpp
  morpheus/_lib/messages/module.cpp
  morpheus/_lib/src/stages/triton_inference.cpp
  morpheus/stages/inference/triton_inference_stage.py
  tests/test_sid.py
Labels: bug, non-breaking

#1760 Merge Agent Morpheus changes
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/dev_cuda-121_arch-x86_64.yaml
  conda/environments/examples_cuda-121_arch-x86_64.yaml
  conda/environments/runtime_cuda-121_arch-x86_64.yaml
  dependencies.yaml
  docs/source/conf.py
  morpheus.code-workspace
  morpheus/_lib/src/llm/utils.cpp
  morpheus/controllers/write_to_file_controller.py
  morpheus/llm/nodes/extracter_node.py
  morpheus/llm/nodes/langchain_agent_node.py
  morpheus/llm/nodes/prompt_template_node.py
  morpheus/llm/services/llm_service.py
  morpheus/llm/services/nemo_llm_service.py
  morpheus/llm/services/nvfoundation_llm_service.py
  morpheus/llm/services/openai_chat_service.py
  morpheus/llm/services/utils/__init__.py
  morpheus/llm/services/utils/langchain_llm_client_wrapper.py
  morpheus/messages/message_base.py
  morpheus/messages/multi_ae_message.py
  morpheus/service/vdb/faiss_vdb_service.py
  morpheus/utils/column_info.py
  tests/conftest.py
  tests/llm/nodes/test_langchain_agent_node.py
  tests/llm/nodes/test_manual_extractor_node.py
  tests/llm/nodes/test_prompt_template_node.py
  tests/llm/services/conftest.py
  tests/llm/services/test_llm_service.py
  tests/llm/services/test_llm_service_pipe.py
  tests/llm/services/test_nvfoundation_llm_service.py
  tests/llm/services/test_openai_chat_client.py
  tests/llm/services/test_openai_chat_service.py
  tests/llm/test_completion_pipe.py
  tests/llm/test_rag_standalone_pipe.py
  tests/test_faiss_vector_db_service.py
Labels: non-breaking, improvement, sherlock

#1743 Auditing the dependencies and syncing `dependencies.yaml` with `meta.yaml`
  ci/conda/recipes/morpheus/meta.yaml
  ci/scripts/github/test.sh
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/dev_cuda-121_arch-x86_64.yaml
  conda/environments/examples_cuda-121_arch-x86_64.yaml
  conda/environments/runtime_cuda-121_arch-x86_64.yaml
  dependencies.yaml
  examples/developer_guide/3_simple_cpp_stage/setup.cfg
  examples/developer_guide/4_rabbitmq_cpp_stage/setup.cfg
Labels: non-breaking, improvement, conda-build

#1734 Introduce multi-endpoint servers and health check endpoints to HttpServerSourceStage
  morpheus/_lib/common/__init__.pyi
  morpheus/_lib/common/module.cpp
  morpheus/_lib/include/morpheus/stages/http_server_source_stage.hpp
  morpheus/_lib/include/morpheus/utilities/http_server.hpp
  morpheus/_lib/src/stages/http_server_source_stage.cpp
  morpheus/_lib/src/utilities/http_server.cpp
  morpheus/_lib/stages/__init__.pyi
  morpheus/_lib/stages/module.cpp
  morpheus/common/__init__.py
  morpheus/stages/input/http_server_source_stage.py
  morpheus/stages/output/http_server_sink_stage.py
  tests/common/test_http_server.py
  tests/stages/test_http_server_source_stage.py
Labels: breaking, feature request

#1764 Remove pre-built container section from `getting_started.md`
  docs/source/getting_started.md
Labels: non-breaking, doc

#1768 Add troubleshooting reference for unsuccessful documentation builds
  docs/README.md
  docs/source/extra_info/troubleshooting.md
Labels: non-breaking, doc

#1766 Release container fixes
  conda/environments/examples_cuda-121_arch-x86_64.yaml
  dependencies.yaml
  docker/Dockerfile
Labels: bug, non-breaking

#1774 Remove out of date instructions from `contributing.md`
  docs/source/developer_guide/contributing.md
Labels: non-breaking, doc

#1777 Add cuda and cudf to link targets for C++ examples
  examples/developer_guide/3_simple_cpp_stage/CMakeLists.txt
  examples/developer_guide/3_simple_cpp_stage/src/simple_cpp_stage/_lib/CMakeLists.txt
  examples/developer_guide/4_rabbitmq_cpp_stage/CMakeLists.txt
  examples/developer_guide/4_rabbitmq_cpp_stage/cmake/dependencies.cmake
  examples/developer_guide/4_rabbitmq_cpp_stage/src/rabbitmq_cpp_stage/_lib/CMakeLists.txt
Labels: bug, non-breaking

#1778 Remove documentation for yaml config files in `vdb_upload` pipeline until #1752 is resolved
  docs/source/examples/llm/rag/README.md
  docs/source/examples/llm/rag/images/persistent_pipeline.png
  docs/source/examples/llm/vdb_upload/README.md
  examples/llm/rag/README.md
  examples/llm/vdb_upload/README.md
Labels: non-breaking, doc
