Repository nv-morpheus/Morpheus, pull requests merged in 2024-03, with the labels that each got.

#1541 Update to match new MRC function sig for AsyncioRunnable::on_data
  morpheus/_lib/llm/include/py_llm_engine_stage.hpp
Labels: non-breaking, improvement

#1535 Adding missing dependency on `pydantic`
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/dev_cuda-121_arch-x86_64.yaml
  conda/environments/examples_cuda-121_arch-x86_64.yaml
  conda/environments/runtime_cuda-121_arch-x86_64.yaml
  dependencies.yaml
Labels: bug, non-breaking

#1544 Add retry logic and proxy support to the NeMo LLM Service
  morpheus.code-workspace
  morpheus/llm/services/llm_service.py
  morpheus/llm/services/nemo_llm_service.py
  morpheus/llm/services/openai_chat_service.py
  tests/_utils/environment.py
  tests/conftest.py
  tests/llm/conftest.py
  tests/llm/services/test_llm_service_pipe.py
  tests/llm/services/test_nemo_llm_client.py
  tests/llm/services/test_nemo_llm_service.py
  tests/llm/services/test_openai_chat_client.py
  tests/llm/test_completion_pipe.py
Labels: breaking, improvement

#1539 Catch langchain agent errors
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/dev_cuda-121_arch-x86_64.yaml
  conda/environments/examples_cuda-121_arch-x86_64.yaml
  conda/environments/runtime_cuda-121_arch-x86_64.yaml
  dependencies.yaml
  morpheus/llm/nodes/langchain_agent_node.py
  tests/_utils/llm.py
  tests/llm/nodes/test_langchain_agent_node.py
Labels: bug, non-breaking

#1561 Dev Day Notebook
  examples/cyber_dev_day/notebooks/cyber-dev-day.ipynb
Labels: non-breaking, improvement

#1553 Fix `configure_logging` in DFP benchmarks
  examples/digital_fingerprinting/production/morpheus/benchmarks/test_bench_e2e_dfp_pipeline.py
Labels: bug, non-breaking

#1562 Fix a few type-os
  examples/cyber_dev_day/notebooks/cyber-dev-day.ipynb
Labels: non-breaking, improvement

#1551 Fix environment yaml paths
  conda/environments/examples_cuda-121_arch-x86_64.yaml
  docker/Dockerfile
  docs/README.md
  docs/source/developer_guide/contributing.md
  examples/digital_fingerprinting/production/Dockerfile
  examples/digital_fingerprinting/production/morpheus/benchmarks/README.md
  examples/gnn_fraud_detection_pipeline/README.md
  examples/llm/agents/README.md
  examples/llm/completion/README.md
  models/training-tuning-scripts/fraud-detection-models/README.md
  morpheus/llm/services/nemo_llm_service.py
  morpheus/llm/services/openai_chat_service.py
  tests/benchmarks/README.md
  tests/conftest.py
  tests/examples/llm/common/conftest.py
  tests/stages/arxiv/conftest.py
Labels: non-breaking, improvement

#1475 DOCA Source Stage improvements
  docker/Dockerfile
  docker/build_container.sh
  docker/optional_deps/doca.sh
  examples/doca/README.md
  examples/doca/run.py
  morpheus/_lib/doca/__init__.pyi
  morpheus/_lib/doca/include/common.hpp
  morpheus/_lib/doca/include/doca_context.hpp
  morpheus/_lib/doca/include/doca_rx_pipe.hpp
  morpheus/_lib/doca/include/doca_rx_queue.hpp
  morpheus/_lib/doca/include/doca_semaphore.hpp
  morpheus/_lib/doca/include/doca_source.hpp
  morpheus/_lib/doca/include/doca_source_kernels.hpp
  morpheus/_lib/doca/include/error.hpp
  morpheus/_lib/doca/module.cpp
  morpheus/_lib/doca/src/doca_context.cpp
  morpheus/_lib/doca/src/doca_rx_pipe.cpp
  morpheus/_lib/doca/src/doca_rx_queue.cpp
  morpheus/_lib/doca/src/doca_semaphore.cpp
  morpheus/_lib/doca/src/doca_source.cpp
  morpheus/_lib/doca/src/doca_source_kernels.cu
  morpheus/stages/doca/doca_source_stage.py
Labels: non-breaking, improvement

#1572 Update MLflow in Production DFP example to use Python 3.10
  examples/digital_fingerprinting/production/mlflow/Dockerfile
  examples/digital_fingerprinting/production/morpheus/dfp/utils/config_generator.py
Labels: non-breaking, improvement

#1578 Update DFP MLflow ModelManager to handle model retrieval using file URI
  examples/digital_fingerprinting/production/morpheus/dfp/utils/model_cache.py
Labels: bug, non-breaking

#1580 Fix `iso_date_regex_pattern` config in `file_batcher` module and allow override
  morpheus/modules/file_batcher.py
  tests/modules/test_file_batcher.py
Labels: bug, non-breaking
