Repository nv-morpheus/Morpheus, pull requests merged in 2024-04, with the labels that each got.

#1584 Remove the defaults channel from `dependencies.yml`
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/dev_cuda-121_arch-x86_64.yaml
  conda/environments/examples_cuda-121_arch-x86_64.yaml
  conda/environments/model-utils_cuda-121_arch-x86_64.yaml
  conda/environments/runtime_cuda-121_arch-x86_64.yaml
  dependencies.yaml
Labels: bug, non-breaking, conda-build

#1548 Adding retry logic to the `TritonInferenceStage` to allow recovering from errors
  .clang-tidy
  examples/log_parsing/inference.py
  morpheus/_lib/cmake/libmorpheus.cmake
  morpheus/_lib/include/morpheus/stages/inference_client_stage.hpp
  morpheus/_lib/include/morpheus/stages/triton_inference.hpp
  morpheus/_lib/llm/include/py_llm_engine.hpp
  morpheus/_lib/llm/src/py_llm_engine.cpp
  morpheus/_lib/messages/module.cpp
  morpheus/_lib/src/stages/inference_client_stage.cpp
  morpheus/_lib/src/stages/triton_inference.cpp
  morpheus/_lib/stages/__init__.pyi
  morpheus/_lib/stages/module.cpp
  morpheus/_lib/tests/CMakeLists.txt
  morpheus/_lib/tests/stages/test_triton_inference_stage.cpp
  morpheus/stages/inference/triton_inference_stage.py
  tests/examples/log_parsing/test_inference.py
  tests/test_cli.py
  tests/test_triton_inference_stage.py
Labels: non-breaking, feature request

#1592 Serialize datetime objects into the module config
  examples/digital_fingerprinting/production/morpheus/dfp/utils/config_generator.py
  morpheus/modules/file_batcher.py
  tests/examples/digital_fingerprinting/utils/test_config_generator.py
  tests/modules/test_file_batcher.py
Labels: bug, non-breaking, dfp

#1589 Support non-json serializable objects in LLMContext
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/dev_cuda-121_arch-x86_64.yaml
  dependencies.yaml
  morpheus.code-workspace
  morpheus/_lib/include/morpheus/llm/llm_context.hpp
  morpheus/_lib/include/morpheus/llm/llm_engine.hpp
  morpheus/_lib/include/morpheus/llm/llm_lambda_node.hpp
  morpheus/_lib/include/morpheus/pybind11/json.hpp
  morpheus/_lib/llm/__init__.pyi
  morpheus/_lib/llm/include/py_llm_engine.hpp
  morpheus/_lib/llm/include/py_llm_lambda_node.hpp
  morpheus/_lib/llm/module.cpp
  morpheus/_lib/llm/src/py_llm_engine.cpp
  morpheus/_lib/llm/src/py_llm_lambda_node.cpp
  morpheus/_lib/llm/src/py_llm_task_handler.cpp
  morpheus/_lib/src/llm/llm_context.cpp
  morpheus/_lib/src/llm/llm_engine.cpp
  morpheus/_lib/tests/llm/test_llm_context.cpp
  morpheus/_lib/tests/llm/test_llm_engine.cpp
  morpheus/_lib/tests/llm/test_llm_node.cpp
  morpheus/_lib/tests/llm/test_llm_node_runner.cpp
  morpheus/_lib/tests/llm/test_llm_task_handler_runner.cpp
  morpheus/llm/nodes/langchain_agent_node.py
  tests/llm/nodes/test_langchain_agent_node.py
  tests/llm/task_handlers/test_simple_task_handler.py
Labels: dependencies, breaking, improvement, sherlock

#1594 Update minimum compute requirements to Volta
  docs/source/cloud_deployment_guide.md
  docs/source/developer_guide/contributing.md
  docs/source/getting_started.md
  examples/gnn_fraud_detection_pipeline/README.md
Labels: non-breaking, doc

#1573 Support `ControlMessage` for `PreProcessNLPStage` `PreProcessFILStage` `AddScoreStageBase`
  morpheus.code-workspace
  morpheus/_lib/include/morpheus/messages/control.hpp
  morpheus/_lib/include/morpheus/messages/memory/inference_memory_fil.hpp
  morpheus/_lib/include/morpheus/messages/meta.hpp
  morpheus/_lib/include/morpheus/stages/add_classification.hpp
  morpheus/_lib/include/morpheus/stages/add_scores.hpp
  morpheus/_lib/include/morpheus/stages/add_scores_stage_base.hpp
  morpheus/_lib/include/morpheus/stages/preprocess_fil.hpp
  morpheus/_lib/include/morpheus/stages/preprocess_nlp.hpp
  morpheus/_lib/include/morpheus/stages/serialize.hpp
  morpheus/_lib/messages/__init__.pyi
  morpheus/_lib/messages/module.cpp
  morpheus/_lib/src/messages/control.cpp
  morpheus/_lib/src/messages/meta.cpp
  morpheus/_lib/src/stages/add_classification.cpp
  morpheus/_lib/src/stages/add_scores.cpp
  morpheus/_lib/src/stages/add_scores_stage_base.cpp
  morpheus/_lib/src/stages/preprocess_fil.cpp
  morpheus/_lib/src/stages/preprocess_nlp.cpp
  morpheus/_lib/src/stages/serialize.cpp
  morpheus/_lib/src/utilities/matx_util.cu
  morpheus/_lib/stages/__init__.pyi
  morpheus/_lib/stages/module.cpp
  morpheus/_lib/tests/CMakeLists.txt
  morpheus/_lib/tests/messages/test_control_message.cpp
  morpheus/_lib/tests/messages/test_message_meta.cpp
  morpheus/_lib/tests/messages/test_messages.hpp
  morpheus/_lib/tests/messages/test_sliced_message_meta.cpp
  morpheus/_lib/tests/stages/test_add_classification.cpp
  morpheus/_lib/tests/stages/test_add_scores.cpp
  morpheus/_lib/tests/stages/test_preprocess_fil.cpp
  morpheus/_lib/tests/stages/test_preprocess_nlp.cpp
  morpheus/_lib/tests/test_utils/common.cpp
  morpheus/_lib/tests/test_utils/common.hpp
  morpheus/_lib/tests/test_utils/tensor_utils.cpp
  morpheus/_lib/tests/test_utils/tensor_utils.hpp
  morpheus/controllers/serialize_controller.py
  morpheus/pipeline/stage_base.py
  morpheus/stages/postprocess/add_classifications_stage.py
  morpheus/stages/postprocess/add_scores_stage.py
  morpheus/stages/postprocess/add_scores_stage_base.py
  morpheus/stages/postprocess/serialize_stage.py
  morpheus/stages/preprocess/preprocess_base_stage.py
  morpheus/stages/preprocess/preprocess_fil_stage.py
  morpheus/stages/preprocess/preprocess_nlp_stage.py
  tests/_utils/stages/conv_msg.py
  tests/stages/test_preprocess_fil_stage.py
  tests/stages/test_preprocess_nlp_stage.py
  tests/test_add_classifications_stage.py
  tests/test_add_classifications_stage_pipe.py
  tests/test_add_scores_stage.py
  tests/test_add_scores_stage_pipe.py
  tests/tests_data/bools.csv
  tests/tests_data/countries_sample.csv
  tests/tests_data/csv_sample.csv
  tests/tests_data/float_str.csv
  tests/tests_data/floats.csv
Labels: non-breaking, improvement

#1604 Fix for databricks_cli import error
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/dev_cuda-121_arch-x86_64.yaml
  conda/environments/examples_cuda-121_arch-x86_64.yaml
  conda/environments/runtime_cuda-121_arch-x86_64.yaml
  dependencies.yaml
Labels: bug, dependencies, non-breaking, ! - Hotfix, conda-build

#1602 Move MemoryDescriptor to the morpheus namespace
  morpheus/_lib/include/morpheus/objects/memory_descriptor.hpp
  morpheus/_lib/src/objects/memory_descriptor.cpp
Labels: bug, breaking, ! - Hotfix, ! - Release

#1612 Switch to kafka 3.5.2
  ci/scripts/download_kafka.py
Labels: bug, non-breaking, ! - Hotfix

#1609 Update mlflow to avoid CVE-2024-27132 and CVE-2024-27133
  ci/conda/recipes/morpheus/meta.yaml
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/dev_cuda-121_arch-x86_64.yaml
  conda/environments/examples_cuda-121_arch-x86_64.yaml
  conda/environments/runtime_cuda-121_arch-x86_64.yaml
  dependencies.yaml
  examples/digital_fingerprinting/production/conda_env.yml
  examples/digital_fingerprinting/production/mlflow/Dockerfile
  models/mlflow/README.md
  models/mlflow/docker/Dockerfile
Labels: bug, non-breaking, ! - Hotfix, dfp, conda-build

#1606 [RELEASE] Morpheus v24.03.01 Hotfix
  CHANGELOG.md
  ci/conda/recipes/morpheus/meta.yaml
  ci/scripts/download_kafka.py
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/dev_cuda-121_arch-x86_64.yaml
  conda/environments/examples_cuda-121_arch-x86_64.yaml
  conda/environments/runtime_cuda-121_arch-x86_64.yaml
  dependencies.yaml
  examples/digital_fingerprinting/production/conda_env.yml
  examples/digital_fingerprinting/production/mlflow/Dockerfile
  models/mlflow/README.md
  models/mlflow/docker/Dockerfile
  morpheus/_lib/include/morpheus/objects/memory_descriptor.hpp
  morpheus/_lib/src/objects/memory_descriptor.cpp
Labels: ! - Hotfix, ! - Release

#1636 Use conda env create --yes instead of --force
  ci/check_style.sh
Labels: non-breaking, improvement

#1638 Fix a typo in the devcontainer base image
  .devcontainer/Dockerfile
Labels: bug, non-breaking

#1640 Don't set pe_count for the C++ impl of the TritonInferenceStage
  ci/check_style.sh
  morpheus/stages/inference/triton_inference_stage.py
  scripts/validation/val-run-all.sh
  scripts/validation/val-run-pipeline.sh
Labels: bug, non-breaking, ! - Hotfix

#1643 Fix vdb_upload runtime error
  examples/llm/rag/README.md
  examples/llm/vdb_upload/module/rss_source_pipe.py
  examples/llm/vdb_upload/run.py
  examples/llm/vdb_upload/vdb_config.yaml
  examples/llm/vdb_upload/vdb_utils.py
  morpheus/modules/input/rss_source.py
  morpheus/modules/schemas/rss_source_schema.py
  morpheus/stages/inference/inference_stage.py
  morpheus/stages/input/rss_source_stage.py
  morpheus/stages/preprocess/preprocess_fil_stage.py
  morpheus/stages/preprocess/preprocess_nlp_stage.py
  tests/examples/gnn_fraud_detection_pipeline/conftest.py
  tests/examples/log_parsing/conftest.py
  tests/examples/ransomware_detection/conftest.py
  tests/stages/test_preprocess_fil_stage.py
  tests/stages/test_preprocess_nlp_stage.py
  tests/test_add_classifications_stage.py
  tests/test_add_scores_stage.py
Labels: bug, non-breaking, ! - Hotfix

#1656 Document current known issues in 24.03.02
  docs/source/extra_info/known_issues.md
Labels: non-breaking, doc, ! - Hotfix

#1621 Fix `cupy_to_tensor` to also infer `uint8` and `int8` dtypes
  morpheus/_lib/include/morpheus/objects/dtype.hpp
  morpheus/_lib/src/objects/dtype.cpp
  morpheus/_lib/tests/CMakeLists.txt
  morpheus/_lib/tests/objects/test_dtype.cpp
Labels: bug, non-breaking

#1659 Fix documentation for building examples
  docs/source/developer_guide/guides.md
  docs/source/developer_guide/guides/3_simple_cpp_stage.md
  docs/source/developer_guide/guides/4_source_cpp_stage.md
  examples/developer_guide/4_rabbitmq_cpp_stage/README.md
Labels: non-breaking, doc, ! - Hotfix

#1662 Fix type-o in documentation
  examples/developer_guide/4_rabbitmq_cpp_stage/README.md
Labels: non-breaking, doc, ! - Hotfix

#1629 Fix tests to detect issue #1626
  tests/benchmarks/test_bench_e2e_pipelines.py
  tests/benchmarks/test_bench_monitor_stage.py
  tests/conftest.py
  tests/examples/developer_guide/test_python_modules.py
  tests/examples/digital_fingerprinting/test_dfp_inference_stage.py
  tests/examples/digital_fingerprinting/test_dfp_postprocessing_stage.py
  tests/examples/digital_fingerprinting/test_dfp_preprocessing_stage.py
  tests/test_abp.py
  tests/test_abp_kafka.py
  tests/test_dfp.py
  tests/test_dfp_kafka.py
  tests/test_monitor_stage.py
  tests/test_phishing.py
  tests/test_phishing_kafka.py
  tests/test_sid.py
  tests/test_sid_kafka.py
Labels: bug, non-breaking

#1664 Fix mis-spelling of examples
  examples/llm/agents/README.md
Labels: non-breaking, doc, ! - Hotfix

#1610 `ControlMessage` support in `TritonInferenceStage` and `PreallocatorMixin`
  morpheus/_lib/include/morpheus/stages/inference_client_stage.hpp
  morpheus/_lib/include/morpheus/stages/preallocate.hpp
  morpheus/_lib/src/stages/inference_client_stage.cpp
  morpheus/_lib/src/stages/triton_inference.cpp
  morpheus/_lib/stages/__init__.pyi
  morpheus/_lib/stages/module.cpp
  morpheus/_lib/tests/stages/test_triton_inference_stage.cpp
  morpheus/pipeline/preallocator_mixin.py
  morpheus/pipeline/stage_base.py
  morpheus/stages/inference/inference_stage.py
  morpheus/stages/inference/triton_inference_stage.py
  morpheus/stages/postprocess/validation_stage.py
  morpheus/stages/preprocess/preprocess_base_stage.py
  tests/test_abp.py
  tests/test_inference_stage.py
  tests/test_sid.py
Labels: non-breaking, feature request
