Repository nv-morpheus/Morpheus, pull requests merged in 2024-02, with the labels that each got.

#1485 Pin pytest to <8
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/dev_cuda-118_arch-x86_64.yaml
  dependencies.yaml
  docker/conda/environments/cuda11.8_dev.yml
Labels: bug, non-breaking

#1466 Add conda builds to CI
  .github/workflows/ci_pipe.yml
  .github/workflows/pr.yaml
  ci/conda/recipes/morpheus/meta.yaml
  ci/scripts/github/conda.sh
  ci/scripts/run_ci_local.sh
Labels: non-breaking, improvement, conda-build

#1494 Fix broken link in getting started with Morpheus doc
  docs/source/getting_started.md
Labels: non-breaking, doc

#1493 Fix logging of sleep time
  morpheus/utils/http_utils.py
Labels: bug, non-breaking

#1503 Adopt updated builds of CI runners
  .github/workflows/pr.yaml
  ci/scripts/run_ci_local.sh
Labels: bug, non-breaking

#1499 Update mlflow plugin version for deployments fix
  models/mlflow/docker/Dockerfile
Labels: bug, dependencies, non-breaking

#1501 Fix or silence warnings emitted during tests
  examples/llm/vdb_upload/module/content_extractor_module.py
  examples/llm/vdb_upload/run.py
  morpheus/_lib/src/objects/table_info.cpp
  morpheus/controllers/rss_controller.py
  morpheus/service/vdb/milvus_vector_db_service.py
  morpheus/stages/general/monitor_stage.py
  morpheus/stages/output/http_server_sink_stage.py
  morpheus/utils/column_info.py
  morpheus/utils/downloader.py
  pyproject.toml
  tests/_utils/dataset_manager.py
  tests/_utils/kafka.py
  tests/dfencoder/test_autoencoder.py
  tests/dfencoder/test_scalers.py
  tests/examples/digital_fingerprinting/test_dfp_postprocessing_stage.py
  tests/examples/digital_fingerprinting/test_dfp_split_users_stage.py
  tests/examples/llm/common/conftest.py
  tests/examples/ransomware_detection/test_preprocessing.py
  tests/llm/conftest.py
  tests/llm/test_rag_standalone_pipe.py
  tests/pipeline/test_pipeline.py
  tests/test_column_info.py
  tests/test_monitor_stage.py
  tests/utils/nvt/test_json_flatten_transform.py
  tests/utils/nvt/test_mutate_op.py
  tests/utils/nvt/test_schema_converters.py
  tests/utils/nvt/test_transforms.py
Labels: non-breaking, improvement

#1513 Fix intermittent segfault on interpreter shutdown
  morpheus/_lib/include/morpheus/utilities/cupy_util.hpp
  morpheus/_lib/src/utilities/cupy_util.cpp
  tests/test_tensor_memory.py
Labels: bug, non-breaking

#1521 Update CI Containers
  .github/workflows/pr.yaml
  ci/scripts/run_ci_local.sh
Labels: bug, non-breaking

#1463 Grafana log monitoring and error alerting example
  docs/source/developer_guide/guides/1_simple_python_stage.md
  examples/digital_fingerprinting/production/conda_env.yml
  examples/digital_fingerprinting/production/docker-compose.yml
  examples/digital_fingerprinting/production/grafana/README.md
  examples/digital_fingerprinting/production/grafana/config/grafana.ini
  examples/digital_fingerprinting/production/grafana/config/loki-config.yml
  examples/digital_fingerprinting/production/grafana/dashboards/dfp_detections.json
  examples/digital_fingerprinting/production/grafana/dashboards/dfp_logs.json
  examples/digital_fingerprinting/production/grafana/datasources/datasources.yaml
  examples/digital_fingerprinting/production/grafana/img/dfp_detections_dashboard.png
  examples/digital_fingerprinting/production/grafana/img/dfp_error_alert_setup.png
  examples/digital_fingerprinting/production/grafana/img/dfp_logs_dashboard.png
  examples/digital_fingerprinting/production/grafana/run.py
  morpheus/stages/general/buffer_stage.py
  morpheus/stages/general/delay_stage.py
  morpheus/utils/logger.py
  tests/test_logger.py
  tests/tests_data/logging.json
Labels: non-breaking, improvement, dfp

#1479 Improve pipeline stop logic to ensure join is called exactly once for all stages
  morpheus/pipeline/pipeline.py
  morpheus/stages/general/monitor_stage.py
  morpheus/stages/postprocess/generate_viz_frames_stage.py
  tests/pipeline/test_pipe_viz.py
  tests/pipeline/test_pipeline_state.py
  tests/test_http_server_source_stage_pipe.py
  tests/test_monitor_stage.py
Labels: bug, non-breaking

#1511 ControlMessage improvements
  examples/llm/cli.py
  morpheus/_lib/include/morpheus/messages/control.hpp
  morpheus/_lib/messages/__init__.pyi
  morpheus/_lib/messages/module.cpp
  morpheus/_lib/src/messages/control.cpp
  morpheus/_lib/tests/messages/test_control_message.cpp
  morpheus/stages/inference/inference_stage.py
  morpheus/stages/preprocess/preprocess_nlp_stage.py
  tests/messages/test_control_message.py
  tests/utils/test_control_message_utils.py
Labels: non-breaking, improvement

#1528 Update ops-bot.yaml
  .github/ops-bot.yaml
Labels: non-breaking, improvement

#1523 Make `start_async()` available to source stages
  morpheus/pipeline/pipeline.py
  morpheus/pipeline/stage.py
  morpheus/pipeline/stage_base.py
  tests/pipeline/test_pipeline.py
Labels: bug, breaking

#1534 Fix memory leak in the mutable dataframe checkout/checkin code
  morpheus/_lib/include/morpheus/objects/table_info.hpp
  morpheus/_lib/include/morpheus/stages/preprocess_fil.hpp
  morpheus/_lib/src/messages/multi.cpp
  morpheus/_lib/src/objects/mutable_table_ctx_mgr.cpp
  morpheus/_lib/src/objects/table_info.cpp
  morpheus/_lib/src/stages/preprocess_fil.cpp
  morpheus/_lib/tests/messages/test_dev_doc_ex3.cpp
Labels: bug, non-breaking

#1529 Upgrade `openai` version to 1.13 and `langchain` to version 0.1.9
  .github/workflows/pr.yaml
  ci/scripts/bootstrap_local_ci.sh
  ci/scripts/run_ci_local.sh
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/examples_cuda-121_arch-x86_64.yaml
  dependencies.yaml
  docs/source/conf.py
  examples/llm/agents/kafka_pipeline.py
  examples/llm/agents/simple_pipeline.py
  examples/llm/common/utils.py
  examples/llm/completion/pipeline.py
  examples/llm/vdb_upload/module/content_extractor_module.py
  morpheus/llm/services/llm_service.py
  morpheus/llm/services/nemo_llm_service.py
  morpheus/llm/services/openai_chat_service.py
  morpheus/stages/inference/inference_stage.py
  morpheus/stages/input/arxiv_source.py
  tests/_utils/llm.py
  tests/benchmarks/conftest.py
  tests/conftest.py
  tests/llm/services/test_llm_service_pipe.py
  tests/llm/services/test_nemo_llm_client.py
  tests/llm/services/test_nemo_llm_service.py
  tests/llm/services/test_openai_chat_client.py
  tests/llm/services/test_openai_chat_service.py
  tests/llm/test_completion_pipe.py
  tests/llm/test_rag_standalone_pipe.py
  tests/stages/arxiv/test_arxiv_source.py
  tests/stages/arxiv/test_arxiv_source_pipe.py
Labels: breaking, improvement

#1536 Expose max_retries parameter to OpenAIChatService & OpenAIChatClient
  morpheus/llm/services/openai_chat_service.py
  tests/llm/services/test_openai_chat_client.py
  tests/llm/services/test_openai_chat_service.py
Labels: non-breaking, improvement

#1531 Fix pathlib.Path support for FileSourceStage
  morpheus/_lib/common/__init__.pyi
  morpheus/_lib/common/module.cpp
  morpheus/_lib/include/morpheus/objects/file_types.hpp
  morpheus/_lib/include/morpheus/stages/file_source.hpp
  morpheus/_lib/src/objects/file_types.cpp
  morpheus/_lib/src/stages/file_source.cpp
  morpheus/_lib/stages/__init__.pyi
  morpheus/_lib/stages/module.cpp
  tests/common/test_determine_file_type.py
  tests/test_file_in_out.py
Labels: bug, non-breaking
