Repository nv-morpheus/Morpheus, pull requests merged in 2024-01, with the labels that each got.

#1447 Misc test improvements
  morpheus/modules/payload_batcher.py
  morpheus/utils/column_info.py
  morpheus/utils/schema_transforms.py
  pyproject.toml
  tests/common/test_http_server.py
  tests/modules/test_payload_batcher.py
  tests/test_cli.py
Labels: non-breaking, improvement

#1451 Replace GPUtil with pynvml for benchmark reports
  ci/conda/recipes/morpheus/meta.yaml
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/dev_cuda-118_arch-x86_64.yaml
  dependencies.yaml
  docker/conda/environments/cuda11.8_dev.yml
  examples/digital_fingerprinting/production/morpheus/benchmarks/conftest.py
  tests/benchmarks/conftest.py
Labels: non-breaking, improvement

#1402 Decouple TritonInferenceStage from pipeline mode
  examples/log_parsing/README.md
  examples/log_parsing/inference.py
  examples/log_parsing/messages.py
  examples/log_parsing/postprocessing.py
  examples/log_parsing/run.py
  morpheus/_lib/src/io/serializers.cpp
  morpheus/cli/commands.py
  morpheus/cli/register_stage.py
  morpheus/messages/multi_tensor_message.py
  morpheus/stages/inference/triton_inference_stage.py
  tests/examples/log_parsing/conftest.py
  tests/examples/log_parsing/test_inference.py
  tests/examples/log_parsing/test_log_parsing_pipe.py
  tests/examples/log_parsing/test_postprocessing.py
  tests/test_cli.py
  tests/test_triton_inference_stage.py
Labels: breaking, improvement

#1471 Fix expected JSON config file extension in logger
  morpheus/utils/logger.py
Labels: bug, non-breaking

#1450 GNN fraud detection notebook fix
  models/training-tuning-scripts/fraud-detection-models/gnn-fraud-detection-training.ipynb
Labels: bug, non-breaking

#1460 Fix Loss Function to Improve Model Convergence for `AutoEncoder`
  morpheus/models/dfencoder/autoencoder.py
  tests/dfencoder/test_autoencoder.py
  tests/dfencoder/test_dfencoder_distributed_e2e.py
Labels: bug, non-breaking

#1473 Create a base mixin class for ingress & egress stages
  morpheus/pipeline/boundary_stage_mixin.py
  morpheus/pipeline/pipeline.py
  morpheus/stages/boundary/linear_boundary_stage.py
  tests/pipeline/test_pipeline.py
Labels: non-breaking, feature request

#1442 Eliminate Redundant Fetches in RSS Controller
  docker/conda/environments/cuda11.8_dev.yml
  morpheus/controllers/rss_controller.py
  tests/controllers/test_rss_controller.py
Labels: bug, non-breaking, sherlock

#1462 Misc Conda Improvements
  ci/conda/recipes/morpheus/meta.yaml
  ci/conda/recipes/run_conda_build.sh
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/dev_cuda-118_arch-x86_64.yaml
  dependencies.yaml
  docker/build_conda_packages.sh
  docker/conda/environments/cuda11.8_dev.yml
  examples/abp_nvsmi_detection/README.md
  examples/log_parsing/README.md
  examples/log_parsing/run.py
  setup.py
Labels: non-breaking, improvement
