Repository nv-morpheus/Morpheus, pull requests merged in 2024-07, with the labels that each got.

#1784 Removes unused envioronment variables from Morpheus build docs
  docs/source/developer_guide/contributing.md
  examples/gnn_fraud_detection_pipeline/README.md
Labels: non-breaking, doc

#1785 Add ransomware model to devcontainer
  .devcontainer/docker-compose.yml
Labels: non-breaking, feature request

#1786 Document supported environments for each example
  docs/source/examples.md
  examples/README.md
  examples/abp_nvsmi_detection/README.md
  examples/abp_pcap_detection/README.md
  examples/developer_guide/1_simple_python_stage/README.md
  examples/developer_guide/2_1_real_world_phishing/README.md
  examples/developer_guide/2_2_rabbitmq/README.md
  examples/developer_guide/3_simple_cpp_stage/README.md
  examples/developer_guide/4_rabbitmq_cpp_stage/README.md
  examples/developer_guide/7_python_modules/README.md
  examples/digital_fingerprinting/starter/README.md
  examples/gnn_fraud_detection_pipeline/README.md
  examples/llm/agents/README.md
  examples/llm/completion/README.md
  examples/llm/rag/README.md
  examples/llm/rag/images/persistent_pipeline.png
  examples/llm/rag/persistant_pipeline.py
  examples/llm/rag/run.py
  examples/llm/vdb_upload/README.md
  examples/log_parsing/README.md
  examples/nlp_si_detection/README.md
  examples/ransomware_detection/README.md
  examples/root_cause_analysis/README.md
Labels: non-breaking, doc

#1787 Add fetch data command in build_container_release.sh
  docker/build_container_release.sh
Labels: bug, non-breaking

#1792 Mark the LLM Agents Kafka pipeline as broken
  docs/source/extra_info/known_issues.md
  examples/llm/agents/README.md
Labels: non-breaking, doc

#1793 Fix LLM Agents Kafka pipeline
  docs/source/extra_info/known_issues.md
  examples/llm/agents/README.md
  examples/llm/agents/common.py
  examples/llm/agents/kafka_pipeline.py
  examples/llm/agents/run.py
  examples/llm/agents/simple_pipeline.py
Labels: bug, non-breaking

#1794 Cleanup docs so that each as a single H1 title
  docs/source/examples/llm/index.rst
  examples/doca/README.md
  examples/llm/agents/README.md
  examples/llm/completion/README.md
Labels: non-breaking, doc

#1801 Update `ci/release/update-version.sh` to include missed files
  ci/release/update-version.sh
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/dev_cuda-121_arch-x86_64.yaml
  conda/environments/examples_cuda-121_arch-x86_64.yaml
  conda/environments/runtime_cuda-121_arch-x86_64.yaml
  docs/source/examples.md
  examples/developer_guide/3_simple_cpp_stage/CMakeLists.txt
  examples/developer_guide/4_rabbitmq_cpp_stage/CMakeLists.txt
  manifest.yaml
  morpheus/_lib/common/__init__.pyi
  morpheus/_lib/llm/__init__.pyi
  morpheus/_lib/messages/__init__.pyi
  morpheus/_lib/modules/__init__.pyi
  morpheus/_lib/stages/__init__.pyi
Labels: bug, non-breaking

#1795 Add unique column to output of the `log_parsing` pipeline
  examples/log_parsing/postprocessing.py
  tests/tests_data/examples/log_parsing/expected_out.csv
Labels: non-breaking, feature request

#1800 Update documentation for `vdb_upload` to use realistic source data with the `--file_source` flag
  examples/data/vdb_upload/doca_guides.jsonlines
  examples/data/vdb_upload/nvidia_blogs.jsonlines
  examples/llm/vdb_upload/README.md
Labels: non-breaking, doc

#1806 Install built documentation into release container
  docker/Dockerfile
Labels: non-breaking, improvement

#1808 Remove obsolete version string from compose yamls
  examples/digital_fingerprinting/production/docker-compose.yml
  examples/sid_visualization/docker-compose.yml
Labels: bug, non-breaking

#1813 Fix merging of CLI args and Yaml configs in `vdb_upload` example
  examples/llm/vdb_upload/langchain.py
  examples/llm/vdb_upload/run.py
  examples/llm/vdb_upload/vdb_config.yaml
  examples/llm/vdb_upload/vdb_utils.py
  tests/examples/llm/vdb_upload/test_vdb_utils.py
Labels: bug, non-breaking

#1804 Create a Docker image for Morpheus models
  .devcontainer/docker-compose.yml
  ci/release/update-version.sh
  docker/Dockerfile
  docker/build_container_release.sh
  docker/run_container_release.sh
  docs/source/basics/building_a_pipeline.md
  docs/source/developer_guide/contributing.md
  docs/source/developer_guide/guides/2_real_world_phishing.md
  docs/source/examples.md
  docs/source/getting_started.md
  examples/README.md
  examples/abp_nvsmi_detection/README.md
  examples/abp_pcap_detection/README.md
  examples/doca/vdb_realtime/README.md
  examples/llm/rag/README.md
  examples/llm/vdb_upload/README.md
  examples/log_parsing/README.md
  examples/nlp_si_detection/README.md
  examples/ransomware_detection/README.md
  examples/root_cause_analysis/README.md
  examples/sid_visualization/README.md
  examples/sid_visualization/docker-compose.yml
  models/docker/Dockerfile
  models/docker/README.md
  models/docker/build_container.sh
  models/ransomware-models/ransomw-model-long-rf/checkpoint.tl
  models/ransomware-models/ransomw-model-medium-rf/checkpoint.tl
  models/ransomware-models/ransomw-model-short-rf/checkpoint.tl
  models/triton-model-repo/README.md
  models/triton-model-repo/ransomw-model-long-rf/1/checkpoint.tl
  models/triton-model-repo/ransomw-model-long-rf/config.pbtxt
  models/triton-model-repo/ransomw-model-medium-rf/1/checkpoint.tl
  models/triton-model-repo/ransomw-model-medium-rf/config.pbtxt
  models/triton-model-repo/ransomw-model-short-rf/1/checkpoint.tl
  models/triton-model-repo/ransomw-model-short-rf/config.pbtxt
  scripts/fetch_data.py
  scripts/validation/val-globals.sh
  scripts/validation/val-utils.sh
  tests/benchmarks/README.md
Labels: non-breaking, feature request

#1809 Fix log parsing undefined variable and duplicate sequence id errors
  examples/log_parsing/postprocessing.py
  morpheus/utils/cudf_subword_helper.py
  tests/conftest.py
  tests/examples/log_parsing/test_log_parsing_pipe.py
  tests/examples/log_parsing/test_postprocessing.py
  tests/test_cli.py
  tests/utils/test_cudf_subword_helper.py
Labels: bug, non-breaking

#1825 Remove NVTabular
  ci/conda/recipes/morpheus/meta.yaml
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/dev_cuda-121_arch-x86_64.yaml
  conda/environments/examples_cuda-121_arch-x86_64.yaml
  conda/environments/runtime_cuda-121_arch-x86_64.yaml
  dependencies.yaml
  docs/source/conf.py
  examples/digital_fingerprinting/production/conda_env.yml
  morpheus/utils/column_info.py
  morpheus/utils/downloader.py
  morpheus/utils/nvt/__init__.py
  morpheus/utils/nvt/decorators.py
  morpheus/utils/nvt/extensions/__init__.py
  morpheus/utils/nvt/extensions/morpheus_ext.py
  morpheus/utils/nvt/mutate.py
  morpheus/utils/nvt/patches/__init__.py
  morpheus/utils/nvt/patches/merlin_patches.py
  morpheus/utils/nvt/schema_converters.py
  morpheus/utils/nvt/transforms.py
  morpheus/utils/schema_transforms.py
  tests/examples/digital_fingerprinting/test_dfp_file_to_df.py
  tests/test_column_info.py
  tests/test_downloader.py
  tests/utils/nvt/__init__.py
  tests/utils/nvt/integration/__init__.py
  tests/utils/nvt/integration/test_mutate_op.py
  tests/utils/nvt/test_json_flatten_transform.py
  tests/utils/nvt/test_mutate_op.py
  tests/utils/nvt/test_schema_converters.py
  tests/utils/nvt/test_transforms.py
Labels: non-breaking, feature request

#1807 Ensure the release container does not contain any unintended files
  docker/Dockerfile
  docker/build_container_release.sh
Labels: bug, non-breaking
