Repository nv-morpheus/Morpheus, pull requests merged in 2024-05, with the labels that each got.

#1665 Truncate strings exceeding max_length when inserting to Milvus
  docs/source/extra_info/known_issues.md
  examples/llm/cli.py
  examples/llm/vdb_upload/pipeline.py
  examples/llm/vdb_upload/vdb_utils.py
  morpheus/io/utils.py
  morpheus/service/vdb/milvus_vector_db_service.py
  morpheus/stages/inference/inference_stage.py
  morpheus/utils/type_aliases.py
  tests/conftest.py
  tests/io/test_io_utils.py
  tests/test_milvus_vector_db_service.py
  tests/tests_data/service/milvus_string_collection_conf.json
Labels: bug, non-breaking

#1670 Strip HTML & XML tags from RSS feed input
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/dev_cuda-121_arch-x86_64.yaml
  conda/environments/examples_cuda-121_arch-x86_64.yaml
  conda/environments/runtime_cuda-121_arch-x86_64.yaml
  dependencies.yaml
  examples/llm/vdb_upload/module/rss_source_pipe.py
  examples/llm/vdb_upload/vdb_config.yaml
  examples/llm/vdb_upload/vdb_utils.py
  morpheus/controllers/rss_controller.py
  morpheus/modules/input/rss_source.py
  morpheus/modules/schemas/rss_source_schema.py
  morpheus/stages/input/rss_source_stage.py
  tests/controllers/test_rss_controller.py
Labels: bug, dependencies, non-breaking, Merge After Dependencies

#1674 Update examples to execute from the root of the repo
  docs/source/examples.md
  examples/README.md
  examples/abp_pcap_detection/README.md
  examples/abp_pcap_detection/run.py
  examples/gnn_fraud_detection_pipeline/README.md
  examples/gnn_fraud_detection_pipeline/run.py
  examples/log_parsing/README.md
  examples/log_parsing/run.py
  examples/nlp_si_detection/README.md
  examples/nlp_si_detection/run.sh
  examples/ransomware_detection/README.md
  examples/ransomware_detection/run.py
  examples/root_cause_analysis/README.md
  morpheus/_lib/common/__init__.pyi
  morpheus/_lib/common/module.cpp
  morpheus/_lib/include/morpheus/objects/dtype.hpp
  morpheus/_lib/include/morpheus/stages/inference_client_stage.hpp
  morpheus/_lib/include/morpheus/stages/triton_inference.hpp
  morpheus/_lib/src/objects/dtype.cpp
  morpheus/_lib/src/stages/inference_client_stage.cpp
  morpheus/_lib/src/stages/triton_inference.cpp
  morpheus/_lib/stages/__init__.pyi
  morpheus/_lib/stages/module.cpp
  morpheus/_lib/tests/objects/test_dtype.cpp
  morpheus/_lib/tests/stages/test_triton_inference_stage.cpp
  morpheus/common/__init__.py
  morpheus/pipeline/preallocator_mixin.py
  morpheus/stages/inference/triton_inference_stage.py
Labels: non-breaking, doc

#1644 Update dfp-model-card.md
  models/model-cards/dfp-model-card.md
Labels: non-breaking, doc

#1680 Update phishing-model-card.md
  models/model-cards/phishing-model-card.md
Labels: non-breaking, doc

#1681 Update gnn-fsi-model-card.md
  models/model-cards/gnn-fsi-model-card.md
Labels: non-breaking, doc

#1683 Update abp-model-card.md
  models/model-cards/abp-model-card.md
Labels: non-breaking, doc

#1679 Standardize `NVIDIA_API_BASE` environment variable to `NVAI_BASE_URL`
  morpheus/llm/services/nvfoundation_llm_service.py
Labels: breaking, improvement

#1687 Enable C++ mode for `abp_pcap_detection` example
  examples/abp_pcap_detection/README.md
  examples/abp_pcap_detection/abp_pcap_preprocessing.py
  examples/abp_pcap_detection/run.py
  tests/examples/abp_pcap_detection/test_abp_pcap_preprocessing.py
Labels: bug, non-breaking

#1689 Support the filter_null parameter in the C++ impl of the FileSourceStage
  morpheus/_lib/include/morpheus/io/deserializers.hpp
  morpheus/_lib/include/morpheus/stages/file_source.hpp
  morpheus/_lib/include/morpheus/utilities/table_util.hpp
  morpheus/_lib/src/io/deserializers.cpp
  morpheus/_lib/src/stages/file_source.cpp
  morpheus/_lib/src/utilities/table_util.cpp
  morpheus/_lib/stages/__init__.pyi
  morpheus/_lib/stages/module.cpp
  morpheus/_lib/tests/CMakeLists.txt
  morpheus/_lib/tests/utilities/test_table_util.cpp
  morpheus/io/deserializers.py
  morpheus/io/utils.py
  morpheus/stages/input/file_source_stage.py
  tests/stages/test_file_source_stage_pipe.py
  tests/tests_data/file_with_nans.csv
  tests/tests_data/file_with_nans.jsonlines
  tests/tests_data/file_with_nulls.csv
  tests/tests_data/file_with_nulls.jsonlines
Labels: bug, non-breaking

#1672 Ensuring consistent use of the export macro `MORPHEUS_EXPORT`
  docs/source/developer_guide/guides/3_simple_cpp_stage.md
  docs/source/developer_guide/guides/4_source_cpp_stage.md
  docs/source/developer_guide/guides/8_cpp_modules.md
  examples/developer_guide/3_simple_cpp_stage/src/simple_cpp_stage/_lib/pass_thru.hpp
  examples/developer_guide/4_rabbitmq_cpp_stage/src/rabbitmq_cpp_stage/_lib/rabbitmq_source.hpp
  morpheus/_lib/doca/include/morpheus/doca/doca_source.hpp
  morpheus/_lib/include/morpheus/io/data_loader.hpp
  morpheus/_lib/include/morpheus/io/data_loader_registry.hpp
  morpheus/_lib/include/morpheus/io/deserializers.hpp
  morpheus/_lib/include/morpheus/io/loaders/file.hpp
  morpheus/_lib/include/morpheus/io/loaders/grpc.hpp
  morpheus/_lib/include/morpheus/io/loaders/lambda.hpp
  morpheus/_lib/include/morpheus/io/loaders/payload.hpp
  morpheus/_lib/include/morpheus/io/loaders/rest.hpp
  morpheus/_lib/include/morpheus/io/serializers.hpp
  morpheus/_lib/include/morpheus/messages/control.hpp
  morpheus/_lib/include/morpheus/messages/memory/inference_memory.hpp
  morpheus/_lib/include/morpheus/messages/memory/inference_memory_fil.hpp
  morpheus/_lib/include/morpheus/messages/memory/inference_memory_nlp.hpp
  morpheus/_lib/include/morpheus/messages/memory/response_memory.hpp
  morpheus/_lib/include/morpheus/messages/memory/response_memory_probs.hpp
  morpheus/_lib/include/morpheus/messages/memory/tensor_memory.hpp
  morpheus/_lib/include/morpheus/messages/meta.hpp
  morpheus/_lib/include/morpheus/messages/multi.hpp
  morpheus/_lib/include/morpheus/messages/multi_inference.hpp
  morpheus/_lib/include/morpheus/messages/multi_inference_fil.hpp
  morpheus/_lib/include/morpheus/messages/multi_inference_nlp.hpp
  morpheus/_lib/include/morpheus/messages/multi_response.hpp
  morpheus/_lib/include/morpheus/messages/multi_response_probs.hpp
  morpheus/_lib/include/morpheus/messages/multi_tensor.hpp
  morpheus/_lib/include/morpheus/modules/data_loader_module.hpp
  morpheus/_lib/include/morpheus/objects/dtype.hpp
  morpheus/_lib/include/morpheus/objects/factory_registry.hpp
  morpheus/_lib/include/morpheus/objects/fiber_queue.hpp
  morpheus/_lib/include/morpheus/objects/file_types.hpp
  morpheus/_lib/include/morpheus/objects/filter_source.hpp
  morpheus/_lib/include/morpheus/objects/mutable_table_ctx_mgr.hpp
  morpheus/_lib/include/morpheus/objects/rmm_tensor.hpp
  morpheus/_lib/include/morpheus/objects/tensor.hpp
  morpheus/_lib/include/morpheus/objects/wrapped_tensor.hpp
  morpheus/_lib/include/morpheus/stages/add_classification.hpp
  morpheus/_lib/include/morpheus/stages/add_scores.hpp
  morpheus/_lib/include/morpheus/stages/add_scores_stage_base.hpp
  morpheus/_lib/include/morpheus/stages/deserialize.hpp
  morpheus/_lib/include/morpheus/stages/file_source.hpp
  morpheus/_lib/include/morpheus/stages/filter_detection.hpp
  morpheus/_lib/include/morpheus/stages/http_server_source_stage.hpp
  morpheus/_lib/include/morpheus/stages/kafka_source.hpp
  morpheus/_lib/include/morpheus/stages/preallocate.hpp
  morpheus/_lib/include/morpheus/stages/preprocess_fil.hpp
  morpheus/_lib/include/morpheus/stages/preprocess_nlp.hpp
  morpheus/_lib/include/morpheus/stages/serialize.hpp
  morpheus/_lib/include/morpheus/stages/write_to_file.hpp
  morpheus/_lib/include/morpheus/utilities/http_server.hpp
  morpheus/_lib/include/morpheus/utilities/python_util.hpp
Labels: non-breaking, improvement

#1692 Remove `pyarrow_hotfix` import from `__init__.py`
  ci/conda/recipes/run_conda_build.sh
  docker/build_conda_packages.sh
  docker/run_container_dev.sh
  morpheus/__init__.py
Labels: bug, non-breaking

#1637 Update `ControlMessage` to hold arbitrary Python objects & update `MessageMeta` to copy & slice
  morpheus/_lib/cmake/libmorpheus.cmake
  morpheus/_lib/include/morpheus/messages/control.hpp
  morpheus/_lib/include/morpheus/messages/meta.hpp
  morpheus/_lib/include/morpheus/pybind11/json.hpp
  morpheus/_lib/include/morpheus/utilities/json_types.hpp
  morpheus/_lib/messages/__init__.pyi
  morpheus/_lib/messages/module.cpp
  morpheus/_lib/src/messages/control.cpp
  morpheus/_lib/src/messages/meta.cpp
  morpheus/_lib/src/utilities/json_types.cpp
  morpheus/_lib/tests/CMakeLists.txt
  morpheus/_lib/tests/messages/test_control_message.cpp
  morpheus/_lib/tests/messages/test_message_meta.cpp
  tests/messages/test_control_message.py
  tests/messages/test_message_meta.py
  tests/tests_data/csv_sample.csv
Labels: non-breaking, improvement

#1700 Remove unused MLflow client arg from DFP inference implementations
  docs/source/developer_guide/guides/10_modular_pipeline_digital_fingerprinting.md
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_inference.py
  examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_inference_stage.py
  examples/digital_fingerprinting/production/morpheus/dfp/utils/model_cache.py
Labels: non-breaking, improvement

#1682 Update dfp-model-card.md
  models/model-cards/dfp-model-card.md
Labels: non-breaking, doc

#1684 Update root-cause-analysis-model-card.md
  models/model-cards/abp-model-card.md
  models/model-cards/dfp-model-card.md
  models/model-cards/gnn-fsi-model-card.md
  models/model-cards/phishing-model-card.md
  models/model-cards/root-cause-analysis-model-card.md
Labels: non-breaking, doc

#1623 Support `ControlMessage` for `Preprocess` and `PostProcess` stages
  morpheus/_lib/cmake/libmorpheus.cmake
  morpheus/_lib/include/morpheus/stages/filter_detections.hpp
  morpheus/_lib/src/stages/add_scores_stage_base.cpp
  morpheus/_lib/src/stages/filter_detection.cpp
  morpheus/_lib/src/stages/filter_detections.cpp
  morpheus/_lib/src/stages/preprocess_fil.cpp
  morpheus/_lib/src/stages/preprocess_nlp.cpp
  morpheus/_lib/stages/__init__.pyi
  morpheus/_lib/stages/module.cpp
  morpheus/controllers/filter_detections_controller.py
  morpheus/stages/postprocess/filter_detections_stage.py
  morpheus/stages/postprocess/generate_viz_frames_stage.py
  morpheus/stages/postprocess/ml_flow_drift_stage.py
  morpheus/stages/postprocess/timeseries_stage.py
  morpheus/stages/postprocess/validation_stage.py
  morpheus/stages/preprocess/preprocess_ae_stage.py
  morpheus/stages/preprocess/preprocess_fil_stage.py
  tests/stages/test_filter_detections_stage.py
  tests/stages/test_generate_viz_frames_stage.py
  tests/stages/test_ml_flow_drift_stage.py
  tests/stages/test_preprocess_ae_stage.py
  tests/stages/test_preprocess_fil_stage.py
  tests/stages/test_preprocess_nlp_stage.py
  tests/stages/test_timeseries_stage.py
  tests/stages/test_validation_stage.py
  tests/test_add_classifications_stage.py
  tests/test_add_scores_stage.py
  tests/test_filter_detections_stage.py
  tests/test_filter_detections_stage_pipe.py
Labels: non-breaking, feature request

#1677 Fix non-deterministic output of gnn sampler
  examples/gnn_fraud_detection_pipeline/stages/model.py
  tests/examples/gnn_fraud_detection_pipeline/test_graph_sage_stage.py
  tests/tests_data/examples/gnn_fraud_detection_pipeline/inductive_emb.csv
Labels: non-breaking, improvement

#1695 Handling agent parsing error and adding a default value for NVAI_BASE_URL
  morpheus/llm/nodes/langchain_agent_node.py
  morpheus/llm/services/nvfoundation_llm_service.py
  tests/llm/nodes/test_langchain_agent_node.py
Labels: improvement

#1704 Use EnvConfigValue for passing env-configured arguments to services
  morpheus/llm/services/nemo_llm_service.py
  morpheus/llm/services/openai_chat_service.py
  morpheus/utils/env_config_value.py
  tests/llm/services/test_openai_chat_client.py
  tests/test_env_config_value.py
Labels: non-breaking, improvement

#1698 Fixes and unit test updates to OpenAI client
  morpheus/llm/services/openai_chat_service.py
  tests/llm/services/test_openai_chat_client.py
Labels: bug, non-breaking

#1658 Update devcontainer to use latest build utils
  .devcontainer/Dockerfile
  .devcontainer/cuda12.1-conda/devcontainer.json
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/initialize-command.sh
  .devcontainer/opt/morpheus/bin/post-attach-command.sh
  .devcontainer/opt/morpheus/etc/.gdbinit
  .devcontainer/opt/morpheus/etc/enable_conda_libstd_pretty_print.py
  docker/optional_deps/doca.sh
  manifest.yaml
Labels: breaking, improvement

#1721 Add function return documentation for `LLMService`
  morpheus/llm/services/llm_service.py
Labels: non-breaking, doc

#1707 Fix description for `cache_mode` option of DFP Rolling Window module
  docs/source/modules/examples/digital_fingerprinting/dfp_deployment.md
  docs/source/modules/examples/digital_fingerprinting/dfp_inference_pipe.md
  docs/source/modules/examples/digital_fingerprinting/dfp_rolling_window.md
  docs/source/modules/examples/digital_fingerprinting/dfp_training_pipe.md
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_deployment.py
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_inference_pipe.py
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_rolling_window.py
  examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_training_pipe.py
  examples/digital_fingerprinting/production/morpheus/dfp/utils/config_generator.py
  examples/digital_fingerprinting/production/morpheus/notebooks/dfp_azure_integrated_training.ipynb
  examples/digital_fingerprinting/production/morpheus/notebooks/dfp_duo_integrated_training.ipynb
Labels: non-breaking, doc

#1622 Update CI to install DOCA and build Morpheus DOCA components.
  .github/workflows/pr.yaml
  ci/runner/Dockerfile
  ci/scripts/github/common.sh
  ci/scripts/run_ci_local.sh
Labels: breaking, feature request

#1705 Support passing a custom parser to `HttpServerSourceStage` and `HttpClientSourceStage` stages
  morpheus/cli/register_stage.py
  morpheus/stages/input/http_client_source_stage.py
  morpheus/stages/input/http_server_source_stage.py
  morpheus/stages/output/http_client_sink_stage.py
  tests/mock_rest_server/mocks/api/v1/invalid/GET.mock
  tests/stages/test_http_client_source_stage_pipe.py
  tests/stages/test_http_server_source_stage.py
  tests/stages/test_http_server_source_stage_pipe.py
  tests/test_http_client_source_stage_pipe.py
Labels: non-breaking, improvement

#1719 Generate deprecation warning for `MultiMessage`
  docs/source/developer_guide/guides/9_control_messages.md
  morpheus/messages/memory/response_memory.py
  morpheus/messages/message_base.py
  morpheus/messages/multi_response_message.py
  morpheus/utils/logger.py
  tests/test_logger.py
  tests/test_multi_message.py
Labels: non-breaking, improvement
