Repository nv-morpheus/Morpheus, pull requests merged in 2025-03, with the labels that each got.

#2098 Kinetica Vector DB Service
  conda/environments/all_cuda-128_arch-aarch64.yaml
  conda/environments/all_cuda-128_arch-x86_64.yaml
  conda/environments/dev_cuda-128_arch-aarch64.yaml
  conda/environments/dev_cuda-128_arch-x86_64.yaml
  conda/environments/examples_cuda-128_arch-aarch64.yaml
  conda/environments/examples_cuda-128_arch-x86_64.yaml
  conda/environments/runtime_cuda-128_arch-aarch64.yaml
  conda/environments/runtime_cuda-128_arch-x86_64.yaml
  dependencies.yaml
  examples/llm/kinetica_pipeline/kinetica_pipeline_example.py
  pyproject.toml
  python/morpheus_llm/morpheus_llm/requirements_morpheus_llm_arch-aarch64.txt
  python/morpheus_llm/morpheus_llm/requirements_morpheus_llm_arch-x86_64.txt
  python/morpheus_llm/morpheus_llm/service/vdb/kinetica_vector_db_service.py
  tests/conftest.py
  tests/morpheus_llm/services/test_kinetica_vector_db_service.py
Labels: non-breaking, feature request

#2201 Remove cudf_helpers.pyx patch for 24.12 bug
  python/morpheus/morpheus/_lib/cudf_helpers.pyx
  python/morpheus/morpheus/_lib/cudf_helpers/__init__.pyi
Labels: non-breaking, improvement

#2203 Switch to the Nvidia Sphinx Theme for documentation
  ci/conda/recipes/morpheus-libs/meta.yaml
  ci/conda/recipes/morpheus/meta.yaml
  ci/scripts/github/docs.sh
  conda/environments/all_cuda-128_arch-aarch64.yaml
  conda/environments/all_cuda-128_arch-x86_64.yaml
  conda/environments/dev_cuda-128_arch-aarch64.yaml
  conda/environments/dev_cuda-128_arch-x86_64.yaml
  conda/environments/examples_cuda-128_arch-aarch64.yaml
  conda/environments/examples_cuda-128_arch-x86_64.yaml
  conda/environments/runtime_cuda-128_arch-aarch64.yaml
  conda/environments/runtime_cuda-128_arch-x86_64.yaml
  dependencies.yaml
  docs/source/_static/copybutton.css
  docs/source/_static/example_mod.js
  docs/source/_static/infoboxes.css
  docs/source/_static/omni-style.css
  docs/source/_static/params.css
  docs/source/_static/py_properties.css
  docs/source/_static/references.css
  docs/source/conf.py
  docs/source/developer_guide/contributing.md
  python/morpheus/morpheus/stages/input/kafka_source_stage.py
Labels: non-breaking, feature request, conda-build

#2205 Add analytics to rendered documentation
  docs/source/conf.py
Labels: non-breaking, doc

#2206 Add test to verify that #2202 is fixed
  tests/morpheus/pipeline/test_pipeline_error.py
Labels: bug, non-breaking

#2208 Fix docker container for Python 3.12
  ci/conda/recipes/python-dbg/conda_build_config.yaml
  docker/Dockerfile
Labels: bug, non-breaking

#2207 Invoke `CudfHelper::load()` from the main Python thread
  python/morpheus/morpheus/_lib/common/__init__.pyi
  python/morpheus/morpheus/_lib/common/module.cpp
  python/morpheus/morpheus/_lib/include/morpheus/utilities/cudf_util.hpp
  python/morpheus/morpheus/_lib/src/io/deserializers.cpp
  python/morpheus/morpheus/_lib/src/io/serializers.cpp
  python/morpheus/morpheus/_lib/src/utilities/cudf_util.cpp
  python/morpheus/morpheus/_lib/tests/test_utils/common.cpp
  python/morpheus/morpheus/common/__init__.py
  python/morpheus/morpheus/pipeline/pipeline.py
  python/morpheus/morpheus/stages/input/kafka_source_stage.py
Labels: bug, non-breaking
