Repository nv-morpheus/Morpheus, pull requests merged in 2025-01, with the labels that each got.

#2090 Avoid private cudf DeviceScalar in favor of using pylibcudf & pyarrow
  python/morpheus/morpheus/_lib/cudf_helpers.pyx
  python/morpheus/morpheus/_lib/cudf_helpers/__init__.pyi
Labels: non-breaking, improvement

#2055 Update the version of yapf being used by pre-commit
  .pre-commit-config.yaml
  conda/environments/all_cuda-125_arch-x86_64.yaml
  conda/environments/dev_cuda-125_arch-x86_64.yaml
  dependencies.yaml
Labels: bug, non-breaking

#2079 Remove triton optimization config, causing error for multi gpu inference
  models/triton-model-repo/phishing-bert-onnx/config.pbtxt
  models/triton-model-repo/sid-minibert-onnx/config.pbtxt
Labels: non-breaking, improvement

#2104 Specify `count: all` for GPU resources in docker compose yamls
  .devcontainer/Dockerfile
  docker/Dockerfile
  examples/digital_fingerprinting/production/Dockerfile
  examples/digital_fingerprinting/production/docker-compose.yml
  examples/sid_visualization/docker-compose.yml
Labels: bug, non-breaking

#2106 Improved DFP documentation, logging and fix MonitorStage
  ci/release/update-version.sh
  dependencies.yaml
  docs/source/developer_guide/guides/5_digital_fingerprinting.md
  examples/digital_fingerprinting/fetch_example_data.py
  examples/digital_fingerprinting/production/README.md
  examples/digital_fingerprinting/production/conda/environments/dfp_example_cuda-125_arch-x86_64.yaml
  examples/digital_fingerprinting/production/dfp_azure_pipeline.py
  examples/digital_fingerprinting/production/dfp_duo_pipeline.py
  examples/digital_fingerprinting/production/dfp_integrated_training_batch_pipeline.py
  examples/digital_fingerprinting/production/dfp_integrated_training_streaming_pipeline.py
  examples/digital_fingerprinting/production/docker-compose.yml
  examples/digital_fingerprinting/production/grafana/run.py
  python/morpheus/morpheus/stages/general/monitor_stage.py
Labels: bug, non-breaking

#2109 Remove some cudf._lib.column.Column annotations in Cython
  python/morpheus/morpheus/_lib/cudf_helpers.pyx
Labels: non-breaking, improvement

#2111 Support ARM builds for the Morpheus and Models container
  docker/Dockerfile
  docker/build_container.sh
  docker/run_container.sh
  docker/run_container_dev.sh
  docker/run_container_release.sh
  models/docker/Dockerfile
  models/docker/build_container.sh
Labels: non-breaking, improvement

#2112 Fix `test_configure_logging_custom_handlers` test for ARM
  tests/morpheus/utils/test_logger.py
Labels: bug, non-breaking

#2117 Documentation improvements
  .gitignore
  ci/release/update-version.sh
  conda/environments/model-utils_cuda-125_arch-aarch64.yaml
  dependencies.yaml
  docs/source/basics/overview.rst
  docs/source/conf.py
  docs/source/developer_guide/contributing.md
  docs/source/developer_guide/guides/5_digital_fingerprinting.md
  examples/abp_nvsmi_detection/README.md
  examples/developer_guide/3_simple_cpp_stage/README.md
  examples/developer_guide/4_rabbitmq_cpp_stage/README.md
  examples/digital_fingerprinting/production/Dockerfile
  examples/digital_fingerprinting/production/README.md
  examples/digital_fingerprinting/production/mlflow/Dockerfile
  examples/digital_fingerprinting/production/morpheus/benchmarks/README.md
  examples/doca/vdb_realtime/README.md
  examples/gnn_fraud_detection_pipeline/README.md
  examples/llm/agents/README.md
  examples/llm/completion/README.md
  examples/llm/rag/README.md
  examples/llm/vdb_upload/README.md
  models/README.md
  models/training-tuning-scripts/fraud-detection-models/README.md
  models/triton-model-repo/README.md
  python/morpheus/morpheus/stages/input/arxiv_source.py
  python/morpheus/morpheus/utils/onnx_to_trt.py
  python/morpheus_llm/morpheus_llm/error.py
  tests/benchmarks/README.md
  tests/conftest.py
  tests/morpheus_llm/stages/arxiv/conftest.py
Labels: non-breaking, doc

#2121 Ensure `MonitorStage` returns the cursor back to the end of output
  python/morpheus/morpheus/_lib/include/morpheus/controllers/monitor_controller.hpp
Labels: bug, non-breaking

#2127 Fix DOCA builds on ARM64
  CMakeLists.txt
  ci/scripts/github/cmake_all.sh
  cmake/package_search/Finddoca.cmake
  cmake/package_search/Findlibdpdk.cmake
Labels: bug, non-breaking

#2129 Performance improvements for `AbpPcapPreprocessingStage`
  examples/abp_pcap_detection/abp_pcap_preprocessing.py
Labels: non-breaking, improvement

#2130 Update `ransomware_detection` documentation to reflect default Dask values
  examples/ransomware_detection/README.md
Labels: non-breaking, doc

#2128 Document known ARM64 issues
  docker/build_container.sh
  docker/build_container_dev.sh
  docker/build_container_release.sh
  docs/source/extra_info/known_issues.md
  examples/digital_fingerprinting/production/grafana/README.md
  examples/digital_fingerprinting/visualization/README.md
  examples/gnn_fraud_detection_pipeline/README.md
  examples/llm/rag/README.md
  examples/llm/vdb_upload/README.md
  examples/llm/vdb_upload/vdb_utils.py
Labels: non-breaking, doc

#2137 Suppress spurious socket error messages from `GenerateVizFramesStage` on shutdown
  examples/developer_guide/2_2_rabbitmq/README.md
  examples/developer_guide/4_rabbitmq_cpp_stage/README.md
  python/morpheus/morpheus/stages/postprocess/generate_viz_frames_stage.py
Labels: bug, non-breaking

#2138 Update `abp_nvsmi_detection` example README
  examples/abp_nvsmi_detection/README.md
Labels: non-breaking, doc

#2140 Fix C++ version of `MonitorStage` output issue caused by out of order function calls
  python/morpheus/morpheus/_lib/include/morpheus/controllers/monitor_controller.hpp
Labels: bug, non-breaking

#2142 Fix output directory for `gnn_fraud_detection_pipeline` example
  examples/gnn_fraud_detection_pipeline/README.md
Labels: bug, non-breaking

#2146 Fix file paths in `log_parsing` CLI example
  examples/log_parsing/README.md
  examples/log_parsing/postprocessing.py
Labels: bug, non-breaking

#2159 Ensure that `MORPHEUS_ROOT_HOST` is defined in the models `Dockerfile`
  models/docker/Dockerfile
  models/docker/build_container.sh
Labels: bug, non-breaking

#2156 Work-around glog dependency issues for C++ examples
  examples/developer_guide/3_simple_cpp_stage/CMakeLists.txt
  examples/developer_guide/3_simple_cpp_stage/src/simple_cpp_stage/_lib/CMakeLists.txt
  examples/developer_guide/4_rabbitmq_cpp_stage/CMakeLists.txt
  examples/developer_guide/4_rabbitmq_cpp_stage/src/rabbitmq_cpp_stage/_lib/CMakeLists.txt
Labels: bug, non-breaking

#2160 Documentation improvements for the C++ developer guides
  docs/source/developer_guide/guides/3_simple_cpp_stage.md
  docs/source/developer_guide/guides/4_source_cpp_stage.md
Labels: non-breaking, doc

#2164 Mention using `--bootstrap_servers` option when running Kafka pipelines in `devcontainer`
  .devcontainer/bin/dev-kafka-start
  examples/llm/agents/README.md
Labels: non-breaking, doc

#2145 CI: Add new L4 runner for test
  .github/workflows/ci_pipe.yml
Labels: non-breaking, improvement

#2143 Remove TRT optimization from `all-MiniLM-L6-v2`
  docs/source/extra_info/known_issues.md
  models/triton-model-repo/all-MiniLM-L6-v2/config.pbtxt
Labels: bug, non-breaking

#2162 Document known Arm64 issues and work-around PyTorch installation issues for DFP
  docs/source/extra_info/known_issues.md
  docs/source/getting_started.md
  examples/digital_fingerprinting/production/Dockerfile
  examples/digital_fingerprinting/production/grafana/README.md
Labels: bug, non-breaking
