Repository nv-morpheus/Morpheus, pull requests merged in 2025-07, with the labels that each got.

#2235 Clamp marshmallow to <4 to avoid version incompatibilities
  conda/environments/all_cuda-128_arch-x86_64.yaml
  conda/environments/dev_cuda-128_arch-x86_64.yaml
  conda/environments/examples_cuda-128_arch-x86_64.yaml
  conda/environments/runtime_cuda-128_arch-x86_64.yaml
  dependencies.yaml
  python/morpheus_llm/morpheus_llm/requirements_morpheus_llm_arch-aarch64.txt
  python/morpheus_llm/morpheus_llm/requirements_morpheus_llm_arch-x86_64.txt
Labels: bug, non-breaking

#2230 Update Dependency
  conda/environments/all_cuda-128_arch-aarch64.yaml
  conda/environments/all_cuda-128_arch-x86_64.yaml
  conda/environments/dev_cuda-128_arch-aarch64.yaml
  conda/environments/dev_cuda-128_arch-x86_64.yaml
  conda/environments/runtime_cuda-128_arch-aarch64.yaml
  conda/environments/runtime_cuda-128_arch-x86_64.yaml
  dependencies.yaml
Labels: non-breaking, improvement

#2215 Fix script reference in DFP example's Dockerfile from 125 to 128
  examples/digital_fingerprinting/production/Dockerfile
Labels: bug, non-breaking

#2226 Add Data Loss Prevention Example
  ci/vale/styles/config/vocabularies/morpheus/accept.txt
  conda/environments/all_cuda-128_arch-aarch64.yaml
  conda/environments/all_cuda-128_arch-x86_64.yaml
  conda/environments/dev_cuda-128_arch-aarch64.yaml
  conda/environments/dev_cuda-128_arch-x86_64.yaml
  conda/environments/examples_cuda-128_arch-aarch64.yaml
  conda/environments/examples_cuda-128_arch-x86_64.yaml
  conda/environments/model-utils_cuda-128_arch-aarch64.yaml
  conda/environments/model-utils_cuda-128_arch-x86_64.yaml
  conda/environments/runtime_cuda-128_arch-aarch64.yaml
  conda/environments/runtime_cuda-128_arch-x86_64.yaml
  dependencies.yaml
  examples/CMakeLists.txt
  examples/README.md
  examples/data_loss_prevention/CMakeLists.txt
  examples/data_loss_prevention/README.md
  examples/data_loss_prevention/data/regex_patterns.json
  examples/data_loss_prevention/dlp_stages/__init__.py
  examples/data_loss_prevention/dlp_stages/_lib/CMakeLists.txt
  examples/data_loss_prevention/dlp_stages/_lib/regex_processor.cpp
  examples/data_loss_prevention/dlp_stages/_lib/regex_processor.hpp
  examples/data_loss_prevention/dlp_stages/_lib/regex_processor/__init__.pyi
  examples/data_loss_prevention/dlp_stages/datasets_source.py
  examples/data_loss_prevention/dlp_stages/dlp_input_processor.py
  examples/data_loss_prevention/dlp_stages/gliner_processor.py
  examples/data_loss_prevention/dlp_stages/gliner_triton.py
  examples/data_loss_prevention/dlp_stages/regex_processor.py
  examples/data_loss_prevention/dlp_stages/risk_scorer.py
  examples/data_loss_prevention/run.py
  models/.gitattributes
  models/dlp_models/gliner_bi_encoder/config.json
  models/dlp_models/gliner_bi_encoder/gliner_config.json
  models/dlp_models/gliner_bi_encoder/label_embedding.pt
  models/dlp_models/gliner_bi_encoder/model.onnx
  models/dlp_models/gliner_bi_encoder/tokenizer.json
  models/dlp_models/gliner_bi_encoder/tokenizer_config.json
  models/dlp_models/script/convert_gliner_onnx.py
  models/dlp_models/script/setup_onnx_model.sh
  models/triton-model-repo/gliner-bi-encoder-onnx/1/model.onnx
  models/triton-model-repo/gliner-bi-encoder-onnx/config.pbtxt
  python/morpheus/morpheus/_lib/include/morpheus/objects/table_info.hpp
  python/morpheus/morpheus/_lib/src/io/serializers.cpp
  python/morpheus/morpheus/_lib/src/objects/table_info.cpp
  python/morpheus/morpheus/_lib/tests/CMakeLists.txt
  python/morpheus/morpheus/_lib/tests/test_table_info.cpp
  python/morpheus/morpheus/io/serializers.py
  tests/morpheus/io/test_serializers.py
  tests/tests_data/nested.jsonlines
Labels: non-breaking, feature request

#2240 DLP diagram formatting update
  examples/data_loss_prevention/README.md
Labels: non-breaking, doc

#2244 Support running the DLP example within the release container
  examples/data_loss_prevention/README.md
  examples/data_loss_prevention/compile.sh
  examples/data_loss_prevention/dlp_stages/gliner_processor.py
  examples/data_loss_prevention/dlp_stages/gliner_triton.py
  examples/data_loss_prevention/dlp_stages/regex_processor.py
  examples/data_loss_prevention/run.py
Labels: bug, non-breaking

#2245 Forward-merge branch-24.06 into branch-24.10
  .github/workflows/ci_pipe.yml
  conda/environments/all_cuda-125_arch-x86_64.yaml
  conda/environments/dev_cuda-125_arch-x86_64.yaml
  conda/environments/examples_cuda-125_arch-x86_64.yaml
  conda/environments/runtime_cuda-125_arch-x86_64.yaml
  dependencies.yaml
  docs/source/developer_guide/guides/2_real_world_phishing.md
Labels: non-breaking, improvement

#2246 Update DLP README and notebook to include new diagrams
  .gitattributes
  examples/data_loss_prevention/README.md
  examples/data_loss_prevention/images/dlp_diagram.png
  models/validation-inference-scripts/dlp-models/data/dlp_pipeline_diagram.png
  models/validation-inference-scripts/dlp-models/dlp_inference_workflow.ipynb
Labels: non-breaking, doc

#2251 Add optional databricks packages to the all env, and rename the group
  conda/environments/all_cuda-128_arch-aarch64.yaml
  conda/environments/all_cuda-128_arch-x86_64.yaml
  dependencies.yaml
Labels: bug, non-breaking

#2250 Update examples content list README.md to include DLP pipeline in the list
  examples/README.md
Labels: non-breaking, doc, ! - Hotfix

#2255 Update DLP diagram
  examples/data_loss_prevention/images/dlp_diagram.png
Labels: non-breaking, doc

#2257 Fix handling of labels in DLP example
  examples/data_loss_prevention/README.md
  examples/data_loss_prevention/dlp_stages/gliner_triton.py
  examples/data_loss_prevention/run.py
Labels: bug, non-breaking

#2260 Fix DFP docker build issues
  examples/digital_fingerprinting/production/Dockerfile
  examples/digital_fingerprinting/production/docker/condarc
  examples/digital_fingerprinting/production/mlflow/Dockerfile
Labels: bug, non-breaking

#2268 Set a reasonable num_threads default value for ransomware_detection example
  examples/ransomware_detection/run.py
Labels: non-breaking, improvement

#2272 Remove NeMoLLM as a dependency, and remove as an option in LLM pipelines
  conda/environments/all_cuda-128_arch-aarch64.yaml
  conda/environments/all_cuda-128_arch-x86_64.yaml
  conda/environments/examples_cuda-128_arch-aarch64.yaml
  conda/environments/examples_cuda-128_arch-x86_64.yaml
  dependencies.yaml
  examples/llm/completion/README.md
  examples/llm/completion/run.py
  examples/llm/rag/README.md
  examples/llm/rag/run.py
  python/morpheus_llm/morpheus_llm/llm/services/nemo_llm_service.py
  python/morpheus_llm/morpheus_llm/requirements_morpheus_llm_arch-aarch64.txt
  python/morpheus_llm/morpheus_llm/requirements_morpheus_llm_arch-x86_64.txt
  tests/morpheus_llm/llm/conftest.py
  tests/morpheus_llm/llm/services/conftest.py
  tests/morpheus_llm/llm/services/test_llm_service.py
  tests/morpheus_llm/llm/services/test_llm_service_pipe.py
  tests/morpheus_llm/llm/services/test_nemo_llm_client.py
  tests/morpheus_llm/llm/services/test_nemo_llm_service.py
  tests/morpheus_llm/llm/test_completion_pipe.py
  tests/morpheus_llm/llm/test_rag_standalone_pipe.py
Labels: bug, breaking

#2282 Allow empty DataFrame slices
  python/morpheus/morpheus/_lib/src/objects/table_info.cpp
Labels: bug, non-breaking

#2283 Replace default model in RAG pipeline with Nvidia hosted model
  examples/llm/common/utils.py
  examples/llm/completion/README.md
  examples/llm/rag/README.md
  examples/llm/rag/run.py
  examples/llm/rag/standalone_pipeline.py
Labels: bug, non-breaking

#2277 Fix: examples build on aarch64
  examples/data_loss_prevention/dlp_stages/_lib/CMakeLists.txt
  examples/developer_guide/3_simple_cpp_stage/compile.sh
  examples/developer_guide/3_simple_cpp_stage/src/simple_cpp_stage/_lib/CMakeLists.txt
  examples/developer_guide/4_rabbitmq_cpp_stage/compile.sh
  examples/developer_guide/4_rabbitmq_cpp_stage/src/rabbitmq_cpp_stage/_lib/CMakeLists.txt
Labels: bug, non-breaking

#2284 Fix type checking of the input message in PassThruStage example
  docs/source/developer_guide/guides/3_simple_cpp_stage.md
  examples/developer_guide/3_simple_cpp_stage/src/simple_cpp_stage/pass_thru.py
Labels: bug, non-breaking

#2288 Fix devcontainer builds
  .devcontainer/Dockerfile
  .devcontainer/cuda12.8-conda/devcontainer.json
  .devcontainer/unset-safepath.sh
  docs/source/extra_info/known_issues.md
  examples/data_loss_prevention/README.md
  examples/log_parsing/README.md
Labels: bug, non-breaking

#2290 Fix mlflow dependency in Conda packages
  ci/conda/recipes/morpheus-core/cmake_common.sh
  ci/conda/recipes/morpheus-core/conda_build_config.yaml
  ci/conda/recipes/morpheus-core/meta.yaml
  ci/conda/recipes/morpheus-core/morpheus_core_build.sh
  ci/conda/recipes/morpheus-core/morpheus_core_test.sh
  ci/conda/recipes/morpheus-dfp/cmake_common.sh
  ci/conda/recipes/morpheus-dfp/conda_build_config.yaml
  ci/conda/recipes/morpheus-dfp/meta.yaml
  ci/conda/recipes/morpheus-dfp/morpheus_dfp_build.sh
  ci/conda/recipes/morpheus-dfp/morpheus_dfp_test.sh
  ci/conda/recipes/morpheus-llm/cmake_common.sh
  ci/conda/recipes/morpheus-llm/conda_build_config.yaml
  ci/conda/recipes/morpheus-llm/meta.yaml
  ci/conda/recipes/morpheus-llm/morpheus_llm_build.sh
  ci/conda/recipes/morpheus-llm/morpheus_llm_test.sh
  ci/conda/recipes/run_conda_build.sh
Labels: bug, dependencies, non-breaking, conda-build

#2291 Fix: typo for PROJECT_IS_TOP_LEVEL for building examples
  examples/data_loss_prevention/dlp_stages/_lib/CMakeLists.txt
  examples/developer_guide/3_simple_cpp_stage/src/simple_cpp_stage/_lib/CMakeLists.txt
  examples/developer_guide/4_rabbitmq_cpp_stage/src/rabbitmq_cpp_stage/_lib/CMakeLists.txt
Labels: bug, non-breaking

#2293 Update nlp_si_detection example `README.md` to reflect that boolean values are used in the output
  examples/nlp_si_detection/README.md
Labels: non-breaking, doc

#2295 Document the licences of additional dependencies
  examples/data_loss_prevention/README.md
Labels: non-breaking, doc

#2297 Update Python stub files
  docs/source/conda_packages.md
  python/morpheus/morpheus/_lib/common/__init__.pyi
  python/morpheus/morpheus/_lib/messages/__init__.pyi
  python/morpheus/morpheus/_lib/modules/__init__.pyi
  python/morpheus/morpheus/_lib/stages/__init__.pyi
  python/morpheus_llm/morpheus_llm/_lib/llm/__init__.pyi
Labels: non-breaking, improvement
